import SP1Clean.Math.Word
import SP1Clean.Extracted.ExtractionDSL
import Clean.Utils.Tactics.ProvableStructDeriving

/-! # AUTO-GENERATED system-table Rust AIR oracle — do not edit by hand.

Generated by `update_extracted.py` from `sp1-constraint-compiler --chip Byte --format lean`. Contains every `Byte` main-trace column in upstream index order, the complete per-row `assertZero` list, and the complete interaction list. The flat vector deliberately avoids inventing semantic field names in the extraction layer; audited adapters may name selected indices above this anchor. Reuses the no helper module(s). -/

set_option linter.all false  -- auto-generated: skip linters

namespace SP1Clean.Extracted
open SP1Clean

-- Generated Lean code for chip ByteChip

structure ByteCols (F : Type) where
  values : (Vector F 6)
deriving ProvableStruct

namespace ByteCols

set_option maxRecDepth 100000 in
@[irreducible] def asserts {F : Type} [Field F] [CoeHead F ℕ]
  (_cols : (ByteCols F))
  (_preprocessed : (Vector F 7))
  (_publicValues : (Vector F 160))
  : List F :=
  [
  ]

set_option maxRecDepth 100000 in
@[irreducible] def interactions {F : Type} [Field F] [CoeHead F ℕ]
  (cols : (ByteCols F))
  (preprocessed : (Vector F 7))
  (_publicValues : (Vector F 160))
  : List (Interaction F) :=
  [
    ⟨.receive, (.byte (ByteOpcode.ofNat 0) preprocessed[2] preprocessed[0] preprocessed[1]), cols.values[0]⟩,
    ⟨.receive, (.byte (ByteOpcode.ofNat 1) preprocessed[3] preprocessed[0] preprocessed[1]), cols.values[1]⟩,
    ⟨.receive, (.byte (ByteOpcode.ofNat 2) preprocessed[4] preprocessed[0] preprocessed[1]), cols.values[2]⟩,
    ⟨.receive, (.byte (ByteOpcode.ofNat 3) 0 preprocessed[0] preprocessed[1]), cols.values[3]⟩,
    ⟨.receive, (.byte (ByteOpcode.ofNat 4) preprocessed[5] preprocessed[0] preprocessed[1]), cols.values[4]⟩,
    ⟨.receive, (.byte (ByteOpcode.ofNat 5) preprocessed[6] preprocessed[0] 0), cols.values[5]⟩,
  ]

end ByteCols

end SP1Clean.Extracted
