import SP1Clean.Math.Word
import SP1Clean.Extracted.ExtractionDSL
import Clean.Utils.Tactics.ProvableStructDeriving
import SP1Clean.Extracted.IsZeroOperation
import SP1Clean.Extracted.LtOperationUnsigned

/-! # AUTO-GENERATED system-table Rust AIR oracle — do not edit by hand.

Generated by `update_extracted.py` from `sp1-constraint-compiler --chip MemoryGlobalInit --format lean`. Contains every `MemoryGlobalInit` main-trace column in upstream index order, the complete per-row `assertZero` list, and the complete interaction list. The flat vector deliberately avoids inventing semantic field names in the extraction layer; audited adapters may name selected indices above this anchor. Reuses the IsZeroOperation, LtOperationUnsigned helper module(s). -/

set_option linter.all false  -- auto-generated: skip linters

namespace SP1Clean.Extracted
open SP1Clean

-- Generated Lean code for chip MemoryGlobalInitChip

structure MemoryGlobalInitCols (F : Type) where
  values : (Vector F 30)
deriving ProvableStruct

namespace MemoryGlobalInitCols

set_option maxRecDepth 100000 in
@[irreducible] def asserts {F : Type} [Field F] [CoeHead F ℕ]
  (cols : (MemoryGlobalInitCols F))
  (_preprocessed : (Vector F 0))
  (_publicValues : (Vector F 160))
  : List F :=
  let E0 : F := cols.values[23] - 1
  let E1 : F := cols.values[23] * E0
  let E2 : F := cols.values[22] * 256
  let E3 : F := cols.values[21] + E2
  let E4 : F := cols.values[19] - E3
  let E10 : F := cols.values[3] + cols.values[4]
  let E11 : F := E10 + cols.values[5]
  let E12 : F := cols.values[27] * cols.values[29]
  let E13 : F := 1 - E12
  let E14 : F := cols.values[23] * E13
  let E15 : F := cols.values[24] - E14
  let E16 : F := cols.values[24] - 1
  let E17 : F := cols.values[24] * E16
  let E18 : F := cols.values[9] - 1
  let E19 : F := cols.values[24] * E18
  let E20 : F := cols.values[23] - cols.values[24]
  let E21 : F := cols.values[6] + cols.values[7]
  let E22 : F := E21 + cols.values[8]
  let E23 : F := E20 * E22
  let E24 : F := E20 * cols.values[17]
  let E25 : F := E20 * cols.values[18]
  let E26 : F := E20 * cols.values[19]
  let E27 : F := E20 * cols.values[20]
  IsZeroOperation.asserts E11 { inverse := cols.values[26], result := cols.values[27] } cols.values[23] ++ IsZeroOperation.asserts cols.values[2] { inverse := cols.values[28], result := cols.values[29] } cols.values[23] ++ LtOperationUnsigned.asserts #v[cols.values[3], cols.values[4], cols.values[5], 0] #v[cols.values[6], cols.values[7], cols.values[8], 0] { u16_compare_operation := { bit := cols.values[9] }, u16_flags := #v[cols.values[10], cols.values[11], cols.values[12], cols.values[13]], not_eq_inv := cols.values[14], comparison_limbs := #v[cols.values[15], cols.values[16]] } cols.values[24] ++ [
    E1,
    E4,
    E15,
    E17,
    E19,
    E23,
    E24,
    E25,
    E26,
    E27,
  ]

set_option maxRecDepth 100000 in
@[irreducible] def interactions {F : Type} [Field F] [CoeHead F ℕ]
  (cols : (MemoryGlobalInitCols F))
  (_preprocessed : (Vector F 0))
  (_publicValues : (Vector F 160))
  : List (Interaction F) :=
  let E5 : F := cols.values[2] + 1
  let E6 : F := cols.values[21] * 65536
  let E7 : F := cols.values[17] + E6
  let E8 : F := cols.values[22] * 65536
  let E9 : F := cols.values[18] + E8
  let E10 : F := cols.values[3] + cols.values[4]
  let E11 : F := E10 + cols.values[5]
  IsZeroOperation.interactions E11 { inverse := cols.values[26], result := cols.values[27] } cols.values[23] ++ IsZeroOperation.interactions cols.values[2] { inverse := cols.values[28], result := cols.values[29] } cols.values[23] ++ LtOperationUnsigned.interactions #v[cols.values[3], cols.values[4], cols.values[5], 0] #v[cols.values[6], cols.values[7], cols.values[8], 0] { u16_compare_operation := { bit := cols.values[9] }, u16_flags := #v[cols.values[10], cols.values[11], cols.values[12], cols.values[13]], not_eq_inv := cols.values[14], comparison_limbs := #v[cols.values[15], cols.values[16]] } cols.values[24] ++ [
    ⟨.send, (.byte 6 cols.values[17] 16 0), cols.values[23]⟩,
    ⟨.send, (.byte 6 cols.values[18] 16 0), cols.values[23]⟩,
    ⟨.send, (.byte 6 cols.values[19] 16 0), cols.values[23]⟩,
    ⟨.send, (.byte 6 cols.values[20] 16 0), cols.values[23]⟩,
    ⟨.send, (.byte 6 cols.values[3] 16 0), cols.values[23]⟩,
    ⟨.send, (.byte 6 cols.values[4] 16 0), cols.values[23]⟩,
    ⟨.send, (.byte 6 cols.values[5] 16 0), cols.values[23]⟩,
    ⟨.send, (.byte 6 cols.values[6] 16 0), cols.values[23]⟩,
    ⟨.send, (.byte 6 cols.values[7] 16 0), cols.values[23]⟩,
    ⟨.send, (.byte 6 cols.values[8] 16 0), cols.values[23]⟩,
    ⟨.send, (.byte 3 0 cols.values[21] cols.values[22]), cols.values[23]⟩,
    ⟨.receive, (.raw .memoryGlobalInitControl [cols.values[2], cols.values[3], cols.values[4], cols.values[5], cols.values[25]]), cols.values[23]⟩,
    ⟨.send, (.raw .memoryGlobalInitControl [E5, cols.values[6], cols.values[7], cols.values[8], cols.values[24]]), cols.values[23]⟩,
    ⟨.send, (.raw .global [0, 0, cols.values[6], cols.values[7], cols.values[8], E7, E9, cols.values[20], 1, 0, 1]), cols.values[23]⟩,
  ]

end MemoryGlobalInitCols

end SP1Clean.Extracted
