import SP1Clean.Math.Word
import SP1Clean.Extracted.ExtractionDSL
import Clean.Utils.Tactics.ProvableStructDeriving

/-! # AUTO-GENERATED system-table Rust AIR oracle — do not edit by hand.

Generated by `update_extracted.py` from `sp1-constraint-compiler --chip MemoryBump --format lean`. Contains every `MemoryBump` main-trace column in upstream index order, the complete per-row `assertZero` list, and the complete interaction list. The flat vector deliberately avoids inventing semantic field names in the extraction layer; audited adapters may name selected indices above this anchor. Reuses no helper modules. -/

set_option linter.all false  -- auto-generated: skip linters

namespace SP1Clean.Extracted
open SP1Clean

-- Generated Lean code for chip MemoryBumpChip

structure MemoryBumpCols (F : Type) where
  values : (Vector F 15)
deriving ProvableStruct

namespace MemoryBumpCols

@[irreducible] def asserts {F : Type} [Field F] [CoeHead F ℕ]
  (cols : (MemoryBumpCols F))
  (_preprocessed : (Vector F 0))
  (_publicValues : (Vector F 160))
  : List F :=
  let E0 : F := cols.values[14] - 1
  let E1 : F := cols.values[14] * E0
  let E2 : F := cols.values[9] * 256
  let E3 : F := cols.values[10] + E2
  let E4 : F := cols.values[11] * 65536
  let E5 : F := cols.values[12] + E4
  let E6 : F := cols.values[14] - 1
  let E7 : F := cols.values[14] * E6
  let E8 : F := cols.values[6] - 1
  let E9 : F := cols.values[6] * E8
  let E10 : F := cols.values[14] * E9
  let E11 : F := E3 - cols.values[4]
  let E12 : F := cols.values[6] * E11
  let E13 : F := cols.values[14] * E12
  let E14 : F := cols.values[6] * cols.values[5]
  let E15 : F := 1 - cols.values[6]
  let E16 : F := E15 * cols.values[4]
  let E17 : F := E14 + E16
  let E18 : F := cols.values[6] * E5
  let E19 : F := 1 - cols.values[6]
  let E20 : F := E19 * E3
  let E21 : F := E18 + E20
  let E22 : F := E21 - E17
  let E23 : F := E22 - 1
  let E24 : F := cols.values[8] * 65536
  let E25 : F := cols.values[7] + E24
  let E26 : F := E23 - E25
  let E27 : F := cols.values[14] * E26
  [
    E1,
    E7,
    E10,
    E13,
    E27,
  ]

@[irreducible] def interactions {F : Type} [Field F] [CoeHead F ℕ]
  (cols : (MemoryBumpCols F))
  (_preprocessed : (Vector F 0))
  (_publicValues : (Vector F 160))
  : List (Interaction F) :=
  let E2 : F := cols.values[9] * 256
  let E3 : F := cols.values[10] + E2
  let E4 : F := cols.values[11] * 65536
  let E5 : F := cols.values[12] + E4
  [
    ⟨.send, (.byte 6 cols.values[12] 16 0), cols.values[14]⟩,
    ⟨.send, (.byte 6 cols.values[9] 16 0), cols.values[14]⟩,
    ⟨.send, (.byte 3 0 cols.values[11] cols.values[10]), cols.values[14]⟩,
    ⟨.send, (.byte 4 1 cols.values[13] 32), cols.values[14]⟩,
    ⟨.send, (.byte 6 cols.values[7] 16 0), cols.values[14]⟩,
    ⟨.send, (.byte 3 0 cols.values[8] 0), cols.values[14]⟩,
    ⟨.send, (.memory cols.values[4] cols.values[5] cols.values[13] 0 0 cols.values[0] cols.values[1] cols.values[2] cols.values[3]), cols.values[14]⟩,
    ⟨.receive, (.memory E3 E5 cols.values[13] 0 0 cols.values[0] cols.values[1] cols.values[2] cols.values[3]), cols.values[14]⟩,
  ]

end MemoryBumpCols

end SP1Clean.Extracted
