import SP1Clean.Math.Word
import SP1Clean.Extracted.ExtractionDSL
import Clean.Utils.Tactics.ProvableStructDeriving

/-! # AUTO-GENERATED system-table Rust AIR oracle — do not edit by hand.

Generated by `update_extracted.py` from `sp1-constraint-compiler --chip Program --format lean`. Contains every `Program` main-trace column in upstream index order, the complete per-row `assertZero` list, and the complete interaction list. The flat vector deliberately avoids inventing semantic field names in the extraction layer; audited adapters may name selected indices above this anchor. Reuses the no helper module(s). -/

set_option linter.all false  -- auto-generated: skip linters

namespace SP1Clean.Extracted
open SP1Clean

-- Generated Lean code for chip ProgramChip

structure ProgramCols (F : Type) where
  values : (Vector F 1)
deriving ProvableStruct

namespace ProgramCols

set_option maxRecDepth 100000 in
@[irreducible] def asserts {F : Type} [Field F] [CoeHead F ℕ]
  (_cols : (ProgramCols F))
  (_preprocessed : (Vector F 16))
  (_publicValues : (Vector F 160))
  : List F :=
  [
  ]

set_option maxRecDepth 100000 in
@[irreducible] def interactions {F : Type} [Field F] [CoeHead F ℕ]
  (cols : (ProgramCols F))
  (preprocessed : (Vector F 16))
  (_publicValues : (Vector F 160))
  : List (Interaction F) :=
  [
    ⟨.receive, (.program preprocessed[0] preprocessed[1] preprocessed[2] (Opcode.ofNat preprocessed[3]) preprocessed[4] preprocessed[5] preprocessed[6] preprocessed[7] preprocessed[8] preprocessed[9] preprocessed[10] preprocessed[11] preprocessed[12] preprocessed[13] preprocessed[14] preprocessed[15]), cols.values[0]⟩,
  ]

end ProgramCols

end SP1Clean.Extracted
