import SP1Clean.Math.Word
import SP1Clean.Extracted.ExtractionDSL
import Clean.Utils.Tactics.ProvableStructDeriving

/-! # AUTO-GENERATED system-table Rust AIR oracle — do not edit by hand.

Generated by `update_extracted.py` from `sp1-constraint-compiler --chip StateBump --format lean`. Contains every `StateBump` main-trace column in upstream index order, the complete per-row `assertZero` list, and the complete interaction list. The flat vector deliberately avoids inventing semantic field names in the extraction layer; audited adapters may name selected indices above this anchor. Reuses the no helper module(s). -/

set_option linter.all false  -- auto-generated: skip linters

namespace SP1Clean.Extracted
open SP1Clean

-- Generated Lean code for chip StateBumpChip

structure StateBumpCols (F : Type) where
  values : (Vector F 14)
deriving ProvableStruct

namespace StateBumpCols

set_option maxRecDepth 100000 in
@[irreducible] def asserts {F : Type} [Field F] [CoeHead F ℕ]
  (cols : (StateBumpCols F))
  (_preprocessed : (Vector F 0))
  (_publicValues : (Vector F 160))
  : List F :=
  let E0 : F := cols.values[13] - 1
  let E1 : F := cols.values[13] * E0
  let E8 : F := cols.values[12] - 1
  let E9 : F := cols.values[12] * E8
  let E10 : F := cols.values[0] * 256
  let E11 : F := cols.values[1] + E10
  let E12 : F := cols.values[4] + cols.values[12]
  let E13 : F := E11 - E12
  let E14 : F := cols.values[13] * E13
  let E15 : F := cols.values[2] * 65536
  let E16 : F := cols.values[3] + E15
  let E17 : F := cols.values[12] * 16777216
  let E18 : F := E16 + E17
  let E19 : F := E18 - cols.values[5]
  let E20 : F := cols.values[13] * E19
  let E21 : F := 0 + cols.values[9]
  let E22 : F := E21 - cols.values[6]
  let E23 : F := E22 * ((65536 : F)⁻¹)
  let E24 : F := E23 - 1
  let E25 : F := E23 * E24
  let E26 : F := E23 + cols.values[10]
  let E27 : F := E26 - cols.values[7]
  let E28 : F := E27 * ((65536 : F)⁻¹)
  let E29 : F := E28 - 1
  let E30 : F := E28 * E29
  let E31 : F := E28 + cols.values[11]
  let E32 : F := E31 - cols.values[8]
  let E33 : F := E32 * ((65536 : F)⁻¹)
  let E34 : F := E33 - 1
  let E35 : F := E33 * E34
  [
    E1,
    E9,
    E14,
    E20,
    E25,
    E30,
    E35,
    E33,
  ]

set_option maxRecDepth 100000 in
@[irreducible] def interactions {F : Type} [Field F] [CoeHead F ℕ]
  (cols : (StateBumpCols F))
  (_preprocessed : (Vector F 0))
  (_publicValues : (Vector F 160))
  : List (Interaction F) :=
  let E2 : F := cols.values[0] * 256
  let E3 : F := cols.values[1] + E2
  let E4 : F := cols.values[2] * 65536
  let E5 : F := cols.values[3] + E4
  let E6 : F := cols.values[3] - 1
  let E7 : F := E6 * ((8 : F)⁻¹)
  [
    ⟨.receive, (.state cols.values[4] cols.values[5] cols.values[9] cols.values[10] cols.values[11]), cols.values[13]⟩,
    ⟨.send, (.state E3 E5 cols.values[6] cols.values[7] cols.values[8]), cols.values[13]⟩,
    ⟨.send, (.byte 6 E7 13 0), cols.values[13]⟩,
    ⟨.send, (.byte 6 cols.values[0] 16 0), cols.values[13]⟩,
    ⟨.send, (.byte 3 0 cols.values[2] cols.values[1]), cols.values[13]⟩,
    ⟨.send, (.byte 6 cols.values[6] 16 0), cols.values[13]⟩,
    ⟨.send, (.byte 6 cols.values[7] 16 0), cols.values[13]⟩,
    ⟨.send, (.byte 6 cols.values[8] 16 0), cols.values[13]⟩,
  ]

end StateBumpCols

end SP1Clean.Extracted
