name = "sp1-lean"
version = "6.2.2"
keywords = ["math"]
defaultTargets = ["SP1Operations", "SP1Chips", "SP1Clean"]

moreLeanArgs = ["--tstack=400000"]
preferReleaseBuild = true

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
linter.unusedSimpArgs = false
linter.flexible = false
synthInstance.maxHeartbeats = 1000000
weak.linter.mathlibStandardSet = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0"

[[require]]
name = "LeanRV64D"
git = "https://github.com/succinctlabs/sail-riscv-lean"
rev = "v6.2.2"

[[require]]
name = "RISCV"
git = "https://github.com/succinctlabs/riscv-lean"
rev = "v6.2.2"

[[require]]
name = "Clean"
git = "https://github.com/succinctlabs/clean"
rev = "v6.2.2"

[[lean_lib]]
name = "SP1Foundations"

[[lean_lib]]
name = "SP1Operations"

[[lean_lib]]
name = "SP1Chips"

[[lean_lib]]
name = "SP1Clean"
