name = "sp1-lean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["SP1Operations", "SP1Chips"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "SP1Foundations"

[[lean_lib]]
name = "SP1Operations"

[[lean_lib]]
name = "SP1Chips"