name = "sp1-lean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["SP1Operations", "SP1Chips"]

moreLeanArgs = ["--tstack=400000"]
preferReleaseBuild = true

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
linter.unusedSimpArgs = false
synthInstance.maxHeartbeats = 1000000
weak.linter.mathlibStandardSet = true
# autoImplicit = false -- Might be good to consider this, given the amount of coercions we use

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0"

[[require]]
name = "Lean_RV64D"
git = "https://github.com/opencompl/sail-riscv-lean"
rev = "main"

[[lean_lib]]
name = "SP1Foundations"

[[lean_lib]]
name = "SP1Operations"

[[lean_lib]]
name = "SP1Chips"
