import SP1Clean.Math.Word
import SP1Clean.Extracted.ExtractionDSL
import Clean.Utils.Tactics.ProvableStructDeriving
import SP1Clean.Extracted.CPUState
import SP1Clean.Extracted.RTypeReader
import SP1Clean.Extracted.JTypeReader

/-! # AUTO-GENERATED whole-chip Rust AIR oracle — do not edit by hand.

Generated by `update_extracted.py` from `sp1-constraint-compiler --chip Jal --format lean`.
Contains the complete Rust `Jal` row shape, `assertZero` list, and interaction list,
reusing canonical generated reader structs and functions where available (no shared helpers).
The compiler's chip-private helper definitions (AddOperation) are embedded in this namespace
rather than imported as operation-level verification artifacts. Regenerate with
`SP1_DIR=… python3 update_extracted.py`. -/

set_option linter.all false  -- auto-generated: skip linters

namespace SP1Clean.Extracted.JalOracle
open SP1Clean

-- Generated Lean code for chip JalChip

structure AddOperation (F : Type) where
  value : (Word F)
deriving ProvableStruct

structure JalColumns (F : Type) where
  state : (CPUState F)
  adapter : (JTypeReader F)
  add_operation : (AddOperation F)
  op_a_operation : (AddOperation F)
  is_real : F
deriving ProvableStruct

namespace AddOperation

@[irreducible] def asserts {F : Type} [Field F] [CoeHead F ℕ]
  (a : (Word F))
  (b : (Word F))
  (cols : (AddOperation F))
  (is_real : F)
  : List F :=
  let E0 : F := is_real - 1
  let E1 : F := is_real * E0
  let E2 : F := a[0] + b[0]
  let E3 : F := E2 - cols.value[0]
  let E4 : F := E3 + 0
  let E5 : F := E4 * ((65536 : F)⁻¹)
  let E6 : F := E5 - 1
  let E7 : F := E5 * E6
  let E8 : F := is_real * E7
  let E9 : F := a[1] + b[1]
  let E10 : F := E9 - cols.value[1]
  let E11 : F := E10 + E5
  let E12 : F := E11 * ((65536 : F)⁻¹)
  let E13 : F := E12 - 1
  let E14 : F := E12 * E13
  let E15 : F := is_real * E14
  let E16 : F := a[2] + b[2]
  let E17 : F := E16 - cols.value[2]
  let E18 : F := E17 + E12
  let E19 : F := E18 * ((65536 : F)⁻¹)
  let E20 : F := E19 - 1
  let E21 : F := E19 * E20
  let E22 : F := is_real * E21
  let E23 : F := a[3] + b[3]
  let E24 : F := E23 - cols.value[3]
  let E25 : F := E24 + E19
  let E26 : F := E25 * ((65536 : F)⁻¹)
  let E27 : F := E26 - 1
  let E28 : F := E26 * E27
  let E29 : F := is_real * E28
  [
    E1,
    E8,
    E15,
    E22,
    E29,
  ]

@[irreducible] def interactions {F : Type} [Field F] [CoeHead F ℕ]
  (_a : (Word F))
  (_b : (Word F))
  (cols : (AddOperation F))
  (is_real : F)
  : List (Interaction F) :=
  [
    ⟨.send, (.byte 6 cols.value[0] 16 0), is_real⟩,
    ⟨.send, (.byte 6 cols.value[1] 16 0), is_real⟩,
    ⟨.send, (.byte 6 cols.value[2] 16 0), is_real⟩,
    ⟨.send, (.byte 6 cols.value[3] 16 0), is_real⟩,
  ]

end AddOperation

namespace JalColumns

@[irreducible] def asserts {F : Type} [Field F] [CoeHead F ℕ]
  (cols : (JalColumns F))
  : List F :=
  let E0 : F := cols.is_real - 1
  let E1 : F := cols.is_real * E0
  let E5 : F := cols.is_real - 1
  let E6 : F := cols.is_real * E5
  let E10 : F := cols.is_real - 1
  let E11 : F := E10 * cols.adapter.op_a_0
  let E12 : F := cols.is_real - cols.adapter.op_a_0
  let E13 : F := cols.adapter.op_a_0 * cols.op_a_operation.value[0]
  let E14 : F := cols.adapter.op_a_0 * cols.op_a_operation.value[1]
  let E15 : F := cols.adapter.op_a_0 * cols.op_a_operation.value[2]
  let E18 : F := cols.is_real - 1
  let E19 : F := cols.is_real * E18
  let E20 : F := cols.op_a_operation.value[0] - 0
  let E21 : F := cols.adapter.op_a_0 * E20
  let E22 : F := cols.op_a_operation.value[1] - 0
  let E23 : F := cols.adapter.op_a_0 * E22
  let E24 : F := cols.op_a_operation.value[2] - 0
  let E25 : F := cols.adapter.op_a_0 * E24
  let E26 : F := cols.op_a_operation.value[3] - 0
  let E27 : F := cols.adapter.op_a_0 * E26
  let E29 : F := cols.is_real - 1
  let E30 : F := cols.is_real * E29
  AddOperation.asserts #v[cols.state.pc[0], cols.state.pc[1], cols.state.pc[2], 0] #v[cols.adapter.op_b_imm[0], cols.adapter.op_b_imm[1], cols.adapter.op_b_imm[2], cols.adapter.op_b_imm[3]] { value := #v[cols.add_operation.value[0], cols.add_operation.value[1], cols.add_operation.value[2], cols.add_operation.value[3]] } cols.is_real ++ AddOperation.asserts #v[cols.state.pc[0], cols.state.pc[1], cols.state.pc[2], 0] #v[4, 0, 0, 0] { value := #v[cols.op_a_operation.value[0], cols.op_a_operation.value[1], cols.op_a_operation.value[2], cols.op_a_operation.value[3]] } E12 ++ [
    E1,
    cols.add_operation.value[3],
    E6,
    E11,
    cols.op_a_operation.value[3],
    E13,
    E14,
    E15,
    E19,
    E21,
    E23,
    E25,
    E27,
    E30,
  ]

@[irreducible] def interactions {F : Type} [Field F] [CoeHead F ℕ]
  (cols : (JalColumns F))
  : List (Interaction F) :=
  let E2 : F := cols.add_operation.value[0] * ((4 : F)⁻¹)
  let E3 : F := cols.state.clk_16_24 * 65536
  let E4 : F := cols.state.clk_0_16 + E3
  let E7 : F := E4 + 8
  let E8 : F := cols.state.clk_0_16 - 1
  let E9 : F := E8 * ((8 : F)⁻¹)
  let E12 : F := cols.is_real - cols.adapter.op_a_0
  let E16 : F := cols.state.clk_16_24 * 65536
  let E17 : F := cols.state.clk_0_16 + E16
  let E28 : F := E17 + 4
  let E31 : F := E28 - cols.adapter.op_a_memory.access_timestamp.prev_low
  let E32 : F := E31 - 1
  let E33 : F := E32 - cols.adapter.op_a_memory.access_timestamp.diff_low_limb
  let E34 : F := E33 * ((65536 : F)⁻¹)
  AddOperation.interactions #v[cols.state.pc[0], cols.state.pc[1], cols.state.pc[2], 0] #v[cols.adapter.op_b_imm[0], cols.adapter.op_b_imm[1], cols.adapter.op_b_imm[2], cols.adapter.op_b_imm[3]] { value := #v[cols.add_operation.value[0], cols.add_operation.value[1], cols.add_operation.value[2], cols.add_operation.value[3]] } cols.is_real ++ AddOperation.interactions #v[cols.state.pc[0], cols.state.pc[1], cols.state.pc[2], 0] #v[4, 0, 0, 0] { value := #v[cols.op_a_operation.value[0], cols.op_a_operation.value[1], cols.op_a_operation.value[2], cols.op_a_operation.value[3]] } E12 ++ [
    ⟨.send, (.byte 6 E2 14 0), cols.is_real⟩,
    ⟨.receive, (.state cols.state.clk_high E4 cols.state.pc[0] cols.state.pc[1] cols.state.pc[2]), cols.is_real⟩,
    ⟨.send, (.state cols.state.clk_high E7 cols.add_operation.value[0] cols.add_operation.value[1] cols.add_operation.value[2]), cols.is_real⟩,
    ⟨.send, (.byte 6 E9 13 0), cols.is_real⟩,
    ⟨.send, (.byte 3 0 cols.state.clk_16_24 0), cols.is_real⟩,
    ⟨.send, (.program cols.state.pc[0] cols.state.pc[1] cols.state.pc[2] (Opcode.ofNat 46) cols.adapter.op_a cols.adapter.op_b_imm[0] cols.adapter.op_b_imm[1] cols.adapter.op_b_imm[2] cols.adapter.op_b_imm[3] cols.adapter.op_c_imm[0] cols.adapter.op_c_imm[1] cols.adapter.op_c_imm[2] cols.adapter.op_c_imm[3] cols.adapter.op_a_0 1 1), cols.is_real⟩,
    ⟨.send, (.byte 6 cols.adapter.op_a_memory.access_timestamp.diff_low_limb 16 0), cols.is_real⟩,
    ⟨.send, (.byte 3 0 E34 0), cols.is_real⟩,
    ⟨.send, (.memory cols.state.clk_high cols.adapter.op_a_memory.access_timestamp.prev_low cols.adapter.op_a 0 0 cols.adapter.op_a_memory.prev_value[0] cols.adapter.op_a_memory.prev_value[1] cols.adapter.op_a_memory.prev_value[2] cols.adapter.op_a_memory.prev_value[3]), cols.is_real⟩,
    ⟨.receive, (.memory cols.state.clk_high E28 cols.adapter.op_a 0 0 cols.op_a_operation.value[0] cols.op_a_operation.value[1] cols.op_a_operation.value[2] cols.op_a_operation.value[3]), cols.is_real⟩,
  ]

end JalColumns

end SP1Clean.Extracted.JalOracle
