import SP1Clean.Math.Word
import SP1Clean.Extracted.ExtractionDSL
import Clean.Utils.Tactics.ProvableStructDeriving
import SP1Clean.Extracted.CPUState
import SP1Clean.Extracted.MemoryAccess
import SP1Clean.Extracted.ITypeReaderImmutable

/-! # AUTO-GENERATED whole-chip Rust AIR oracle — do not edit by hand.

Generated by `update_extracted.py` from `sp1-constraint-compiler --chip LoadX0 --format lean`.
Contains the complete Rust `LoadX0` row shape, `assertZero` list, and interaction list,
reusing the canonical generated struct/reader modules imported above (CPUState, MemoryAccess, ITypeReaderImmutable).
The compiler's chip-private helper definitions (AddrAddOperation, AddressOperation) are embedded in this namespace
rather than imported as operation-level verification artifacts. Regenerate with
`SP1_DIR=… python3 update_extracted.py`. -/

set_option linter.all false  -- auto-generated: skip linters

namespace SP1Clean.Extracted.LoadX0Oracle
open SP1Clean

-- Generated Lean code for chip LoadX0Chip

structure AddrAddOperation (F : Type) where
  value : (Vector F 3)
deriving ProvableStruct

structure AddressOperation (F : Type) where
  addr_operation : (AddrAddOperation F)
  top_two_limb_inv : F
deriving ProvableStruct

structure LoadX0Columns (F : Type) where
  state : (CPUState F)
  adapter : (ITypeReader F)
  address_operation : (AddressOperation F)
  memory_access : (MemoryAccessCols F)
  offset_bit : (Vector F 3)
  is_lb : F
  is_lbu : F
  is_lh : F
  is_lhu : F
  is_lw : F
  is_lwu : F
  is_ld : F
deriving ProvableStruct

namespace AddrAddOperation

@[irreducible] def asserts {F : Type} [Field F] [CoeHead F ℕ]
  (a : (Word F))
  (b : (Word F))
  (cols : (AddrAddOperation F))
  (is_real : F)
  : List F :=
  let E0 : F := is_real - 1
  let E1 : F := is_real * E0
  let E2 : F := a[0] + b[0]
  let E3 : F := E2 - cols.value[0]
  let E4 : F := E3 + 0
  let E5 : F := E4 * ((65536 : F)⁻¹)
  let E6 : F := E5 - 1
  let E7 : F := E5 * E6
  let E8 : F := is_real * E7
  let E9 : F := a[1] + b[1]
  let E10 : F := E9 - cols.value[1]
  let E11 : F := E10 + E5
  let E12 : F := E11 * ((65536 : F)⁻¹)
  let E13 : F := E12 - 1
  let E14 : F := E12 * E13
  let E15 : F := is_real * E14
  let E16 : F := a[2] + b[2]
  let E17 : F := E16 - cols.value[2]
  let E18 : F := E17 + E12
  let E19 : F := E18 * ((65536 : F)⁻¹)
  let E20 : F := E19 - 1
  let E21 : F := E19 * E20
  let E22 : F := is_real * E21
  let E23 : F := a[3] + b[3]
  let E24 : F := E23 - 0
  let E25 : F := E24 + E19
  let E26 : F := E25 * ((65536 : F)⁻¹)
  let E27 : F := E26 - 1
  let E28 : F := E26 * E27
  let E29 : F := is_real * E28
  [
    E1,
    E8,
    E15,
    E22,
    E29,
  ]

@[irreducible] def interactions {F : Type} [Field F] [CoeHead F ℕ]
  (_a : (Word F))
  (_b : (Word F))
  (cols : (AddrAddOperation F))
  (is_real : F)
  : List (Interaction F) :=
  [
    ⟨.send, (.byte 6 cols.value[0] 16 0), is_real⟩,
    ⟨.send, (.byte 6 cols.value[1] 16 0), is_real⟩,
    ⟨.send, (.byte 6 cols.value[2] 16 0), is_real⟩,
  ]

end AddrAddOperation

namespace AddressOperation

@[irreducible] def asserts {F : Type} [Field F] [CoeHead F ℕ]
  (b : (Word F))
  (cc : (Word F))
  (offset_bit0 : F)
  (offset_bit1 : F)
  (offset_bit2 : F)
  (is_real : F)
  (cols : (AddressOperation F))
  : List F :=
  let E0 : F := is_real - 1
  let E1 : F := is_real * E0
  let E2 : F := offset_bit0 - 1
  let E3 : F := offset_bit0 * E2
  let E4 : F := offset_bit1 - 1
  let E5 : F := offset_bit1 * E4
  let E6 : F := offset_bit2 - 1
  let E7 : F := offset_bit2 * E6
  let E8 : F := cols.addr_operation.value[1] + cols.addr_operation.value[2]
  let E9 : F := cols.top_two_limb_inv * E8
  let E10 : F := E9 - is_real
  AddrAddOperation.asserts #v[b[0], b[1], b[2], b[3]] #v[cc[0], cc[1], cc[2], cc[3]] { value := #v[cols.addr_operation.value[0], cols.addr_operation.value[1], cols.addr_operation.value[2]] } is_real ++ [
    E1,
    E3,
    E5,
    E7,
    E10,
  ]

@[irreducible] def interactions {F : Type} [Field F] [CoeHead F ℕ]
  (b : (Word F))
  (cc : (Word F))
  (offset_bit0 : F)
  (offset_bit1 : F)
  (offset_bit2 : F)
  (is_real : F)
  (cols : (AddressOperation F))
  : List (Interaction F) :=
  let E11 : F := 4 * offset_bit2
  let E12 : F := cols.addr_operation.value[0] - E11
  let E13 : F := 2 * offset_bit1
  let E14 : F := E12 - E13
  let E15 : F := E14 - offset_bit0
  let E16 : F := E15 * ((8 : F)⁻¹)
  AddrAddOperation.interactions #v[b[0], b[1], b[2], b[3]] #v[cc[0], cc[1], cc[2], cc[3]] { value := #v[cols.addr_operation.value[0], cols.addr_operation.value[1], cols.addr_operation.value[2]] } is_real ++ [
    ⟨.send, (.byte 6 E16 13 0), is_real⟩,
  ]

@[irreducible] def value {F : Type} [Field F] [CoeHead F ℕ]
  (_b : (Word F))
  (_cc : (Word F))
  (offset_bit0 : F)
  (offset_bit1 : F)
  (offset_bit2 : F)
  (_is_real : F)
  (cols : (AddressOperation F))
  : (Vector F 3) :=
  let E17 : F := 4 * offset_bit2
  let E18 : F := cols.addr_operation.value[0] - E17
  let E19 : F := 2 * offset_bit1
  let E20 : F := E18 - E19
  let E21 : F := E20 - offset_bit0
  #v[E21, cols.addr_operation.value[1], cols.addr_operation.value[2]]

end AddressOperation

namespace LoadX0Columns

@[irreducible] def asserts {F : Type} [Field F] [CoeHead F ℕ]
  (cols : (LoadX0Columns F))
  : List F :=
  let E0 : F := cols.state.clk_16_24 * 65536
  let E1 : F := cols.state.clk_0_16 + E0
  let E2 : F := 29 * cols.is_lb
  let E3 : F := 32 * cols.is_lbu
  let E4 : F := E2 + E3
  let E5 : F := 30 * cols.is_lh
  let E6 : F := E4 + E5
  let E7 : F := 33 * cols.is_lhu
  let E8 : F := E6 + E7
  let E9 : F := 31 * cols.is_lw
  let E10 : F := E8 + E9
  let E11 : F := 34 * cols.is_lwu
  let E12 : F := E10 + E11
  let E13 : F := 35 * cols.is_ld
  let E14 : F := E12 + E13
  let E67 : F := cols.is_lb + cols.is_lbu
  let E68 : F := E67 + cols.is_lh
  let E69 : F := E68 + cols.is_lhu
  let E70 : F := E69 + cols.is_lw
  let E71 : F := E70 + cols.is_lwu
  let E72 : F := E71 + cols.is_ld
  let E73 : F := cols.is_lb - 1
  let E74 : F := cols.is_lb * E73
  let E75 : F := cols.is_lbu - 1
  let E76 : F := cols.is_lbu * E75
  let E77 : F := cols.is_lh - 1
  let E78 : F := cols.is_lh * E77
  let E79 : F := cols.is_lhu - 1
  let E80 : F := cols.is_lhu * E79
  let E81 : F := cols.is_lw - 1
  let E82 : F := cols.is_lw * E81
  let E83 : F := cols.is_lwu - 1
  let E84 : F := cols.is_lwu * E83
  let E85 : F := cols.is_ld - 1
  let E86 : F := cols.is_ld * E85
  let E87 : F := E72 - 1
  let E88 : F := E72 * E87
  let E92 : F := cols.is_ld * cols.offset_bit[2]
  let E93 : F := cols.is_lw + cols.is_lwu
  let E94 : F := E93 + cols.is_ld
  let E95 : F := E94 * cols.offset_bit[1]
  let E96 : F := cols.is_lh + cols.is_lhu
  let E97 : F := E96 + cols.is_lw
  let E98 : F := E97 + cols.is_lwu
  let E99 : F := E98 + cols.is_ld
  let E100 : F := E99 * cols.offset_bit[0]
  let E101 : F := E1 + 1
  let E102 : F := E72 - 1
  let E103 : F := E72 * E102
  let E104 : F := cols.memory_access.access_timestamp.compare_low - 1
  let E105 : F := cols.memory_access.access_timestamp.compare_low * E104
  let E106 : F := E72 * E105
  let E107 : F := cols.state.clk_high - cols.memory_access.access_timestamp.prev_high
  let E108 : F := cols.memory_access.access_timestamp.compare_low * E107
  let E109 : F := E72 * E108
  let E110 : F := cols.memory_access.access_timestamp.compare_low * cols.memory_access.access_timestamp.prev_low
  let E111 : F := 1 - cols.memory_access.access_timestamp.compare_low
  let E112 : F := E111 * cols.memory_access.access_timestamp.prev_high
  let E113 : F := E110 + E112
  let E114 : F := cols.memory_access.access_timestamp.compare_low * E101
  let E115 : F := 1 - cols.memory_access.access_timestamp.compare_low
  let E116 : F := E115 * cols.state.clk_high
  let E117 : F := E114 + E116
  let E118 : F := E117 - E113
  let E119 : F := E118 - 1
  let E120 : F := cols.memory_access.access_timestamp.diff_high_limb * 65536
  let E121 : F := cols.memory_access.access_timestamp.diff_low_limb + E120
  let E122 : F := E119 - E121
  let E123 : F := E72 * E122
  let E124 : F := cols.adapter.op_a_0 - 1
  let E125 : F := E72 * E124
  let E126 : F := E72 - 1
  let E127 : F := E126 * cols.adapter.op_a_0
  let E128 : F := cols.state.pc[0] + 4
  AddressOperation.asserts #v[cols.adapter.op_b_memory.prev_value[0], cols.adapter.op_b_memory.prev_value[1], cols.adapter.op_b_memory.prev_value[2], cols.adapter.op_b_memory.prev_value[3]] #v[cols.adapter.op_c_imm[0], cols.adapter.op_c_imm[1], cols.adapter.op_c_imm[2], cols.adapter.op_c_imm[3]] cols.offset_bit[0] cols.offset_bit[1] cols.offset_bit[2] E72 { addr_operation := { value := #v[cols.address_operation.addr_operation.value[0], cols.address_operation.addr_operation.value[1], cols.address_operation.addr_operation.value[2]] }, top_two_limb_inv := cols.address_operation.top_two_limb_inv } ++ SP1Clean.Extracted.CPUState.asserts { clk_high := cols.state.clk_high, clk_16_24 := cols.state.clk_16_24, clk_0_16 := cols.state.clk_0_16, pc := #v[cols.state.pc[0], cols.state.pc[1], cols.state.pc[2]] } #v[E128, cols.state.pc[1], cols.state.pc[2]] 8 E72 ++ SP1Clean.Extracted.ITypeReaderImmutable.asserts cols.state.clk_high E1 #v[cols.state.pc[0], cols.state.pc[1], cols.state.pc[2]] E14 { op_a := cols.adapter.op_a, op_a_memory := { prev_value := #v[cols.adapter.op_a_memory.prev_value[0], cols.adapter.op_a_memory.prev_value[1], cols.adapter.op_a_memory.prev_value[2], cols.adapter.op_a_memory.prev_value[3]], access_timestamp := { prev_low := cols.adapter.op_a_memory.access_timestamp.prev_low, diff_low_limb := cols.adapter.op_a_memory.access_timestamp.diff_low_limb } }, op_a_0 := cols.adapter.op_a_0, op_b := cols.adapter.op_b, op_b_memory := { prev_value := #v[cols.adapter.op_b_memory.prev_value[0], cols.adapter.op_b_memory.prev_value[1], cols.adapter.op_b_memory.prev_value[2], cols.adapter.op_b_memory.prev_value[3]], access_timestamp := { prev_low := cols.adapter.op_b_memory.access_timestamp.prev_low, diff_low_limb := cols.adapter.op_b_memory.access_timestamp.diff_low_limb } }, op_c_imm := #v[cols.adapter.op_c_imm[0], cols.adapter.op_c_imm[1], cols.adapter.op_c_imm[2], cols.adapter.op_c_imm[3]] } E72 E72 ++ [
    E74,
    E76,
    E78,
    E80,
    E82,
    E84,
    E86,
    E88,
    E92,
    E95,
    E100,
    E103,
    E106,
    E109,
    E123,
    E125,
    E127,
  ]

@[irreducible] def interactions {F : Type} [Field F] [CoeHead F ℕ]
  (cols : (LoadX0Columns F))
  : List (Interaction F) :=
  let E0 : F := cols.state.clk_16_24 * 65536
  let E1 : F := cols.state.clk_0_16 + E0
  let E2 : F := 29 * cols.is_lb
  let E3 : F := 32 * cols.is_lbu
  let E4 : F := E2 + E3
  let E5 : F := 30 * cols.is_lh
  let E6 : F := E4 + E5
  let E7 : F := 33 * cols.is_lhu
  let E8 : F := E6 + E7
  let E9 : F := 31 * cols.is_lw
  let E10 : F := E8 + E9
  let E11 : F := 34 * cols.is_lwu
  let E12 : F := E10 + E11
  let E13 : F := 35 * cols.is_ld
  let E14 : F := E12 + E13
  let E67 : F := cols.is_lb + cols.is_lbu
  let E68 : F := E67 + cols.is_lh
  let E69 : F := E68 + cols.is_lhu
  let E70 : F := E69 + cols.is_lw
  let E71 : F := E70 + cols.is_lwu
  let E72 : F := E71 + cols.is_ld
  let __call0_v := AddressOperation.value #v[cols.adapter.op_b_memory.prev_value[0], cols.adapter.op_b_memory.prev_value[1], cols.adapter.op_b_memory.prev_value[2], cols.adapter.op_b_memory.prev_value[3]] #v[cols.adapter.op_c_imm[0], cols.adapter.op_c_imm[1], cols.adapter.op_c_imm[2], cols.adapter.op_c_imm[3]] cols.offset_bit[0] cols.offset_bit[1] cols.offset_bit[2] E72 { addr_operation := { value := #v[cols.address_operation.addr_operation.value[0], cols.address_operation.addr_operation.value[1], cols.address_operation.addr_operation.value[2]] }, top_two_limb_inv := cols.address_operation.top_two_limb_inv }
  let E89 := __call0_v[0]
  let E90 := __call0_v[1]
  let E91 := __call0_v[2]
  let E101 : F := E1 + 1
  let E128 : F := cols.state.pc[0] + 4
  AddressOperation.interactions #v[cols.adapter.op_b_memory.prev_value[0], cols.adapter.op_b_memory.prev_value[1], cols.adapter.op_b_memory.prev_value[2], cols.adapter.op_b_memory.prev_value[3]] #v[cols.adapter.op_c_imm[0], cols.adapter.op_c_imm[1], cols.adapter.op_c_imm[2], cols.adapter.op_c_imm[3]] cols.offset_bit[0] cols.offset_bit[1] cols.offset_bit[2] E72 { addr_operation := { value := #v[cols.address_operation.addr_operation.value[0], cols.address_operation.addr_operation.value[1], cols.address_operation.addr_operation.value[2]] }, top_two_limb_inv := cols.address_operation.top_two_limb_inv } ++ SP1Clean.Extracted.CPUState.interactions { clk_high := cols.state.clk_high, clk_16_24 := cols.state.clk_16_24, clk_0_16 := cols.state.clk_0_16, pc := #v[cols.state.pc[0], cols.state.pc[1], cols.state.pc[2]] } #v[E128, cols.state.pc[1], cols.state.pc[2]] 8 E72 ++ SP1Clean.Extracted.ITypeReaderImmutable.interactions cols.state.clk_high E1 #v[cols.state.pc[0], cols.state.pc[1], cols.state.pc[2]] E14 { op_a := cols.adapter.op_a, op_a_memory := { prev_value := #v[cols.adapter.op_a_memory.prev_value[0], cols.adapter.op_a_memory.prev_value[1], cols.adapter.op_a_memory.prev_value[2], cols.adapter.op_a_memory.prev_value[3]], access_timestamp := { prev_low := cols.adapter.op_a_memory.access_timestamp.prev_low, diff_low_limb := cols.adapter.op_a_memory.access_timestamp.diff_low_limb } }, op_a_0 := cols.adapter.op_a_0, op_b := cols.adapter.op_b, op_b_memory := { prev_value := #v[cols.adapter.op_b_memory.prev_value[0], cols.adapter.op_b_memory.prev_value[1], cols.adapter.op_b_memory.prev_value[2], cols.adapter.op_b_memory.prev_value[3]], access_timestamp := { prev_low := cols.adapter.op_b_memory.access_timestamp.prev_low, diff_low_limb := cols.adapter.op_b_memory.access_timestamp.diff_low_limb } }, op_c_imm := #v[cols.adapter.op_c_imm[0], cols.adapter.op_c_imm[1], cols.adapter.op_c_imm[2], cols.adapter.op_c_imm[3]] } E72 E72 ++ [
    ⟨.send, (.byte 6 cols.memory_access.access_timestamp.diff_low_limb 16 0), E72⟩,
    ⟨.send, (.byte 3 0 cols.memory_access.access_timestamp.diff_high_limb 0), E72⟩,
    ⟨.send, (.memory cols.memory_access.access_timestamp.prev_high cols.memory_access.access_timestamp.prev_low E89 E90 E91 cols.memory_access.prev_value[0] cols.memory_access.prev_value[1] cols.memory_access.prev_value[2] cols.memory_access.prev_value[3]), E72⟩,
    ⟨.receive, (.memory cols.state.clk_high E101 E89 E90 E91 cols.memory_access.prev_value[0] cols.memory_access.prev_value[1] cols.memory_access.prev_value[2] cols.memory_access.prev_value[3]), E72⟩,
  ]

end LoadX0Columns

end SP1Clean.Extracted.LoadX0Oracle
