import SP1Clean.Math.Word
import Mathlib.Tactic.NormNum.Prime

/-! # Shared scaffolding for the whole-trace conformance layer (`TraceGenTests/`).

`TraceGenTests/` is the **full-trace** chip testing layer: for each covered chip, the whole trace
matrix is *derived from the chip's own circuit* (`TraceGenerator.lean` — witness columns from
`main`'s witness closures, row layout from `main`'s output struct, zero padding) and checked by
`native_decide` against the matrix dumped from SP1's **real** `MachineAir::generate_trace`
(`<Chip>ChipTraceVectors.lean`, regenerated by `update_extracted.py`). The only hand-written
remainder is the event → input-column extraction (`EventPopulate.lean`).

This layer is self-contained — it does not depend on `WitnessTests/` (the older, per-operation
`populate`-conformance bridge, kept as a temporary operation-level tie). The chips are
field-generic over `ZMod p`; conformance is checked at SP1's **concrete field** (KoalaBear), where
SP1's prover actually runs, so this file discharges the chips' `Fact` assumptions once at that
prime. As in `WitnessTests/`, the anchors are *conformance* ties on a fixed dumped battery, not
all-inputs proofs: they prove their matrix equality by `native_decide` (adding generated
`._native.native_decide.ax_*` compiler-trust constants, deliberately confined to the anchor
files), and corrupting any dumped cell
fails the build. The generic generators stay axiom-clean. -/

namespace SP1Clean.TraceGenTests

open SP1Clean

/-- SP1's field is KoalaBear, the prime `2^31 - 2^24 + 1`. SP1's prover runs here, so trace
conformance is checked at this concrete field. -/
abbrev SP1Prime : ℕ := 2130706433

instance instFactSP1Prime : Fact (Nat.Prime SP1Prime) := ⟨by native_decide⟩

/-- The chips' standard field-size assumption, discharged at the concrete prime (the trace anchors
instantiate whole chip `main`s, which carry `Fact (2 ^ 17 < p)`). -/
instance instFact2pow17SP1Prime : Fact (2 ^ 17 < SP1Prime) := ⟨by norm_num [SP1Prime]⟩

/-- `MulOperation.populate` / `MulChip.main` need `2 ^ 24 < p`; discharged at KoalaBear
(`2^24 = 16777216 < SP1Prime`). -/
instance instFact2pow24SP1Prime : Fact (2 ^ 24 < SP1Prime) := ⟨by norm_num [SP1Prime]⟩

/-- Cast a single ℕ (a dumped canonical field value) into SP1's field. -/
def toField (n : ℕ) : ZMod SP1Prime := (n : ZMod SP1Prime)

end SP1Clean.TraceGenTests
