import SP1Clean.Foundations.Word
import SP1Clean.Extracted.ExtractionDSL
import Clean.Utils.Tactics.ProvableStructDeriving
import SP1Clean.Extracted.CPUState
import SP1Clean.Extracted.RTypeReader
import SP1Clean.Extracted.ITypeReader
import SP1Clean.Extracted.AddOperation

/-! # AUTO-GENERATED — do not edit by hand.

Generated by `update_extracted.py` from the `sp1-constraint-compiler`
(`--chip Addi --format lean --reuse-struct …`). Contains SP1's `Addi` chip column
struct plus the chip's composed-operation constraints, reusing the CPUState, RTypeReader, ITypeReader, AddOperation
column-struct module(s) (imported above, not re-emitted). Regenerate with
`SP1_DIR=… python3 update_extracted.py`. -/

namespace SP1Clean.Extracted
open SP1Clean

-- Generated Lean code for chip AddiChip

structure AddiCols (F : Type) where
  state : (CPUState F)
  adapter : (ITypeReader F)
  add_operation : (AddOperation F)
  is_real : F
deriving ProvableStruct

namespace AddiCols

set_option maxHeartbeats 8000000 in
@[irreducible] def asserts {F : Type} [Field F] [CoeHead F ℕ]
  (cols : (AddiCols F))
  : List F :=
  let E0 : F := cols.is_real - 1
  let E1 : F := cols.is_real * E0
  let E2 : F := cols.state.pc[0] + 4
  let E3 : F := cols.state.clk_16_24 * 65536
  let E4 : F := cols.state.clk_0_16 + E3
  AddOperation.asserts #v[cols.adapter.op_b_memory.prev_value[0], cols.adapter.op_b_memory.prev_value[1], cols.adapter.op_b_memory.prev_value[2], cols.adapter.op_b_memory.prev_value[3]] #v[cols.adapter.op_c_imm[0], cols.adapter.op_c_imm[1], cols.adapter.op_c_imm[2], cols.adapter.op_c_imm[3]] { value := #v[cols.add_operation.value[0], cols.add_operation.value[1], cols.add_operation.value[2], cols.add_operation.value[3]] } cols.is_real ++ CPUState.asserts { clk_high := cols.state.clk_high, clk_16_24 := cols.state.clk_16_24, clk_0_16 := cols.state.clk_0_16, pc := #v[cols.state.pc[0], cols.state.pc[1], cols.state.pc[2]] } #v[E2, cols.state.pc[1], cols.state.pc[2]] 8 cols.is_real ++ ITypeReader.asserts cols.state.clk_high E4 #v[cols.state.pc[0], cols.state.pc[1], cols.state.pc[2]] 1 #v[cols.add_operation.value[0], cols.add_operation.value[1], cols.add_operation.value[2], cols.add_operation.value[3]] { op_a := cols.adapter.op_a, op_a_memory := { prev_value := #v[cols.adapter.op_a_memory.prev_value[0], cols.adapter.op_a_memory.prev_value[1], cols.adapter.op_a_memory.prev_value[2], cols.adapter.op_a_memory.prev_value[3]], access_timestamp := { prev_low := cols.adapter.op_a_memory.access_timestamp.prev_low, diff_low_limb := cols.adapter.op_a_memory.access_timestamp.diff_low_limb } }, op_a_0 := cols.adapter.op_a_0, op_b := cols.adapter.op_b, op_b_memory := { prev_value := #v[cols.adapter.op_b_memory.prev_value[0], cols.adapter.op_b_memory.prev_value[1], cols.adapter.op_b_memory.prev_value[2], cols.adapter.op_b_memory.prev_value[3]], access_timestamp := { prev_low := cols.adapter.op_b_memory.access_timestamp.prev_low, diff_low_limb := cols.adapter.op_b_memory.access_timestamp.diff_low_limb } }, op_c_imm := #v[cols.adapter.op_c_imm[0], cols.adapter.op_c_imm[1], cols.adapter.op_c_imm[2], cols.adapter.op_c_imm[3]] } cols.is_real cols.is_real ++ [
    E1,
    cols.adapter.op_a_0,
  ]

set_option maxHeartbeats 8000000 in
@[irreducible] def interactions {F : Type} [Field F] [CoeHead F ℕ]
  (cols : (AddiCols F))
  : List (Interaction F) :=
  let E2 : F := cols.state.pc[0] + 4
  let E3 : F := cols.state.clk_16_24 * 65536
  let E4 : F := cols.state.clk_0_16 + E3
  AddOperation.interactions #v[cols.adapter.op_b_memory.prev_value[0], cols.adapter.op_b_memory.prev_value[1], cols.adapter.op_b_memory.prev_value[2], cols.adapter.op_b_memory.prev_value[3]] #v[cols.adapter.op_c_imm[0], cols.adapter.op_c_imm[1], cols.adapter.op_c_imm[2], cols.adapter.op_c_imm[3]] { value := #v[cols.add_operation.value[0], cols.add_operation.value[1], cols.add_operation.value[2], cols.add_operation.value[3]] } cols.is_real ++ CPUState.interactions { clk_high := cols.state.clk_high, clk_16_24 := cols.state.clk_16_24, clk_0_16 := cols.state.clk_0_16, pc := #v[cols.state.pc[0], cols.state.pc[1], cols.state.pc[2]] } #v[E2, cols.state.pc[1], cols.state.pc[2]] 8 cols.is_real ++ ITypeReader.interactions cols.state.clk_high E4 #v[cols.state.pc[0], cols.state.pc[1], cols.state.pc[2]] 1 #v[cols.add_operation.value[0], cols.add_operation.value[1], cols.add_operation.value[2], cols.add_operation.value[3]] { op_a := cols.adapter.op_a, op_a_memory := { prev_value := #v[cols.adapter.op_a_memory.prev_value[0], cols.adapter.op_a_memory.prev_value[1], cols.adapter.op_a_memory.prev_value[2], cols.adapter.op_a_memory.prev_value[3]], access_timestamp := { prev_low := cols.adapter.op_a_memory.access_timestamp.prev_low, diff_low_limb := cols.adapter.op_a_memory.access_timestamp.diff_low_limb } }, op_a_0 := cols.adapter.op_a_0, op_b := cols.adapter.op_b, op_b_memory := { prev_value := #v[cols.adapter.op_b_memory.prev_value[0], cols.adapter.op_b_memory.prev_value[1], cols.adapter.op_b_memory.prev_value[2], cols.adapter.op_b_memory.prev_value[3]], access_timestamp := { prev_low := cols.adapter.op_b_memory.access_timestamp.prev_low, diff_low_limb := cols.adapter.op_b_memory.access_timestamp.diff_low_limb } }, op_c_imm := #v[cols.adapter.op_c_imm[0], cols.adapter.op_c_imm[1], cols.adapter.op_c_imm[2], cols.adapter.op_c_imm[3]] } cols.is_real cols.is_real ++ [
  ]

end AddiCols

end SP1Clean.Extracted
