import SP1Clean.Foundations.Word
import SP1Clean.Extracted.ExtractionDSL
import Clean.Utils.Tactics.ProvableStructDeriving
import SP1Clean.Extracted.AddrAddOperation

/-! # AUTO-GENERATED — do not edit by hand.

Generated by `update_extracted.py` from the `sp1-constraint-compiler`
(`--operation AddressOperation --format lean`). Contains SP1's `AddressOperation` operation
constraints (reusing the AddrAddOperation column-struct module(s), imported above). Regenerate
with `SP1_DIR=… python3 update_extracted.py`; the faithfulness anchor lives under
`SP1Clean/Faithful/`. -/

set_option linter.all false  -- auto-generated: skip linters

namespace SP1Clean.Extracted
open SP1Clean

structure AddressOperation (F : Type) where
  addr_operation : (AddrAddOperation F)
  top_two_limb_inv : F
deriving ProvableStruct

namespace AddressOperation

set_option maxHeartbeats 8000000 in
@[irreducible] def asserts {F : Type} [Field F] [CoeHead F ℕ]
  (b : (Word F))
  (cc : (Word F))
  (offset_bit0 : F)
  (offset_bit1 : F)
  (offset_bit2 : F)
  (is_real : F)
  (cols : (AddressOperation F))
  : List F :=
  let E0 : F := is_real - 1
  let E1 : F := is_real * E0
  let E2 : F := offset_bit0 - 1
  let E3 : F := offset_bit0 * E2
  let E4 : F := offset_bit1 - 1
  let E5 : F := offset_bit1 * E4
  let E6 : F := offset_bit2 - 1
  let E7 : F := offset_bit2 * E6
  let E8 : F := cols.addr_operation.value[1] + cols.addr_operation.value[2]
  let E9 : F := cols.top_two_limb_inv * E8
  let E10 : F := E9 - is_real
  AddrAddOperation.asserts #v[b[0], b[1], b[2], b[3]] #v[cc[0], cc[1], cc[2], cc[3]] { value := #v[cols.addr_operation.value[0], cols.addr_operation.value[1], cols.addr_operation.value[2]] } is_real ++ [
    E1,
    E3,
    E5,
    E7,
    E10,
  ]

set_option maxHeartbeats 8000000 in
@[irreducible] def interactions {F : Type} [Field F] [CoeHead F ℕ]
  (b : (Word F))
  (cc : (Word F))
  (offset_bit0 : F)
  (offset_bit1 : F)
  (offset_bit2 : F)
  (is_real : F)
  (cols : (AddressOperation F))
  : List (Interaction F) :=
  let E11 : F := 4 * offset_bit2
  let E12 : F := cols.addr_operation.value[0] - E11
  let E13 : F := 2 * offset_bit1
  let E14 : F := E12 - E13
  let E15 : F := E14 - offset_bit0
  let E16 : F := E15 * ((8 : F)⁻¹)
  AddrAddOperation.interactions #v[b[0], b[1], b[2], b[3]] #v[cc[0], cc[1], cc[2], cc[3]] { value := #v[cols.addr_operation.value[0], cols.addr_operation.value[1], cols.addr_operation.value[2]] } is_real ++ [
    ⟨.send, (.byte (ByteOpcode.ofNat 6) E16 13 0), is_real⟩,
  ]

set_option maxHeartbeats 8000000 in
@[irreducible] def value {F : Type} [Field F] [CoeHead F ℕ]
  (_b : (Word F))
  (_cc : (Word F))
  (offset_bit0 : F)
  (offset_bit1 : F)
  (offset_bit2 : F)
  (_is_real : F)
  (cols : (AddressOperation F))
  : (Vector F 3) :=
  let E17 : F := 4 * offset_bit2
  let E18 : F := cols.addr_operation.value[0] - E17
  let E19 : F := 2 * offset_bit1
  let E20 : F := E18 - E19
  let E21 : F := E20 - offset_bit0
  #v[E21, cols.addr_operation.value[1], cols.addr_operation.value[2]]

end AddressOperation

end SP1Clean.Extracted
