import SP1Clean.Foundations.Word
import SP1Clean.Extracted.ExtractionDSL
import Clean.Utils.Tactics.ProvableStructDeriving
import SP1Clean.Extracted.CPUState
import SP1Clean.Extracted.RTypeReader
import SP1Clean.Extracted.ALUTypeReader

/-! # AUTO-GENERATED — do not edit by hand.

Generated by `update_extracted.py` from the `sp1-constraint-compiler`
(`--chip AluX0 --format lean --reuse-struct …`). Contains SP1's `AluX0` chip column
struct plus the chip's composed-operation constraints, reusing the CPUState, RTypeReader, ALUTypeReader
column-struct module(s) (imported above, not re-emitted). Regenerate with
`SP1_DIR=… python3 update_extracted.py`. -/

namespace SP1Clean.Extracted
open SP1Clean

-- Generated Lean code for chip AluX0Chip

structure AluX0Cols (F : Type) where
  state : (CPUState F)
  adapter : (ALUTypeReader F)
  opcode : F
  is_real : F
deriving ProvableStruct

namespace AluX0Cols

set_option maxHeartbeats 8000000 in
@[irreducible] def asserts {F : Type} [Field F] [CoeHead F ℕ]
  (cols : (AluX0Cols F))
  : List F :=
  let E0 : F := cols.is_real - 1
  let E1 : F := cols.is_real * E0
  let E2 : F := cols.adapter.op_a_0 - 1
  let E3 : F := cols.is_real * E2
  let E4 : F := cols.is_real - 1
  let E5 : F := E4 * cols.adapter.op_a_0
  let E6 : F := cols.state.pc[0] + 4
  let E9 : F := cols.is_real - 1
  let E10 : F := cols.is_real * E9
  let E11 : F := cols.is_real - 1
  let E12 : F := cols.adapter.imm_c - 0
  let E13 : F := E11 * E12
  let E15 : F := cols.adapter.op_a_memory.prev_value[0] - 0
  let E16 : F := cols.adapter.op_a_0 * E15
  let E17 : F := cols.adapter.op_a_memory.prev_value[1] - 0
  let E18 : F := cols.adapter.op_a_0 * E17
  let E19 : F := cols.adapter.op_a_memory.prev_value[2] - 0
  let E20 : F := cols.adapter.op_a_0 * E19
  let E21 : F := cols.adapter.op_a_memory.prev_value[3] - 0
  let E22 : F := cols.adapter.op_a_0 * E21
  let E24 : F := cols.is_real - 1
  let E25 : F := cols.is_real * E24
  let E31 : F := cols.is_real - 1
  let E32 : F := cols.is_real * E31
  let E38 : F := cols.is_real - cols.adapter.imm_c
  let E39 : F := E38 - 1
  let E40 : F := E38 * E39
  let E45 : F := cols.adapter.op_c_memory.prev_value[0] - cols.adapter.op_c[0]
  let E46 : F := cols.adapter.imm_c * E45
  let E47 : F := cols.adapter.op_c_memory.prev_value[1] - cols.adapter.op_c[1]
  let E48 : F := cols.adapter.imm_c * E47
  let E49 : F := cols.adapter.op_c_memory.prev_value[2] - cols.adapter.op_c[2]
  let E50 : F := cols.adapter.imm_c * E49
  let E51 : F := cols.adapter.op_c_memory.prev_value[3] - cols.adapter.op_c[3]
  let E52 : F := cols.adapter.imm_c * E51
  CPUState.asserts { clk_high := cols.state.clk_high, clk_16_24 := cols.state.clk_16_24, clk_0_16 := cols.state.clk_0_16, pc := #v[cols.state.pc[0], cols.state.pc[1], cols.state.pc[2]] } #v[E6, cols.state.pc[1], cols.state.pc[2]] 8 cols.is_real ++ [
    E1,
    E3,
    E5,
    E10,
    E13,
    E16,
    E18,
    E20,
    E22,
    E25,
    E32,
    E40,
    E46,
    E48,
    E50,
    E52,
  ]

set_option maxHeartbeats 8000000 in
@[irreducible] def interactions {F : Type} [Field F] [CoeHead F ℕ]
  (cols : (AluX0Cols F))
  : List (Interaction F) :=
  let E6 : F := cols.state.pc[0] + 4
  let E7 : F := cols.state.clk_16_24 * 65536
  let E8 : F := cols.state.clk_0_16 + E7
  let E14 : F := 0 + cols.adapter.op_b
  let E23 : F := E8 + 4
  let E26 : F := E23 - cols.adapter.op_a_memory.access_timestamp.prev_low
  let E27 : F := E26 - 1
  let E28 : F := E27 - cols.adapter.op_a_memory.access_timestamp.diff_low_limb
  let E29 : F := E28 * ((65536 : F)⁻¹)
  let E30 : F := E8 + 3
  let E33 : F := E30 - cols.adapter.op_b_memory.access_timestamp.prev_low
  let E34 : F := E33 - 1
  let E35 : F := E34 - cols.adapter.op_b_memory.access_timestamp.diff_low_limb
  let E36 : F := E35 * ((65536 : F)⁻¹)
  let E37 : F := E8 + 2
  let E38 : F := cols.is_real - cols.adapter.imm_c
  let E41 : F := E37 - cols.adapter.op_c_memory.access_timestamp.prev_low
  let E42 : F := E41 - 1
  let E43 : F := E42 - cols.adapter.op_c_memory.access_timestamp.diff_low_limb
  let E44 : F := E43 * ((65536 : F)⁻¹)
  CPUState.interactions { clk_high := cols.state.clk_high, clk_16_24 := cols.state.clk_16_24, clk_0_16 := cols.state.clk_0_16, pc := #v[cols.state.pc[0], cols.state.pc[1], cols.state.pc[2]] } #v[E6, cols.state.pc[1], cols.state.pc[2]] 8 cols.is_real ++ [
    ⟨.send, (.byte (ByteOpcode.ofNat 4) 1 cols.opcode 29), cols.is_real⟩,
    ⟨.send, (.program cols.state.pc[0] cols.state.pc[1] cols.state.pc[2] (Opcode.ofNat cols.opcode) cols.adapter.op_a E14 0 0 0 cols.adapter.op_c[0] cols.adapter.op_c[1] cols.adapter.op_c[2] cols.adapter.op_c[3] cols.adapter.op_a_0 0 cols.adapter.imm_c), cols.is_real⟩,
    ⟨.send, (.byte (ByteOpcode.ofNat 6) cols.adapter.op_a_memory.access_timestamp.diff_low_limb 16 0), cols.is_real⟩,
    ⟨.send, (.byte (ByteOpcode.ofNat 3) 0 E29 0), cols.is_real⟩,
    ⟨.send, (.memory cols.state.clk_high cols.adapter.op_a_memory.access_timestamp.prev_low cols.adapter.op_a 0 0 cols.adapter.op_a_memory.prev_value[0] cols.adapter.op_a_memory.prev_value[1] cols.adapter.op_a_memory.prev_value[2] cols.adapter.op_a_memory.prev_value[3]), cols.is_real⟩,
    ⟨.receive, (.memory cols.state.clk_high E23 cols.adapter.op_a 0 0 cols.adapter.op_a_memory.prev_value[0] cols.adapter.op_a_memory.prev_value[1] cols.adapter.op_a_memory.prev_value[2] cols.adapter.op_a_memory.prev_value[3]), cols.is_real⟩,
    ⟨.send, (.byte (ByteOpcode.ofNat 6) cols.adapter.op_b_memory.access_timestamp.diff_low_limb 16 0), cols.is_real⟩,
    ⟨.send, (.byte (ByteOpcode.ofNat 3) 0 E36 0), cols.is_real⟩,
    ⟨.send, (.memory cols.state.clk_high cols.adapter.op_b_memory.access_timestamp.prev_low cols.adapter.op_b 0 0 cols.adapter.op_b_memory.prev_value[0] cols.adapter.op_b_memory.prev_value[1] cols.adapter.op_b_memory.prev_value[2] cols.adapter.op_b_memory.prev_value[3]), cols.is_real⟩,
    ⟨.receive, (.memory cols.state.clk_high E30 cols.adapter.op_b 0 0 cols.adapter.op_b_memory.prev_value[0] cols.adapter.op_b_memory.prev_value[1] cols.adapter.op_b_memory.prev_value[2] cols.adapter.op_b_memory.prev_value[3]), cols.is_real⟩,
    ⟨.send, (.byte (ByteOpcode.ofNat 6) cols.adapter.op_c_memory.access_timestamp.diff_low_limb 16 0), E38⟩,
    ⟨.send, (.byte (ByteOpcode.ofNat 3) 0 E44 0), E38⟩,
    ⟨.send, (.memory cols.state.clk_high cols.adapter.op_c_memory.access_timestamp.prev_low cols.adapter.op_c[0] 0 0 cols.adapter.op_c_memory.prev_value[0] cols.adapter.op_c_memory.prev_value[1] cols.adapter.op_c_memory.prev_value[2] cols.adapter.op_c_memory.prev_value[3]), E38⟩,
    ⟨.receive, (.memory cols.state.clk_high E37 cols.adapter.op_c[0] 0 0 cols.adapter.op_c_memory.prev_value[0] cols.adapter.op_c_memory.prev_value[1] cols.adapter.op_c_memory.prev_value[2] cols.adapter.op_c_memory.prev_value[3]), E38⟩,
  ]

end AluX0Cols

end SP1Clean.Extracted
