import SP1Clean.Foundations.Word
import SP1Clean.Extracted.ExtractionDSL
import Clean.Utils.Tactics.ProvableStructDeriving
import SP1Clean.Extracted.U16toU8OperationUnsafe
import SP1Clean.Extracted.BitwiseOperation

/-! # AUTO-GENERATED — do not edit by hand.

Generated by `update_extracted.py` from the `sp1-constraint-compiler`
(`--operation BitwiseU16Operation --format lean`). Contains SP1's `BitwiseU16Operation` operation
constraints (reusing the U16toU8OperationUnsafe, BitwiseOperation column-struct module(s), imported above). Regenerate
with `SP1_DIR=… python3 update_extracted.py`; the faithfulness anchor lives under
`SP1Clean/Faithful/`. -/

namespace SP1Clean.Extracted
open SP1Clean

structure BitwiseU16Operation (F : Type) where
  b_low_bytes : (U16toU8Operation F)
  c_low_bytes : (U16toU8Operation F)
  bitwise_operation : (BitwiseOperation F)
deriving ProvableStruct

namespace BitwiseU16Operation

set_option maxHeartbeats 8000000 in
@[irreducible] def asserts {F : Type} [Field F] [CoeHead F ℕ]
  (b : (Word F))
  (cc : (Word F))
  (cols : (BitwiseU16Operation F))
  (opcode : F)
  (is_real : F)
  : List F :=
  let E0 : F := is_real - 1
  let E1 : F := is_real * E0
  let __call0_v := U16toU8OperationUnsafe.value #v[b[0], b[1], b[2], b[3]] { low_bytes := #v[cols.b_low_bytes.low_bytes[0], cols.b_low_bytes.low_bytes[1], cols.b_low_bytes.low_bytes[2], cols.b_low_bytes.low_bytes[3]] }
  let E2 := __call0_v[0]
  let E3 := __call0_v[1]
  let E4 := __call0_v[2]
  let E5 := __call0_v[3]
  let E6 := __call0_v[4]
  let E7 := __call0_v[5]
  let E8 := __call0_v[6]
  let E9 := __call0_v[7]
  let __call1_v := U16toU8OperationUnsafe.value #v[cc[0], cc[1], cc[2], cc[3]] { low_bytes := #v[cols.c_low_bytes.low_bytes[0], cols.c_low_bytes.low_bytes[1], cols.c_low_bytes.low_bytes[2], cols.c_low_bytes.low_bytes[3]] }
  let E10 := __call1_v[0]
  let E11 := __call1_v[1]
  let E12 := __call1_v[2]
  let E13 := __call1_v[3]
  let E14 := __call1_v[4]
  let E15 := __call1_v[5]
  let E16 := __call1_v[6]
  let E17 := __call1_v[7]
  U16toU8OperationUnsafe.asserts #v[b[0], b[1], b[2], b[3]] { low_bytes := #v[cols.b_low_bytes.low_bytes[0], cols.b_low_bytes.low_bytes[1], cols.b_low_bytes.low_bytes[2], cols.b_low_bytes.low_bytes[3]] } ++ U16toU8OperationUnsafe.asserts #v[cc[0], cc[1], cc[2], cc[3]] { low_bytes := #v[cols.c_low_bytes.low_bytes[0], cols.c_low_bytes.low_bytes[1], cols.c_low_bytes.low_bytes[2], cols.c_low_bytes.low_bytes[3]] } ++ BitwiseOperation.asserts #v[E2, E3, E4, E5, E6, E7, E8, E9] #v[E10, E11, E12, E13, E14, E15, E16, E17] { result := #v[cols.bitwise_operation.result[0], cols.bitwise_operation.result[1], cols.bitwise_operation.result[2], cols.bitwise_operation.result[3], cols.bitwise_operation.result[4], cols.bitwise_operation.result[5], cols.bitwise_operation.result[6], cols.bitwise_operation.result[7]] } opcode is_real ++ [
    E1,
  ]

set_option maxHeartbeats 8000000 in
@[irreducible] def interactions {F : Type} [Field F] [CoeHead F ℕ]
  (b : (Word F))
  (cc : (Word F))
  (cols : (BitwiseU16Operation F))
  (opcode : F)
  (is_real : F)
  : List (Interaction F) :=
  let __call0_v := U16toU8OperationUnsafe.value #v[b[0], b[1], b[2], b[3]] { low_bytes := #v[cols.b_low_bytes.low_bytes[0], cols.b_low_bytes.low_bytes[1], cols.b_low_bytes.low_bytes[2], cols.b_low_bytes.low_bytes[3]] }
  let E2 := __call0_v[0]
  let E3 := __call0_v[1]
  let E4 := __call0_v[2]
  let E5 := __call0_v[3]
  let E6 := __call0_v[4]
  let E7 := __call0_v[5]
  let E8 := __call0_v[6]
  let E9 := __call0_v[7]
  let __call1_v := U16toU8OperationUnsafe.value #v[cc[0], cc[1], cc[2], cc[3]] { low_bytes := #v[cols.c_low_bytes.low_bytes[0], cols.c_low_bytes.low_bytes[1], cols.c_low_bytes.low_bytes[2], cols.c_low_bytes.low_bytes[3]] }
  let E10 := __call1_v[0]
  let E11 := __call1_v[1]
  let E12 := __call1_v[2]
  let E13 := __call1_v[3]
  let E14 := __call1_v[4]
  let E15 := __call1_v[5]
  let E16 := __call1_v[6]
  let E17 := __call1_v[7]
  U16toU8OperationUnsafe.interactions #v[b[0], b[1], b[2], b[3]] { low_bytes := #v[cols.b_low_bytes.low_bytes[0], cols.b_low_bytes.low_bytes[1], cols.b_low_bytes.low_bytes[2], cols.b_low_bytes.low_bytes[3]] } ++ U16toU8OperationUnsafe.interactions #v[cc[0], cc[1], cc[2], cc[3]] { low_bytes := #v[cols.c_low_bytes.low_bytes[0], cols.c_low_bytes.low_bytes[1], cols.c_low_bytes.low_bytes[2], cols.c_low_bytes.low_bytes[3]] } ++ BitwiseOperation.interactions #v[E2, E3, E4, E5, E6, E7, E8, E9] #v[E10, E11, E12, E13, E14, E15, E16, E17] { result := #v[cols.bitwise_operation.result[0], cols.bitwise_operation.result[1], cols.bitwise_operation.result[2], cols.bitwise_operation.result[3], cols.bitwise_operation.result[4], cols.bitwise_operation.result[5], cols.bitwise_operation.result[6], cols.bitwise_operation.result[7]] } opcode is_real ++ [
  ]

set_option maxHeartbeats 8000000 in
@[irreducible] def value {F : Type} [Field F] [CoeHead F ℕ]
  (_b : (Word F))
  (_cc : (Word F))
  (cols : (BitwiseU16Operation F))
  (_opcode : F)
  (_is_real : F)
  : (Word F) :=
  let E18 : F := cols.bitwise_operation.result[1] * 256
  let E19 : F := cols.bitwise_operation.result[0] + E18
  let E20 : F := cols.bitwise_operation.result[3] * 256
  let E21 : F := cols.bitwise_operation.result[2] + E20
  let E22 : F := cols.bitwise_operation.result[5] * 256
  let E23 : F := cols.bitwise_operation.result[4] + E22
  let E24 : F := cols.bitwise_operation.result[7] * 256
  let E25 : F := cols.bitwise_operation.result[6] + E24
  #v[E19, E21, E23, E25]

end BitwiseU16Operation

end SP1Clean.Extracted
