import SP1Clean.Foundations.Word
import SP1Clean.Extracted.ExtractionDSL
import Clean.Utils.Tactics.ProvableStructDeriving

/-! # AUTO-GENERATED — do not edit by hand.

Generated by `update_extracted.py` from the `sp1-constraint-compiler`
(`--operation BitwiseOperation --format lean`). Contains SP1's `BitwiseOperation` operation
constraints (reusing the no column-struct module(s), imported above). Regenerate
with `SP1_DIR=… python3 update_extracted.py`; the faithfulness anchor lives under
`SP1Clean/Faithful/`. -/

set_option linter.all false  -- auto-generated: skip linters

namespace SP1Clean.Extracted
open SP1Clean

structure BitwiseOperation (F : Type) where
  result : (Vector F 8)
deriving ProvableStruct

namespace BitwiseOperation

set_option maxHeartbeats 8000000 in
@[irreducible] def asserts {F : Type} [Field F] [CoeHead F ℕ]
  (_a : (Vector F 8))
  (_b : (Vector F 8))
  (_cols : (BitwiseOperation F))
  (_opcode : F)
  (_is_real : F)
  : List F :=
  [
  ]

set_option maxHeartbeats 8000000 in
@[irreducible] def interactions {F : Type} [Field F] [CoeHead F ℕ]
  (a : (Vector F 8))
  (b : (Vector F 8))
  (cols : (BitwiseOperation F))
  (opcode : F)
  (is_real : F)
  : List (Interaction F) :=
  [
    ⟨.send, (.byte (ByteOpcode.ofNat opcode) cols.result[0] a[0] b[0]), is_real⟩,
    ⟨.send, (.byte (ByteOpcode.ofNat opcode) cols.result[1] a[1] b[1]), is_real⟩,
    ⟨.send, (.byte (ByteOpcode.ofNat opcode) cols.result[2] a[2] b[2]), is_real⟩,
    ⟨.send, (.byte (ByteOpcode.ofNat opcode) cols.result[3] a[3] b[3]), is_real⟩,
    ⟨.send, (.byte (ByteOpcode.ofNat opcode) cols.result[4] a[4] b[4]), is_real⟩,
    ⟨.send, (.byte (ByteOpcode.ofNat opcode) cols.result[5] a[5] b[5]), is_real⟩,
    ⟨.send, (.byte (ByteOpcode.ofNat opcode) cols.result[6] a[6] b[6]), is_real⟩,
    ⟨.send, (.byte (ByteOpcode.ofNat opcode) cols.result[7] a[7] b[7]), is_real⟩,
  ]

end BitwiseOperation

end SP1Clean.Extracted
