import SP1Clean.Foundations.SP1Constraint

/-! # Extraction DSL — the bus-interaction vocabulary the extracted constraints speak.

**Hand-written** (not generated by `update_extracted.py`), but lives under `Extracted/` and in the
`SP1Clean.Extracted` namespace because it is the surface the `sp1-constraint-compiler`
`--format lean` backend targets. Every generated `Extracted/<Op>.lean` emits two field lists per
operation/chip — an `asserts : List F` (each element `= 0`) and an `interactions :
List (Interaction F)` (bus sends/receives) — mirroring Clean's own `Operations.constraints` /
`Operations.interactions` split and isolating arithmetic faithfulness from bus faithfulness. There
is **no** `SP1Constraints` wrapper struct: the two lists are independent functions, composed by plain
`List.append` (`Sub0.asserts … ++ Sub1.asserts … ++ [own…]`).

Byte sends keep their **load-bearing** per-row meaning (range / AND·OR·XOR via `ByteOpcode.constrain`,
which lives in `Foundations/SP1Constraint.lean`); state/memory/program sends and all receives are
per-row `True` (their meaning is the trace-level bus balance, `Foundations/InteractionBus.lean`). -/

namespace SP1Clean.Extracted

open SP1Clean

variable {p : ℕ}

/-! ## `AirInteraction` (port of `SP1Foundations/Constraint.lean`)

The `byte` interaction carries the only fully-modelled semantics (range / AND·OR·XOR, via
`ByteOpcode.constrain`). The `state` / `memory` / `program` bus interactions are emitted by the
extracted chip column operations (`CPUState`, `RTypeReader`); their arities match SP1's
(`state` = 5, `memory` = 9, `program` = 16 with an `Opcode` at position 4). Their *meaning*
(global bus consistency: register/memory permutation, CPU-state chaining) is deferred — see
`docs/architecture.md` — so `Interaction.toProp` maps them to `True` below; they are present so the
extracted modules elaborate faithfully in structure. -/

inductive AirInteraction (F : Type) where
  | byte (op : ByteOpcode) (a b c : F)
  | state (a b c d e : F)
  | memory (a b c d e f g h i : F)
  | program (a b c : F) (op : Opcode) (d e f g h i j k l m n o : F)
  deriving DecidableEq

inductive Dir | send | receive
  deriving DecidableEq

structure Interaction (F : Type) where
  dir : Dir
  payload : AirInteraction F
  mult : F
  deriving DecidableEq

namespace Interaction

def toProp {p : ℕ} [NeZero p] : Interaction (ZMod p) → Prop
  | ⟨.send, .byte op a b c, mult⟩ => mult ≠ 0 → op.constrain a b c
  | _ => True

@[simp] lemma toProp_send_byte {p : ℕ} [NeZero p]
    (op : ByteOpcode) (a b c mult : ZMod p) :
    (⟨.send, .byte op a b c, mult⟩ : Interaction (ZMod p)).toProp ↔ (mult ≠ 0 → op.constrain a b c) :=
  Iff.rfl

/-- A `receive` of any interaction has trivial per-row meaning — its semantics are the trace-level
multiset balance (`Foundations/InteractionBus.lean`), not a row predicate. -/
@[simp] lemma toProp_receive {p : ℕ} [NeZero p] (i : AirInteraction (ZMod p)) (mult : ZMod p) :
    (⟨.receive, i, mult⟩ : Interaction (ZMod p)).toProp ↔ True := Iff.rfl

/-- A `send` of a `.state` interaction has trivial per-row meaning (the State bus's consistency is
the trace-level PC chain, `Soundness/StateConsistency.lean`). -/
@[simp] lemma toProp_send_state {p : ℕ} [NeZero p] (a b c d e mult : ZMod p) :
    (⟨.send, .state a b c d e, mult⟩ : Interaction (ZMod p)).toProp ↔ True := Iff.rfl

/-- A `send` of a `.memory` interaction has trivial per-row meaning (the memory bus's consistency is
the trace-level register/RAM permutation, `Soundness/MemoryConsistency.lean`). -/
@[simp] lemma toProp_send_memory {p : ℕ} [NeZero p] (a b c d e f g h i mult : ZMod p) :
    (⟨.send, .memory a b c d e f g h i, mult⟩ : Interaction (ZMod p)).toProp ↔ True := Iff.rfl

/-- A `send` of a `.program` interaction has trivial per-row meaning (the program bus's consistency is
the trace-level instruction-fetch membership, `Soundness/ProgramConsistency.lean`). -/
@[simp] lemma toProp_send_program {p : ℕ} [NeZero p]
    (a b c : ZMod p) (op : Opcode) (d e f g h i j k l m n o mult : ZMod p) :
    (⟨.send, .program a b c op d e f g h i j k l m n o, mult⟩ : Interaction (ZMod p)).toProp ↔ True :=
  Iff.rfl

end Interaction

/-! ## Composed-faithfulness peeling lemma

The two-list replacement for the old `SP1Constraints.allHold_append`. A composed operation/chip
emits its asserts and interactions as **parallel** append chains (`Sub0.x … ++ Sub1.x … ++ [own…]`
in the same sub-call order), so a faithfulness anchor peels one sub-operation's `(asserts,
interactions)` contribution per application — exactly mirroring how the chip anchors used to split
`CS0 ++ CS1 ++ …`. Applied explicitly (`rw [forall_append_pair, …]`), once per `++` in the chain. -/
theorem forall_append_pair {p : ℕ} [NeZero p]
    (a₁ a₂ : List (ZMod p)) (i₁ i₂ : List (Interaction (ZMod p))) :
    (List.Forall (· = 0) (a₁ ++ a₂) ∧ List.Forall Interaction.toProp (i₁ ++ i₂)) ↔
      ((List.Forall (· = 0) a₁ ∧ List.Forall Interaction.toProp i₁) ∧
       (List.Forall (· = 0) a₂ ∧ List.Forall Interaction.toProp i₂)) := by
  simp only [List.forall_append]; tauto

/-- Assertion-only peel: the `asserts`-half analogue of `forall_append_pair`, for anchoring a chip's
`asserts` append-chain on its own (after the two-list split). -/
theorem forall_append_single {p : ℕ} [NeZero p] (a₁ a₂ : List (ZMod p)) :
    List.Forall (· = 0) (a₁ ++ a₂) ↔
      (List.Forall (· = 0) a₁ ∧ List.Forall (· = 0) a₂) := by
  simp only [List.forall_append]

/-- Interaction-only peel: the `interactions`-half analogue of `forall_append_pair`. -/
theorem forall_append_interactions {p : ℕ} [NeZero p]
    (i₁ i₂ : List (Interaction (ZMod p))) :
    List.Forall Interaction.toProp (i₁ ++ i₂) ↔
      (List.Forall Interaction.toProp i₁ ∧ List.Forall Interaction.toProp i₂) := by
  simp only [List.forall_append]

end SP1Clean.Extracted
