import SP1Clean.Math.Word
import SP1Clean.Extracted.ExtractionDSL
import Clean.Utils.Tactics.ProvableStructDeriving
import SP1Clean.Extracted.IsZeroOperation
import SP1Clean.Extracted.IsZeroWordOperation

/-! # AUTO-GENERATED — do not edit by hand.

Generated by `update_extracted.py` from the `sp1-constraint-compiler`
(`--operation IsEqualWordOperation --format lean`). Contains SP1's `IsEqualWordOperation` operation
constraints (reusing the IsZeroOperation, IsZeroWordOperation column-struct module(s), imported above). Regenerate
with `SP1_DIR=… python3 update_extracted.py`; the faithfulness anchor lives under
`SP1Clean/Faithful/`. -/

set_option linter.all false  -- auto-generated: skip linters

namespace SP1Clean.Extracted
open SP1Clean

structure IsEqualWordOperation (F : Type) where
  is_diff_zero : (IsZeroWordOperation F)
deriving ProvableStruct

namespace IsEqualWordOperation

@[irreducible] def asserts {F : Type} [Field F] [CoeHead F ℕ]
  (a : (Word F))
  (b : (Word F))
  (cols : (IsEqualWordOperation F))
  (is_real : F)
  : List F :=
  let E0 : F := is_real - 1
  let E1 : F := is_real * E0
  let E2 : F := a[0] - b[0]
  let E3 : F := a[1] - b[1]
  let E4 : F := a[2] - b[2]
  let E5 : F := a[3] - b[3]
  IsZeroWordOperation.asserts #v[E2, E3, E4, E5] { is_zero_limb_0 := { inverse := cols.is_diff_zero.is_zero_limb_0.inverse, result := cols.is_diff_zero.is_zero_limb_0.result }, is_zero_limb_1 := { inverse := cols.is_diff_zero.is_zero_limb_1.inverse, result := cols.is_diff_zero.is_zero_limb_1.result }, is_zero_limb_2 := { inverse := cols.is_diff_zero.is_zero_limb_2.inverse, result := cols.is_diff_zero.is_zero_limb_2.result }, is_zero_limb_3 := { inverse := cols.is_diff_zero.is_zero_limb_3.inverse, result := cols.is_diff_zero.is_zero_limb_3.result }, is_zero_first_half := cols.is_diff_zero.is_zero_first_half, is_zero_second_half := cols.is_diff_zero.is_zero_second_half, result := cols.is_diff_zero.result } is_real ++ [
    E1,
  ]

@[irreducible] def interactions {F : Type} [Field F] [CoeHead F ℕ]
  (a : (Word F))
  (b : (Word F))
  (cols : (IsEqualWordOperation F))
  (is_real : F)
  : List (Interaction F) :=
  let E2 : F := a[0] - b[0]
  let E3 : F := a[1] - b[1]
  let E4 : F := a[2] - b[2]
  let E5 : F := a[3] - b[3]
  IsZeroWordOperation.interactions #v[E2, E3, E4, E5] { is_zero_limb_0 := { inverse := cols.is_diff_zero.is_zero_limb_0.inverse, result := cols.is_diff_zero.is_zero_limb_0.result }, is_zero_limb_1 := { inverse := cols.is_diff_zero.is_zero_limb_1.inverse, result := cols.is_diff_zero.is_zero_limb_1.result }, is_zero_limb_2 := { inverse := cols.is_diff_zero.is_zero_limb_2.inverse, result := cols.is_diff_zero.is_zero_limb_2.result }, is_zero_limb_3 := { inverse := cols.is_diff_zero.is_zero_limb_3.inverse, result := cols.is_diff_zero.is_zero_limb_3.result }, is_zero_first_half := cols.is_diff_zero.is_zero_first_half, is_zero_second_half := cols.is_diff_zero.is_zero_second_half, result := cols.is_diff_zero.result } is_real ++ [
  ]

end IsEqualWordOperation

end SP1Clean.Extracted
