import SP1Clean.Math.Word
import SP1Clean.Extracted.ExtractionDSL
import Clean.Utils.Tactics.ProvableStructDeriving

/-! # AUTO-GENERATED — do not edit by hand.

Generated by `update_extracted.py` from the `sp1-constraint-compiler`
(`--operation IsZeroOperation --format lean`). Contains SP1's `IsZeroOperation` operation
constraints (reusing the no column-struct module(s), imported above). Regenerate
with `SP1_DIR=… python3 update_extracted.py`; the faithfulness anchor lives under
`SP1Clean/Faithful/`. -/

set_option linter.all false  -- auto-generated: skip linters

namespace SP1Clean.Extracted
open SP1Clean

structure IsZeroOperation (F : Type) where
  inverse : F
  result : F
deriving ProvableStruct

namespace IsZeroOperation

set_option maxHeartbeats 8000000 in
@[irreducible] def asserts {F : Type} [Field F] [CoeHead F ℕ]
  (a : F)
  (cols : (IsZeroOperation F))
  (is_real : F)
  : List F :=
  let E0 : F := cols.inverse * a
  let E1 : F := 1 - E0
  let E2 : F := E1 - cols.result
  let E3 : F := is_real * E2
  let E4 : F := cols.result - 1
  let E5 : F := cols.result * E4
  let E6 : F := is_real * E5
  let E7 : F := cols.result * a
  let E8 : F := is_real * E7
  [
    E3,
    E6,
    E8,
  ]

set_option maxHeartbeats 8000000 in
@[irreducible] def interactions {F : Type} [Field F] [CoeHead F ℕ]
  (_a : F)
  (_cols : (IsZeroOperation F))
  (_is_real : F)
  : List (Interaction F) :=
  [
  ]

end IsZeroOperation

end SP1Clean.Extracted
