import SP1Clean.Math.Word
import SP1Clean.Extracted.ExtractionDSL
import Clean.Utils.Tactics.ProvableStructDeriving
import SP1Clean.Extracted.CPUState
import SP1Clean.Extracted.RTypeReader
import SP1Clean.Extracted.ITypeReader
import SP1Clean.Extracted.AddrAddOperation
import SP1Clean.Extracted.AddressOperation

/-! # AUTO-GENERATED — do not edit by hand.

Generated by `update_extracted.py` from the `sp1-constraint-compiler`
(`--chip LoadByte --format lean --reuse-struct …`). Contains SP1's `LoadByte` chip column
struct plus the chip's composed-operation constraints, reusing the CPUState, RTypeReader, ITypeReader, AddrAddOperation, AddressOperation
column-struct module(s) (imported above, not re-emitted). Regenerate with
`SP1_DIR=… python3 update_extracted.py`. -/

set_option linter.all false  -- auto-generated: skip linters

namespace SP1Clean.Extracted
open SP1Clean

-- Generated Lean code for chip LoadByteChip

structure MemoryAccessTimestamp (F : Type) where
  prev_high : F
  prev_low : F
  compare_low : F
  diff_low_limb : F
  diff_high_limb : F
deriving ProvableStruct

structure MemoryAccessCols (F : Type) where
  prev_value : (Word F)
  access_timestamp : (MemoryAccessTimestamp F)
deriving ProvableStruct

structure LoadByteColumns (F : Type) where
  state : (CPUState F)
  adapter : (ITypeReader F)
  address_operation : (AddressOperation F)
  memory_access : (MemoryAccessCols F)
  offset_bit : (Vector F 3)
  selected_limb : F
  selected_limb_low_byte : F
  selected_byte : F
  msb : F
  is_lb : F
  is_lbu : F
deriving ProvableStruct

namespace LoadByteColumns

set_option maxHeartbeats 8000000 in
@[irreducible] def asserts {F : Type} [Field F] [CoeHead F ℕ]
  (cols : (LoadByteColumns F))
  : List F :=
  let E0 : F := cols.state.clk_16_24 * 65536
  let E1 : F := cols.state.clk_0_16 + E0
  let E2 : F := 29 * cols.is_lb
  let E3 : F := 32 * cols.is_lbu
  let E4 : F := E2 + E3
  let E17 : F := cols.is_lb + cols.is_lbu
  let E18 : F := cols.is_lb - 1
  let E19 : F := cols.is_lb * E18
  let E20 : F := cols.is_lbu - 1
  let E21 : F := cols.is_lbu * E20
  let E22 : F := E17 - 1
  let E23 : F := E17 * E22
  let E27 : F := E1 + 1
  let E28 : F := E17 - 1
  let E29 : F := E17 * E28
  let E30 : F := cols.memory_access.access_timestamp.compare_low - 1
  let E31 : F := cols.memory_access.access_timestamp.compare_low * E30
  let E32 : F := E17 * E31
  let E33 : F := cols.state.clk_high - cols.memory_access.access_timestamp.prev_high
  let E34 : F := cols.memory_access.access_timestamp.compare_low * E33
  let E35 : F := E17 * E34
  let E36 : F := cols.memory_access.access_timestamp.compare_low * cols.memory_access.access_timestamp.prev_low
  let E37 : F := 1 - cols.memory_access.access_timestamp.compare_low
  let E38 : F := E37 * cols.memory_access.access_timestamp.prev_high
  let E39 : F := E36 + E38
  let E40 : F := cols.memory_access.access_timestamp.compare_low * E27
  let E41 : F := 1 - cols.memory_access.access_timestamp.compare_low
  let E42 : F := E41 * cols.state.clk_high
  let E43 : F := E40 + E42
  let E44 : F := E43 - E39
  let E45 : F := E44 - 1
  let E46 : F := cols.memory_access.access_timestamp.diff_high_limb * 65536
  let E47 : F := cols.memory_access.access_timestamp.diff_low_limb + E46
  let E48 : F := E45 - E47
  let E49 : F := E17 * E48
  let E50 : F := cols.offset_bit[1] - 1
  let E51 : F := cols.offset_bit[2] - 1
  let E52 : F := cols.selected_limb - cols.memory_access.prev_value[0]
  let E53 : F := E51 * E52
  let E54 : F := E50 * E53
  let E55 : F := cols.offset_bit[2] - 1
  let E56 : F := cols.selected_limb - cols.memory_access.prev_value[1]
  let E57 : F := E55 * E56
  let E58 : F := cols.offset_bit[1] * E57
  let E59 : F := cols.offset_bit[1] - 1
  let E60 : F := cols.selected_limb - cols.memory_access.prev_value[2]
  let E61 : F := cols.offset_bit[2] * E60
  let E62 : F := E59 * E61
  let E63 : F := cols.selected_limb - cols.memory_access.prev_value[3]
  let E64 : F := cols.offset_bit[2] * E63
  let E65 : F := cols.offset_bit[1] * E64
  let E66 : F := cols.selected_limb - cols.selected_limb_low_byte
  let E67 : F := E66 * ((256 : F)⁻¹)
  let E68 : F := cols.offset_bit[0] * E67
  let E69 : F := 1 - cols.offset_bit[0]
  let E70 : F := E69 * cols.selected_limb_low_byte
  let E71 : F := E68 + E70
  let E72 : F := cols.selected_byte - E71
  let E73 : F := cols.is_lbu * cols.msb
  let E74 : F := cols.state.pc[0] + 4
  let E75 : F := 65280 * cols.msb
  let E76 : F := cols.selected_byte + E75
  let E77 : F := 65535 * cols.msb
  let E78 : F := 65535 * cols.msb
  let E79 : F := 65535 * cols.msb
  AddressOperation.asserts #v[cols.adapter.op_b_memory.prev_value[0], cols.adapter.op_b_memory.prev_value[1], cols.adapter.op_b_memory.prev_value[2], cols.adapter.op_b_memory.prev_value[3]] #v[cols.adapter.op_c_imm[0], cols.adapter.op_c_imm[1], cols.adapter.op_c_imm[2], cols.adapter.op_c_imm[3]] cols.offset_bit[0] cols.offset_bit[1] cols.offset_bit[2] E17 { addr_operation := { value := #v[cols.address_operation.addr_operation.value[0], cols.address_operation.addr_operation.value[1], cols.address_operation.addr_operation.value[2]] }, top_two_limb_inv := cols.address_operation.top_two_limb_inv } ++ CPUState.asserts { clk_high := cols.state.clk_high, clk_16_24 := cols.state.clk_16_24, clk_0_16 := cols.state.clk_0_16, pc := #v[cols.state.pc[0], cols.state.pc[1], cols.state.pc[2]] } #v[E74, cols.state.pc[1], cols.state.pc[2]] 8 E17 ++ ITypeReader.asserts cols.state.clk_high E1 #v[cols.state.pc[0], cols.state.pc[1], cols.state.pc[2]] E4 #v[E76, E77, E78, E79] { op_a := cols.adapter.op_a, op_a_memory := { prev_value := #v[cols.adapter.op_a_memory.prev_value[0], cols.adapter.op_a_memory.prev_value[1], cols.adapter.op_a_memory.prev_value[2], cols.adapter.op_a_memory.prev_value[3]], access_timestamp := { prev_low := cols.adapter.op_a_memory.access_timestamp.prev_low, diff_low_limb := cols.adapter.op_a_memory.access_timestamp.diff_low_limb } }, op_a_0 := cols.adapter.op_a_0, op_b := cols.adapter.op_b, op_b_memory := { prev_value := #v[cols.adapter.op_b_memory.prev_value[0], cols.adapter.op_b_memory.prev_value[1], cols.adapter.op_b_memory.prev_value[2], cols.adapter.op_b_memory.prev_value[3]], access_timestamp := { prev_low := cols.adapter.op_b_memory.access_timestamp.prev_low, diff_low_limb := cols.adapter.op_b_memory.access_timestamp.diff_low_limb } }, op_c_imm := #v[cols.adapter.op_c_imm[0], cols.adapter.op_c_imm[1], cols.adapter.op_c_imm[2], cols.adapter.op_c_imm[3]] } E17 E17 ++ [
    E19,
    E21,
    E23,
    E29,
    E32,
    E35,
    E49,
    cols.adapter.op_a_0,
    E54,
    E58,
    E62,
    E65,
    E72,
    E73,
  ]

set_option maxHeartbeats 8000000 in
@[irreducible] def interactions {F : Type} [Field F] [CoeHead F ℕ]
  (cols : (LoadByteColumns F))
  : List (Interaction F) :=
  let E0 : F := cols.state.clk_16_24 * 65536
  let E1 : F := cols.state.clk_0_16 + E0
  let E2 : F := 29 * cols.is_lb
  let E3 : F := 32 * cols.is_lbu
  let E4 : F := E2 + E3
  let E17 : F := cols.is_lb + cols.is_lbu
  let __call0_v := AddressOperation.value #v[cols.adapter.op_b_memory.prev_value[0], cols.adapter.op_b_memory.prev_value[1], cols.adapter.op_b_memory.prev_value[2], cols.adapter.op_b_memory.prev_value[3]] #v[cols.adapter.op_c_imm[0], cols.adapter.op_c_imm[1], cols.adapter.op_c_imm[2], cols.adapter.op_c_imm[3]] cols.offset_bit[0] cols.offset_bit[1] cols.offset_bit[2] E17 { addr_operation := { value := #v[cols.address_operation.addr_operation.value[0], cols.address_operation.addr_operation.value[1], cols.address_operation.addr_operation.value[2]] }, top_two_limb_inv := cols.address_operation.top_two_limb_inv }
  let E24 := __call0_v[0]
  let E25 := __call0_v[1]
  let E26 := __call0_v[2]
  let E27 : F := E1 + 1
  let E66 : F := cols.selected_limb - cols.selected_limb_low_byte
  let E67 : F := E66 * ((256 : F)⁻¹)
  let E74 : F := cols.state.pc[0] + 4
  let E75 : F := 65280 * cols.msb
  let E76 : F := cols.selected_byte + E75
  let E77 : F := 65535 * cols.msb
  let E78 : F := 65535 * cols.msb
  let E79 : F := 65535 * cols.msb
  AddressOperation.interactions #v[cols.adapter.op_b_memory.prev_value[0], cols.adapter.op_b_memory.prev_value[1], cols.adapter.op_b_memory.prev_value[2], cols.adapter.op_b_memory.prev_value[3]] #v[cols.adapter.op_c_imm[0], cols.adapter.op_c_imm[1], cols.adapter.op_c_imm[2], cols.adapter.op_c_imm[3]] cols.offset_bit[0] cols.offset_bit[1] cols.offset_bit[2] E17 { addr_operation := { value := #v[cols.address_operation.addr_operation.value[0], cols.address_operation.addr_operation.value[1], cols.address_operation.addr_operation.value[2]] }, top_two_limb_inv := cols.address_operation.top_two_limb_inv } ++ CPUState.interactions { clk_high := cols.state.clk_high, clk_16_24 := cols.state.clk_16_24, clk_0_16 := cols.state.clk_0_16, pc := #v[cols.state.pc[0], cols.state.pc[1], cols.state.pc[2]] } #v[E74, cols.state.pc[1], cols.state.pc[2]] 8 E17 ++ ITypeReader.interactions cols.state.clk_high E1 #v[cols.state.pc[0], cols.state.pc[1], cols.state.pc[2]] E4 #v[E76, E77, E78, E79] { op_a := cols.adapter.op_a, op_a_memory := { prev_value := #v[cols.adapter.op_a_memory.prev_value[0], cols.adapter.op_a_memory.prev_value[1], cols.adapter.op_a_memory.prev_value[2], cols.adapter.op_a_memory.prev_value[3]], access_timestamp := { prev_low := cols.adapter.op_a_memory.access_timestamp.prev_low, diff_low_limb := cols.adapter.op_a_memory.access_timestamp.diff_low_limb } }, op_a_0 := cols.adapter.op_a_0, op_b := cols.adapter.op_b, op_b_memory := { prev_value := #v[cols.adapter.op_b_memory.prev_value[0], cols.adapter.op_b_memory.prev_value[1], cols.adapter.op_b_memory.prev_value[2], cols.adapter.op_b_memory.prev_value[3]], access_timestamp := { prev_low := cols.adapter.op_b_memory.access_timestamp.prev_low, diff_low_limb := cols.adapter.op_b_memory.access_timestamp.diff_low_limb } }, op_c_imm := #v[cols.adapter.op_c_imm[0], cols.adapter.op_c_imm[1], cols.adapter.op_c_imm[2], cols.adapter.op_c_imm[3]] } E17 E17 ++ [
    ⟨.send, (.byte (ByteOpcode.ofNat 6) cols.memory_access.access_timestamp.diff_low_limb 16 0), E17⟩,
    ⟨.send, (.byte (ByteOpcode.ofNat 3) 0 cols.memory_access.access_timestamp.diff_high_limb 0), E17⟩,
    ⟨.send, (.memory cols.memory_access.access_timestamp.prev_high cols.memory_access.access_timestamp.prev_low E24 E25 E26 cols.memory_access.prev_value[0] cols.memory_access.prev_value[1] cols.memory_access.prev_value[2] cols.memory_access.prev_value[3]), E17⟩,
    ⟨.receive, (.memory cols.state.clk_high E27 E24 E25 E26 cols.memory_access.prev_value[0] cols.memory_access.prev_value[1] cols.memory_access.prev_value[2] cols.memory_access.prev_value[3]), E17⟩,
    ⟨.send, (.byte (ByteOpcode.ofNat 3) 0 cols.selected_limb_low_byte E67), E17⟩,
    ⟨.send, (.byte (ByteOpcode.ofNat 5) cols.msb cols.selected_byte 0), cols.is_lb⟩,
  ]

end LoadByteColumns

end SP1Clean.Extracted
