import SP1Clean.Math.Word
import SP1Clean.Extracted.ExtractionDSL
import Clean.Utils.Tactics.ProvableStructDeriving
import SP1Clean.Extracted.U16CompareOperation

/-! # AUTO-GENERATED — do not edit by hand.

Generated by `update_extracted.py` from the `sp1-constraint-compiler`
(`--operation LtOperationUnsigned --format lean`). Contains SP1's `LtOperationUnsigned` operation
constraints (reusing the U16CompareOperation column-struct module(s), imported above). Regenerate
with `SP1_DIR=… python3 update_extracted.py`; the faithfulness anchor lives under
`SP1Clean/Faithful/`. -/

set_option linter.all false  -- auto-generated: skip linters

namespace SP1Clean.Extracted
open SP1Clean

structure LtOperationUnsigned (F : Type) where
  u16_compare_operation : (U16CompareOperation F)
  u16_flags : (Vector F 4)
  not_eq_inv : F
  comparison_limbs : (Vector F 2)
deriving ProvableStruct

namespace LtOperationUnsigned

set_option maxHeartbeats 8000000 in
@[irreducible] def asserts {F : Type} [Field F] [CoeHead F ℕ]
  (b : (Word F))
  (cc : (Word F))
  (cols : (LtOperationUnsigned F))
  (is_real : F)
  : List F :=
  let E0 : F := is_real - 1
  let E1 : F := is_real * E0
  let E2 : F := cols.u16_flags[0] + cols.u16_flags[1]
  let E3 : F := E2 + cols.u16_flags[2]
  let E4 : F := E3 + cols.u16_flags[3]
  let E5 : F := cols.u16_flags[0] - 1
  let E6 : F := cols.u16_flags[0] * E5
  let E7 : F := cols.u16_flags[1] - 1
  let E8 : F := cols.u16_flags[1] * E7
  let E9 : F := cols.u16_flags[2] - 1
  let E10 : F := cols.u16_flags[2] * E9
  let E11 : F := cols.u16_flags[3] - 1
  let E12 : F := cols.u16_flags[3] * E11
  let E13 : F := E4 - 1
  let E14 : F := E4 * E13
  let E15 : F := 1 - E4
  let E16 : F := 0 + cols.u16_flags[3]
  let E17 : F := is_real - E16
  let E18 : F := b[3] - cc[3]
  let E19 : F := E17 * E18
  let E20 : F := b[3] * cols.u16_flags[3]
  let E21 : F := 0 + E20
  let E22 : F := cc[3] * cols.u16_flags[3]
  let E23 : F := 0 + E22
  let E24 : F := E16 + cols.u16_flags[2]
  let E25 : F := is_real - E24
  let E26 : F := b[2] - cc[2]
  let E27 : F := E25 * E26
  let E28 : F := b[2] * cols.u16_flags[2]
  let E29 : F := E21 + E28
  let E30 : F := cc[2] * cols.u16_flags[2]
  let E31 : F := E23 + E30
  let E32 : F := E24 + cols.u16_flags[1]
  let E33 : F := is_real - E32
  let E34 : F := b[1] - cc[1]
  let E35 : F := E33 * E34
  let E36 : F := b[1] * cols.u16_flags[1]
  let E37 : F := E29 + E36
  let E38 : F := cc[1] * cols.u16_flags[1]
  let E39 : F := E31 + E38
  let E40 : F := E32 + cols.u16_flags[0]
  let E41 : F := is_real - E40
  let E42 : F := b[0] - cc[0]
  let E43 : F := E41 * E42
  let E44 : F := b[0] * cols.u16_flags[0]
  let E45 : F := E37 + E44
  let E46 : F := cc[0] * cols.u16_flags[0]
  let E47 : F := E39 + E46
  let E48 : F := E45 - cols.comparison_limbs[0]
  let E49 : F := E47 - cols.comparison_limbs[1]
  let E50 : F := E15 - 1
  let E51 : F := cols.comparison_limbs[0] - cols.comparison_limbs[1]
  let E52 : F := cols.not_eq_inv * E51
  let E53 : F := E52 - is_real
  let E54 : F := E50 * E53
  U16CompareOperation.asserts cols.comparison_limbs[0] cols.comparison_limbs[1] { bit := cols.u16_compare_operation.bit } is_real ++ [
    E1,
    E6,
    E8,
    E10,
    E12,
    E14,
    E19,
    E27,
    E35,
    E43,
    E48,
    E49,
    E54,
  ]

set_option maxHeartbeats 8000000 in
@[irreducible] def interactions {F : Type} [Field F] [CoeHead F ℕ]
  (_b : (Word F))
  (_cc : (Word F))
  (cols : (LtOperationUnsigned F))
  (is_real : F)
  : List (Interaction F) :=
  U16CompareOperation.interactions cols.comparison_limbs[0] cols.comparison_limbs[1] { bit := cols.u16_compare_operation.bit } is_real ++ [
  ]

end LtOperationUnsigned

end SP1Clean.Extracted
