import SP1Clean.Foundations.Word
import SP1Clean.Extracted.ExtractionDSL
import Clean.Utils.Tactics.ProvableStructDeriving
import SP1Clean.Extracted.U16CompareOperation
import SP1Clean.Extracted.LtOperationUnsigned
import SP1Clean.Extracted.U16MSBOperation

/-! # AUTO-GENERATED — do not edit by hand.

Generated by `update_extracted.py` from the `sp1-constraint-compiler`
(`--operation LtOperationSigned --format lean`). Contains SP1's `LtOperationSigned` operation
constraints (reusing the U16CompareOperation, LtOperationUnsigned, U16MSBOperation column-struct module(s), imported above). Regenerate
with `SP1_DIR=… python3 update_extracted.py`; the faithfulness anchor lives under
`SP1Clean/Faithful/`. -/

namespace SP1Clean.Extracted
open SP1Clean

structure LtOperationSigned (F : Type) where
  result : (LtOperationUnsigned F)
  b_msb : (U16MSBOperation F)
  c_msb : (U16MSBOperation F)
deriving ProvableStruct

namespace LtOperationSigned

set_option maxHeartbeats 8000000 in
@[irreducible] def asserts {F : Type} [Field F] [CoeHead F ℕ]
  (b : (Word F))
  (cc : (Word F))
  (cols : (LtOperationSigned F))
  (is_signed : F)
  (is_real : F)
  : List F :=
  let E0 : F := is_signed - 1
  let E1 : F := is_signed * E0
  let E2 : F := is_real - 1
  let E3 : F := is_real * E2
  let E4 : F := is_real - 1
  let E5 : F := E4 * is_signed
  let E6 : F := is_signed - 1
  let E7 : F := E6 * cols.b_msb.msb
  let E8 : F := is_signed - 1
  let E9 : F := E8 * cols.c_msb.msb
  let E10 : F := is_signed * 32768
  let E11 : F := b[3] + E10
  let E12 : F := 65536 * cols.b_msb.msb
  let E13 : F := E11 - E12
  let E14 : F := is_signed * 32768
  let E15 : F := cc[3] + E14
  let E16 : F := 65536 * cols.c_msb.msb
  let E17 : F := E15 - E16
  U16MSBOperation.asserts b[3] { msb := cols.b_msb.msb } is_signed ++ U16MSBOperation.asserts cc[3] { msb := cols.c_msb.msb } is_signed ++ LtOperationUnsigned.asserts #v[b[0], b[1], b[2], E13] #v[cc[0], cc[1], cc[2], E17] { u16_compare_operation := { bit := cols.result.u16_compare_operation.bit }, u16_flags := #v[cols.result.u16_flags[0], cols.result.u16_flags[1], cols.result.u16_flags[2], cols.result.u16_flags[3]], not_eq_inv := cols.result.not_eq_inv, comparison_limbs := #v[cols.result.comparison_limbs[0], cols.result.comparison_limbs[1]] } is_real ++ [
    E1,
    E3,
    E5,
    E7,
    E9,
  ]

set_option maxHeartbeats 8000000 in
@[irreducible] def interactions {F : Type} [Field F] [CoeHead F ℕ]
  (b : (Word F))
  (cc : (Word F))
  (cols : (LtOperationSigned F))
  (is_signed : F)
  (is_real : F)
  : List (Interaction F) :=
  let E10 : F := is_signed * 32768
  let E11 : F := b[3] + E10
  let E12 : F := 65536 * cols.b_msb.msb
  let E13 : F := E11 - E12
  let E14 : F := is_signed * 32768
  let E15 : F := cc[3] + E14
  let E16 : F := 65536 * cols.c_msb.msb
  let E17 : F := E15 - E16
  U16MSBOperation.interactions b[3] { msb := cols.b_msb.msb } is_signed ++ U16MSBOperation.interactions cc[3] { msb := cols.c_msb.msb } is_signed ++ LtOperationUnsigned.interactions #v[b[0], b[1], b[2], E13] #v[cc[0], cc[1], cc[2], E17] { u16_compare_operation := { bit := cols.result.u16_compare_operation.bit }, u16_flags := #v[cols.result.u16_flags[0], cols.result.u16_flags[1], cols.result.u16_flags[2], cols.result.u16_flags[3]], not_eq_inv := cols.result.not_eq_inv, comparison_limbs := #v[cols.result.comparison_limbs[0], cols.result.comparison_limbs[1]] } is_real ++ [
  ]

end LtOperationSigned

end SP1Clean.Extracted
