import SP1Clean.Math.Word
import SP1Clean.Extracted.ExtractionDSL
import Clean.Utils.Tactics.ProvableStructDeriving

/-! # AUTO-GENERATED — do not edit by hand.

Generated by `update_extracted.py` from the `sp1-constraint-compiler`
(`--operation SubOperation --format lean`). Contains SP1's `SubOperation` operation
constraints (reusing the no column-struct module(s), imported above). Regenerate
with `SP1_DIR=… python3 update_extracted.py`; the faithfulness anchor lives under
`SP1Clean/Faithful/`. -/

set_option linter.all false  -- auto-generated: skip linters

namespace SP1Clean.Extracted
open SP1Clean

structure SubOperation (F : Type) where
  value : (Word F)
deriving ProvableStruct

namespace SubOperation

set_option maxHeartbeats 8000000 in
@[irreducible] def asserts {F : Type} [Field F] [CoeHead F ℕ]
  (a : (Word F))
  (b : (Word F))
  (cols : (SubOperation F))
  (is_real : F)
  : List F :=
  let E0 : F := is_real - 1
  let E1 : F := is_real * E0
  let E2 : F := a[0] + 65536
  let E3 : F := E2 - 1
  let E4 : F := E3 - b[0]
  let E5 : F := E4 - cols.value[0]
  let E6 : F := E5 + 1
  let E7 : F := E6 * ((65536 : F)⁻¹)
  let E8 : F := E7 - 1
  let E9 : F := E7 * E8
  let E10 : F := is_real * E9
  let E11 : F := a[1] + 65536
  let E12 : F := E11 - 1
  let E13 : F := E12 - b[1]
  let E14 : F := E13 - cols.value[1]
  let E15 : F := E14 + E7
  let E16 : F := E15 * ((65536 : F)⁻¹)
  let E17 : F := E16 - 1
  let E18 : F := E16 * E17
  let E19 : F := is_real * E18
  let E20 : F := a[2] + 65536
  let E21 : F := E20 - 1
  let E22 : F := E21 - b[2]
  let E23 : F := E22 - cols.value[2]
  let E24 : F := E23 + E16
  let E25 : F := E24 * ((65536 : F)⁻¹)
  let E26 : F := E25 - 1
  let E27 : F := E25 * E26
  let E28 : F := is_real * E27
  let E29 : F := a[3] + 65536
  let E30 : F := E29 - 1
  let E31 : F := E30 - b[3]
  let E32 : F := E31 - cols.value[3]
  let E33 : F := E32 + E25
  let E34 : F := E33 * ((65536 : F)⁻¹)
  let E35 : F := E34 - 1
  let E36 : F := E34 * E35
  let E37 : F := is_real * E36
  [
    E1,
    E10,
    E19,
    E28,
    E37,
  ]

set_option maxHeartbeats 8000000 in
@[irreducible] def interactions {F : Type} [Field F] [CoeHead F ℕ]
  (_a : (Word F))
  (_b : (Word F))
  (cols : (SubOperation F))
  (is_real : F)
  : List (Interaction F) :=
  [
    ⟨.send, (.byte (ByteOpcode.ofNat 6) cols.value[0] 16 0), is_real⟩,
    ⟨.send, (.byte (ByteOpcode.ofNat 6) cols.value[1] 16 0), is_real⟩,
    ⟨.send, (.byte (ByteOpcode.ofNat 6) cols.value[2] 16 0), is_real⟩,
    ⟨.send, (.byte (ByteOpcode.ofNat 6) cols.value[3] 16 0), is_real⟩,
  ]

end SubOperation

end SP1Clean.Extracted
