import SP1Clean.Math.Word
import SP1Clean.Extracted.ExtractionDSL
import Clean.Utils.Tactics.ProvableStructDeriving
import SP1Clean.Extracted.U16MSBOperation

/-! # AUTO-GENERATED — do not edit by hand.

Generated by `update_extracted.py` from the `sp1-constraint-compiler`
(`--operation SubwOperation --format lean`). Contains SP1's `SubwOperation` operation
constraints (reusing the U16MSBOperation column-struct module(s), imported above). Regenerate
with `SP1_DIR=… python3 update_extracted.py`; the faithfulness anchor lives under
`SP1Clean/Faithful/`. -/

set_option linter.all false  -- auto-generated: skip linters

namespace SP1Clean.Extracted
open SP1Clean

structure SubwOperation (F : Type) where
  value : (Vector F 2)
  msb : (U16MSBOperation F)
deriving ProvableStruct

namespace SubwOperation

set_option maxHeartbeats 8000000 in
@[irreducible] def asserts {F : Type} [Field F] [CoeHead F ℕ]
  (a : (Word F))
  (b : (Word F))
  (cols : (SubwOperation F))
  (is_real : F)
  : List F :=
  let E0 : F := is_real - 1
  let E1 : F := is_real * E0
  let E2 : F := a[0] + 65536
  let E3 : F := E2 - 1
  let E4 : F := E3 - b[0]
  let E5 : F := E4 - cols.value[0]
  let E6 : F := E5 + 1
  let E7 : F := E6 * ((65536 : F)⁻¹)
  let E8 : F := E7 - 1
  let E9 : F := E7 * E8
  let E10 : F := is_real * E9
  let E11 : F := a[1] + 65536
  let E12 : F := E11 - 1
  let E13 : F := E12 - b[1]
  let E14 : F := E13 - cols.value[1]
  let E15 : F := E14 + E7
  let E16 : F := E15 * ((65536 : F)⁻¹)
  let E17 : F := E16 - 1
  let E18 : F := E16 * E17
  let E19 : F := is_real * E18
  U16MSBOperation.asserts cols.value[1] { msb := cols.msb.msb } is_real ++ [
    E1,
    E10,
    E19,
  ]

set_option maxHeartbeats 8000000 in
@[irreducible] def interactions {F : Type} [Field F] [CoeHead F ℕ]
  (_a : (Word F))
  (_b : (Word F))
  (cols : (SubwOperation F))
  (is_real : F)
  : List (Interaction F) :=
  U16MSBOperation.interactions cols.value[1] { msb := cols.msb.msb } is_real ++ [
    ⟨.send, (.byte 6 cols.value[0] 16 0), is_real⟩,
    ⟨.send, (.byte 6 cols.value[1] 16 0), is_real⟩,
  ]

end SubwOperation

end SP1Clean.Extracted
