import SP1Clean.Math.Word
import SP1Clean.Extracted.ExtractionDSL
import Clean.Utils.Tactics.ProvableStructDeriving

/-! # AUTO-GENERATED — do not edit by hand.

Generated by `update_extracted.py` from the `sp1-constraint-compiler`
(`--operation U16CompareOperation --format lean`). Contains SP1's `U16CompareOperation` operation
constraints (reusing no column-struct modules). Regenerate
with `SP1_DIR=… python3 update_extracted.py`; the faithfulness anchor lives under
`SP1Clean/Faithful/`. -/

set_option linter.all false  -- auto-generated: skip linters

namespace SP1Clean.Extracted
open SP1Clean

structure U16CompareOperation (F : Type) where
  bit : F
deriving ProvableStruct

namespace U16CompareOperation

@[irreducible] def asserts {F : Type} [Field F] [CoeHead F ℕ]
  (_a : F)
  (_b : F)
  (cols : (U16CompareOperation F))
  (is_real : F)
  : List F :=
  let E0 : F := is_real - 1
  let E1 : F := is_real * E0
  let E2 : F := cols.bit - 1
  let E3 : F := cols.bit * E2
  [
    E1,
    E3,
  ]

@[irreducible] def interactions {F : Type} [Field F] [CoeHead F ℕ]
  (a : F)
  (b : F)
  (cols : (U16CompareOperation F))
  (is_real : F)
  : List (Interaction F) :=
  let E4 : F := a - b
  let E5 : F := cols.bit * 65536
  let E6 : F := E4 + E5
  [
    ⟨.send, (.byte 6 E6 16 0), is_real⟩,
  ]

end U16CompareOperation

end SP1Clean.Extracted
