import SP1Clean.Foundations.Word
import SP1Clean.Extracted.ExtractionDSL
import Clean.Utils.Tactics.ProvableStructDeriving

/-! # AUTO-GENERATED — do not edit by hand.

Generated by `update_extracted.py` from the `sp1-constraint-compiler`
(`--operation U16MSBOperation --format lean`). Contains SP1's `U16MSBOperation` operation
constraints (reusing the no column-struct module(s), imported above). Regenerate
with `SP1_DIR=… python3 update_extracted.py`; the faithfulness anchor lives under
`SP1Clean/Faithful/`. -/

namespace SP1Clean.Extracted
open SP1Clean

structure U16MSBOperation (F : Type) where
  msb : F
deriving ProvableStruct

namespace U16MSBOperation

set_option maxHeartbeats 8000000 in
@[irreducible] def asserts {F : Type} [Field F] [CoeHead F ℕ]
  (_a : F)
  (cols : (U16MSBOperation F))
  (is_real : F)
  : List F :=
  let E0 : F := is_real - 1
  let E1 : F := is_real * E0
  let E2 : F := cols.msb - 1
  let E3 : F := cols.msb * E2
  [
    E1,
    E3,
  ]

set_option maxHeartbeats 8000000 in
@[irreducible] def interactions {F : Type} [Field F] [CoeHead F ℕ]
  (a : F)
  (cols : (U16MSBOperation F))
  (is_real : F)
  : List (Interaction F) :=
  let E4 : F := 2 * a
  let E5 : F := cols.msb * 65536
  let E6 : F := E4 - E5
  [
    ⟨.send, (.byte (ByteOpcode.ofNat 6) E6 16 0), is_real⟩,
  ]

end U16MSBOperation

end SP1Clean.Extracted
