import SP1Clean.Math.Word
import SP1Clean.Extracted.ExtractionDSL
import Clean.Utils.Tactics.ProvableStructDeriving

/-! # AUTO-GENERATED — do not edit by hand.

Generated by `update_extracted.py` from the `sp1-constraint-compiler`
(`--operation U16toU8OperationUnsafe --format lean`). Contains SP1's `U16toU8OperationUnsafe` operation
constraints (reusing no column-struct modules). Regenerate
with `SP1_DIR=… python3 update_extracted.py`; the faithfulness anchor lives under
`SP1Clean/Faithful/`. -/

set_option linter.all false  -- auto-generated: skip linters

namespace SP1Clean.Extracted
open SP1Clean

structure U16toU8Operation (F : Type) where
  low_bytes : (Vector F 4)
deriving ProvableStruct

namespace U16toU8OperationUnsafe

@[irreducible] def asserts {F : Type} [Field F] [CoeHead F ℕ]
  (_u16_values : (Vector F 4))
  (_cols : (U16toU8Operation F))
  : List F :=
  [
  ]

@[irreducible] def interactions {F : Type} [Field F] [CoeHead F ℕ]
  (_u16_values : (Vector F 4))
  (_cols : (U16toU8Operation F))
  : List (Interaction F) :=
  [
  ]

@[irreducible] def value {F : Type} [Field F] [CoeHead F ℕ]
  (u16_values : (Vector F 4))
  (cols : (U16toU8Operation F))
  : (Vector F 8) :=
  let E0 : F := u16_values[0] - cols.low_bytes[0]
  let E1 : F := E0 * ((256 : F)⁻¹)
  let E2 : F := u16_values[1] - cols.low_bytes[1]
  let E3 : F := E2 * ((256 : F)⁻¹)
  let E4 : F := u16_values[2] - cols.low_bytes[2]
  let E5 : F := E4 * ((256 : F)⁻¹)
  let E6 : F := u16_values[3] - cols.low_bytes[3]
  let E7 : F := E6 * ((256 : F)⁻¹)
  #v[cols.low_bytes[0], E1, cols.low_bytes[1], E3, cols.low_bytes[2], E5, cols.low_bytes[3], E7]

end U16toU8OperationUnsafe

end SP1Clean.Extracted
