import SP1Clean.Foundations.Word
import SP1Clean.Foundations.Channels
import SP1Clean.Foundations.ByteTable
import SP1Clean.Extracted.U16CompareOperation
import Clean.Circuit.Basic
import Clean.Circuit.Subcircuit
import Clean.Circuit.Channel
import Clean.Gadgets.Equality
import Clean.Utils.Tactics.ProvableStructDeriving

/-! # AUTO-GENERATED circuit form — do not edit by hand.

SP1's `U16CompareOperation::eval` as a Clean `Circuit`: the `Inputs` struct (the `eval` params
verbatim — the column struct nested as `cols`), the `main` do-block, and the
`ElaboratedCircuit` instance + `@[circuit_norm]` rfl-lemmas. Generated by
`update_extracted.py` from the `sp1-constraint-compiler` (`--operation U16CompareOperation --format
lean-circuit`). This *is* the faithful artifact the gadget's soundness/completeness run
against — no separate `asserts`/`interactions` bridge. Regenerate with
`SP1_DIR=… python3 update_extracted.py`. -/

set_option linter.all false  -- auto-generated: skip linters

namespace SP1Clean.U16CompareOperation

open Circuit
open SP1Clean.Channels (byteChannel)
open SP1Clean.Extracted

variable {p : ℕ} [Fact p.Prime] [Fact (2 ^ 17 < p)]

structure Inputs (F : Type) where
  a : F
  b : F
  cols : (U16CompareOperation F)
  is_real : F
deriving ProvableStruct

def main (input : Var Inputs (ZMod p)) : Circuit (ZMod p) Unit := do
  let a := input.a
  let b := input.b
  let cols := input.cols
  let is_real := input.is_real
  let E0 := is_real - 1
  let E1 := is_real * E0
  let E2 := cols.bit - 1
  let E3 := cols.bit * E2
  let E4 := a - b
  let E5 := cols.bit * 65536
  let E6 := E4 + E5
  byteChannel.gatedReceive is_real (⟨6, E6, Expression.const ((16 : ℕ) : ZMod p), 0⟩ : ByteRow (Expression (ZMod p)))
  E1 === 0
  E3 === 0

instance elaborated : ElaboratedCircuit (ZMod p) Inputs unit main where
  localLength _ := 0
  output _ _ := ()
  channelsWithGuarantees := [byteChannel.toRawGated]
  channelsWithRequirements := [byteChannel.toRawGated]

set_option linter.unusedSectionVars false in
@[circuit_norm] lemma channelsWithGuarantees_eq :
    ((elaborated (p := p)).channelsWithGuarantees : List (RawChannel (ZMod p)))
      = [byteChannel.toRawGated] := rfl
set_option linter.unusedSectionVars false in
@[circuit_norm] lemma channelsWithRequirements_eq :
    ((elaborated (p := p)).channelsWithRequirements : List (RawChannel (ZMod p)))
      = [byteChannel.toRawGated] := rfl
set_option linter.unusedSectionVars false in
@[circuit_norm] lemma localLength_eq (x : Var Inputs (ZMod p)) :
    (elaborated (p := p)).localLength x = 0 := rfl

end SP1Clean.U16CompareOperation
