import SP1Clean.Native.Operations.MulOperation.RawSpec

/-! # `MulOperation` native circuit

The proof-oriented Clean implementation. Its whole-chip faithfulness proof compares the assembled
native assertion and interaction system with the independent Rust anchor lists. -/

namespace SP1Clean.MulOperation

open Circuit
open SP1Clean.Channels (byteChannel)

variable {p : ℕ} [Fact p.Prime] [Fact (2 ^ 24 < p)]

set_option maxHeartbeats 8000000 in
/-- SP1's `MulOperation::eval` as a Clean `FormalAssertion`: compose `U16toU8OperationSafe`/`U16MSBOperation`
over the `populate`d `cols` (gated on `is_real` / `is_mulw`), `is_real`-gated `slice_range_check` byte pulls
on the carries (u16) and products (u8 pairs), the two sign-extend definitions, and the 16 `is_real`-gated
schoolbook carry-chain product equations. Witnesses nothing — the column struct is an input. The result
word is reconstructed (`resultWord`) and placed at the chip level. -/
def main (input : Var Inputs (ZMod p)) : Circuit (ZMod p) Unit := do
  let cols := input.cols
  let is_real := input.is_real
  assertZero (is_real * (is_real - 1))
  assertion U16toU8OperationSafe.circuit ⟨input.b, cols.b_lower_byte, is_real⟩
  assertion U16toU8OperationSafe.circuit ⟨input.c, cols.c_lower_byte, is_real⟩
  assertion U16MSBOperation.circuit ⟨cols.product[2] + cols.product[3] * 256, cols.product_msb, input.is_mulw⟩
  -- `b_msb`/`c_msb`: SP1 (`mul.rs`) asserts booleanity **unconditionally** (`assert_bool`) and pins the
  -- byte-MSB semantics via an `is_real`-gated `MSB`(opcode 5) byte send on the high decomposition byte
  -- `E7 = (b[3]-low[3])/256`. (The old `U16MSBOperation` gadget conflated both into one `Range` send.)
  cols.b_msb * (cols.b_msb - 1) === 0
  cols.c_msb * (cols.c_msb - 1) === 0
  byteChannel.pullIf is_real
    (⟨5, cols.b_msb, (input.b[3] - cols.b_lower_byte.low_bytes[3]) * Expression.const ((256 : ZMod p)⁻¹), 0⟩
      : ByteRow (Expression (ZMod p)))
  byteChannel.pullIf is_real
    (⟨5, cols.c_msb, (input.c[3] - cols.c_lower_byte.low_bytes[3]) * Expression.const ((256 : ZMod p)⁻¹), 0⟩
      : ByteRow (Expression (ZMod p)))
  byteChannel.pullIf is_real (⟨6, cols.carry[0], Expression.const ((16 : ℕ) : ZMod p), 0⟩ : ByteRow (Expression (ZMod p)))
  byteChannel.pullIf is_real (⟨6, cols.carry[1], Expression.const ((16 : ℕ) : ZMod p), 0⟩ : ByteRow (Expression (ZMod p)))
  byteChannel.pullIf is_real (⟨6, cols.carry[2], Expression.const ((16 : ℕ) : ZMod p), 0⟩ : ByteRow (Expression (ZMod p)))
  byteChannel.pullIf is_real (⟨6, cols.carry[3], Expression.const ((16 : ℕ) : ZMod p), 0⟩ : ByteRow (Expression (ZMod p)))
  byteChannel.pullIf is_real (⟨6, cols.carry[4], Expression.const ((16 : ℕ) : ZMod p), 0⟩ : ByteRow (Expression (ZMod p)))
  byteChannel.pullIf is_real (⟨6, cols.carry[5], Expression.const ((16 : ℕ) : ZMod p), 0⟩ : ByteRow (Expression (ZMod p)))
  byteChannel.pullIf is_real (⟨6, cols.carry[6], Expression.const ((16 : ℕ) : ZMod p), 0⟩ : ByteRow (Expression (ZMod p)))
  byteChannel.pullIf is_real (⟨6, cols.carry[7], Expression.const ((16 : ℕ) : ZMod p), 0⟩ : ByteRow (Expression (ZMod p)))
  byteChannel.pullIf is_real (⟨6, cols.carry[8], Expression.const ((16 : ℕ) : ZMod p), 0⟩ : ByteRow (Expression (ZMod p)))
  byteChannel.pullIf is_real (⟨6, cols.carry[9], Expression.const ((16 : ℕ) : ZMod p), 0⟩ : ByteRow (Expression (ZMod p)))
  byteChannel.pullIf is_real (⟨6, cols.carry[10], Expression.const ((16 : ℕ) : ZMod p), 0⟩ : ByteRow (Expression (ZMod p)))
  byteChannel.pullIf is_real (⟨6, cols.carry[11], Expression.const ((16 : ℕ) : ZMod p), 0⟩ : ByteRow (Expression (ZMod p)))
  byteChannel.pullIf is_real (⟨6, cols.carry[12], Expression.const ((16 : ℕ) : ZMod p), 0⟩ : ByteRow (Expression (ZMod p)))
  byteChannel.pullIf is_real (⟨6, cols.carry[13], Expression.const ((16 : ℕ) : ZMod p), 0⟩ : ByteRow (Expression (ZMod p)))
  byteChannel.pullIf is_real (⟨6, cols.carry[14], Expression.const ((16 : ℕ) : ZMod p), 0⟩ : ByteRow (Expression (ZMod p)))
  byteChannel.pullIf is_real (⟨6, cols.carry[15], Expression.const ((16 : ℕ) : ZMod p), 0⟩ : ByteRow (Expression (ZMod p)))
  byteChannel.pullIf is_real (⟨3, 0, cols.product[0], cols.product[1]⟩ : ByteRow (Expression (ZMod p)))
  byteChannel.pullIf is_real (⟨3, 0, cols.product[2], cols.product[3]⟩ : ByteRow (Expression (ZMod p)))
  byteChannel.pullIf is_real (⟨3, 0, cols.product[4], cols.product[5]⟩ : ByteRow (Expression (ZMod p)))
  byteChannel.pullIf is_real (⟨3, 0, cols.product[6], cols.product[7]⟩ : ByteRow (Expression (ZMod p)))
  byteChannel.pullIf is_real (⟨3, 0, cols.product[8], cols.product[9]⟩ : ByteRow (Expression (ZMod p)))
  byteChannel.pullIf is_real (⟨3, 0, cols.product[10], cols.product[11]⟩ : ByteRow (Expression (ZMod p)))
  byteChannel.pullIf is_real (⟨3, 0, cols.product[12], cols.product[13]⟩ : ByteRow (Expression (ZMod p)))
  byteChannel.pullIf is_real (⟨3, 0, cols.product[14], cols.product[15]⟩ : ByteRow (Expression (ZMod p)))
  cols.b_sign_extend === (input.is_mulh + input.is_mulhsu) * cols.b_msb
  cols.c_sign_extend === input.is_mulh * cols.c_msb
  cols.b_sign_extend * (cols.b_msb - 1) === 0
  cols.c_sign_extend * (cols.c_msb - 1) === 0
  is_real * (cols.product[0] - (((cols.b_lower_byte.low_bytes[0]) * (cols.c_lower_byte.low_bytes[0])) - cols.carry[0] * 256)) === 0
  is_real * (cols.product[1] - (((cols.b_lower_byte.low_bytes[0]) * ((input.c[0] - cols.c_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) + ((input.b[0] - cols.b_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) * (cols.c_lower_byte.low_bytes[0])) + cols.carry[0] - cols.carry[1] * 256)) === 0
  is_real * (cols.product[2] - (((cols.b_lower_byte.low_bytes[0]) * (cols.c_lower_byte.low_bytes[1]) + ((input.b[0] - cols.b_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) * ((input.c[0] - cols.c_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) + (cols.b_lower_byte.low_bytes[1]) * (cols.c_lower_byte.low_bytes[0])) + cols.carry[1] - cols.carry[2] * 256)) === 0
  is_real * (cols.product[3] - (((cols.b_lower_byte.low_bytes[0]) * ((input.c[1] - cols.c_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) + ((input.b[0] - cols.b_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) * (cols.c_lower_byte.low_bytes[1]) + (cols.b_lower_byte.low_bytes[1]) * ((input.c[0] - cols.c_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) + ((input.b[1] - cols.b_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) * (cols.c_lower_byte.low_bytes[0])) + cols.carry[2] - cols.carry[3] * 256)) === 0
  is_real * (cols.product[4] - (((cols.b_lower_byte.low_bytes[0]) * (cols.c_lower_byte.low_bytes[2]) + ((input.b[0] - cols.b_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) * ((input.c[1] - cols.c_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) + (cols.b_lower_byte.low_bytes[1]) * (cols.c_lower_byte.low_bytes[1]) + ((input.b[1] - cols.b_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) * ((input.c[0] - cols.c_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) + (cols.b_lower_byte.low_bytes[2]) * (cols.c_lower_byte.low_bytes[0])) + cols.carry[3] - cols.carry[4] * 256)) === 0
  is_real * (cols.product[5] - (((cols.b_lower_byte.low_bytes[0]) * ((input.c[2] - cols.c_lower_byte.low_bytes[2]) * (256 : ZMod p)⁻¹) + ((input.b[0] - cols.b_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) * (cols.c_lower_byte.low_bytes[2]) + (cols.b_lower_byte.low_bytes[1]) * ((input.c[1] - cols.c_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) + ((input.b[1] - cols.b_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) * (cols.c_lower_byte.low_bytes[1]) + (cols.b_lower_byte.low_bytes[2]) * ((input.c[0] - cols.c_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) + ((input.b[2] - cols.b_lower_byte.low_bytes[2]) * (256 : ZMod p)⁻¹) * (cols.c_lower_byte.low_bytes[0])) + cols.carry[4] - cols.carry[5] * 256)) === 0
  is_real * (cols.product[6] - (((cols.b_lower_byte.low_bytes[0]) * (cols.c_lower_byte.low_bytes[3]) + ((input.b[0] - cols.b_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) * ((input.c[2] - cols.c_lower_byte.low_bytes[2]) * (256 : ZMod p)⁻¹) + (cols.b_lower_byte.low_bytes[1]) * (cols.c_lower_byte.low_bytes[2]) + ((input.b[1] - cols.b_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) * ((input.c[1] - cols.c_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) + (cols.b_lower_byte.low_bytes[2]) * (cols.c_lower_byte.low_bytes[1]) + ((input.b[2] - cols.b_lower_byte.low_bytes[2]) * (256 : ZMod p)⁻¹) * ((input.c[0] - cols.c_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) + (cols.b_lower_byte.low_bytes[3]) * (cols.c_lower_byte.low_bytes[0])) + cols.carry[5] - cols.carry[6] * 256)) === 0
  is_real * (cols.product[7] - (((cols.b_lower_byte.low_bytes[0]) * ((input.c[3] - cols.c_lower_byte.low_bytes[3]) * (256 : ZMod p)⁻¹) + ((input.b[0] - cols.b_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) * (cols.c_lower_byte.low_bytes[3]) + (cols.b_lower_byte.low_bytes[1]) * ((input.c[2] - cols.c_lower_byte.low_bytes[2]) * (256 : ZMod p)⁻¹) + ((input.b[1] - cols.b_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) * (cols.c_lower_byte.low_bytes[2]) + (cols.b_lower_byte.low_bytes[2]) * ((input.c[1] - cols.c_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) + ((input.b[2] - cols.b_lower_byte.low_bytes[2]) * (256 : ZMod p)⁻¹) * (cols.c_lower_byte.low_bytes[1]) + (cols.b_lower_byte.low_bytes[3]) * ((input.c[0] - cols.c_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) + ((input.b[3] - cols.b_lower_byte.low_bytes[3]) * (256 : ZMod p)⁻¹) * (cols.c_lower_byte.low_bytes[0])) + cols.carry[6] - cols.carry[7] * 256)) === 0
  is_real * (cols.product[8] - (((cols.b_lower_byte.low_bytes[0]) * (cols.c_sign_extend * (255 : ZMod p)) + ((input.b[0] - cols.b_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) * ((input.c[3] - cols.c_lower_byte.low_bytes[3]) * (256 : ZMod p)⁻¹) + (cols.b_lower_byte.low_bytes[1]) * (cols.c_lower_byte.low_bytes[3]) + ((input.b[1] - cols.b_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) * ((input.c[2] - cols.c_lower_byte.low_bytes[2]) * (256 : ZMod p)⁻¹) + (cols.b_lower_byte.low_bytes[2]) * (cols.c_lower_byte.low_bytes[2]) + ((input.b[2] - cols.b_lower_byte.low_bytes[2]) * (256 : ZMod p)⁻¹) * ((input.c[1] - cols.c_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) + (cols.b_lower_byte.low_bytes[3]) * (cols.c_lower_byte.low_bytes[1]) + ((input.b[3] - cols.b_lower_byte.low_bytes[3]) * (256 : ZMod p)⁻¹) * ((input.c[0] - cols.c_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) + (cols.b_sign_extend * (255 : ZMod p)) * (cols.c_lower_byte.low_bytes[0])) + cols.carry[7] - cols.carry[8] * 256)) === 0
  is_real * (cols.product[9] - (((cols.b_lower_byte.low_bytes[0]) * (cols.c_sign_extend * (255 : ZMod p)) + ((input.b[0] - cols.b_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) * (cols.c_sign_extend * (255 : ZMod p)) + (cols.b_lower_byte.low_bytes[1]) * ((input.c[3] - cols.c_lower_byte.low_bytes[3]) * (256 : ZMod p)⁻¹) + ((input.b[1] - cols.b_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) * (cols.c_lower_byte.low_bytes[3]) + (cols.b_lower_byte.low_bytes[2]) * ((input.c[2] - cols.c_lower_byte.low_bytes[2]) * (256 : ZMod p)⁻¹) + ((input.b[2] - cols.b_lower_byte.low_bytes[2]) * (256 : ZMod p)⁻¹) * (cols.c_lower_byte.low_bytes[2]) + (cols.b_lower_byte.low_bytes[3]) * ((input.c[1] - cols.c_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) + ((input.b[3] - cols.b_lower_byte.low_bytes[3]) * (256 : ZMod p)⁻¹) * (cols.c_lower_byte.low_bytes[1]) + (cols.b_sign_extend * (255 : ZMod p)) * ((input.c[0] - cols.c_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) + (cols.b_sign_extend * (255 : ZMod p)) * (cols.c_lower_byte.low_bytes[0])) + cols.carry[8] - cols.carry[9] * 256)) === 0
  is_real * (cols.product[10] - (((cols.b_lower_byte.low_bytes[0]) * (cols.c_sign_extend * (255 : ZMod p)) + ((input.b[0] - cols.b_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) * (cols.c_sign_extend * (255 : ZMod p)) + (cols.b_lower_byte.low_bytes[1]) * (cols.c_sign_extend * (255 : ZMod p)) + ((input.b[1] - cols.b_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) * ((input.c[3] - cols.c_lower_byte.low_bytes[3]) * (256 : ZMod p)⁻¹) + (cols.b_lower_byte.low_bytes[2]) * (cols.c_lower_byte.low_bytes[3]) + ((input.b[2] - cols.b_lower_byte.low_bytes[2]) * (256 : ZMod p)⁻¹) * ((input.c[2] - cols.c_lower_byte.low_bytes[2]) * (256 : ZMod p)⁻¹) + (cols.b_lower_byte.low_bytes[3]) * (cols.c_lower_byte.low_bytes[2]) + ((input.b[3] - cols.b_lower_byte.low_bytes[3]) * (256 : ZMod p)⁻¹) * ((input.c[1] - cols.c_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) + (cols.b_sign_extend * (255 : ZMod p)) * (cols.c_lower_byte.low_bytes[1]) + (cols.b_sign_extend * (255 : ZMod p)) * ((input.c[0] - cols.c_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) + (cols.b_sign_extend * (255 : ZMod p)) * (cols.c_lower_byte.low_bytes[0])) + cols.carry[9] - cols.carry[10] * 256)) === 0
  is_real * (cols.product[11] - (((cols.b_lower_byte.low_bytes[0]) * (cols.c_sign_extend * (255 : ZMod p)) + ((input.b[0] - cols.b_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) * (cols.c_sign_extend * (255 : ZMod p)) + (cols.b_lower_byte.low_bytes[1]) * (cols.c_sign_extend * (255 : ZMod p)) + ((input.b[1] - cols.b_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) * (cols.c_sign_extend * (255 : ZMod p)) + (cols.b_lower_byte.low_bytes[2]) * ((input.c[3] - cols.c_lower_byte.low_bytes[3]) * (256 : ZMod p)⁻¹) + ((input.b[2] - cols.b_lower_byte.low_bytes[2]) * (256 : ZMod p)⁻¹) * (cols.c_lower_byte.low_bytes[3]) + (cols.b_lower_byte.low_bytes[3]) * ((input.c[2] - cols.c_lower_byte.low_bytes[2]) * (256 : ZMod p)⁻¹) + ((input.b[3] - cols.b_lower_byte.low_bytes[3]) * (256 : ZMod p)⁻¹) * (cols.c_lower_byte.low_bytes[2]) + (cols.b_sign_extend * (255 : ZMod p)) * ((input.c[1] - cols.c_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) + (cols.b_sign_extend * (255 : ZMod p)) * (cols.c_lower_byte.low_bytes[1]) + (cols.b_sign_extend * (255 : ZMod p)) * ((input.c[0] - cols.c_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) + (cols.b_sign_extend * (255 : ZMod p)) * (cols.c_lower_byte.low_bytes[0])) + cols.carry[10] - cols.carry[11] * 256)) === 0
  is_real * (cols.product[12] - (((cols.b_lower_byte.low_bytes[0]) * (cols.c_sign_extend * (255 : ZMod p)) + ((input.b[0] - cols.b_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) * (cols.c_sign_extend * (255 : ZMod p)) + (cols.b_lower_byte.low_bytes[1]) * (cols.c_sign_extend * (255 : ZMod p)) + ((input.b[1] - cols.b_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) * (cols.c_sign_extend * (255 : ZMod p)) + (cols.b_lower_byte.low_bytes[2]) * (cols.c_sign_extend * (255 : ZMod p)) + ((input.b[2] - cols.b_lower_byte.low_bytes[2]) * (256 : ZMod p)⁻¹) * ((input.c[3] - cols.c_lower_byte.low_bytes[3]) * (256 : ZMod p)⁻¹) + (cols.b_lower_byte.low_bytes[3]) * (cols.c_lower_byte.low_bytes[3]) + ((input.b[3] - cols.b_lower_byte.low_bytes[3]) * (256 : ZMod p)⁻¹) * ((input.c[2] - cols.c_lower_byte.low_bytes[2]) * (256 : ZMod p)⁻¹) + (cols.b_sign_extend * (255 : ZMod p)) * (cols.c_lower_byte.low_bytes[2]) + (cols.b_sign_extend * (255 : ZMod p)) * ((input.c[1] - cols.c_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) + (cols.b_sign_extend * (255 : ZMod p)) * (cols.c_lower_byte.low_bytes[1]) + (cols.b_sign_extend * (255 : ZMod p)) * ((input.c[0] - cols.c_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) + (cols.b_sign_extend * (255 : ZMod p)) * (cols.c_lower_byte.low_bytes[0])) + cols.carry[11] - cols.carry[12] * 256)) === 0
  is_real * (cols.product[13] - (((cols.b_lower_byte.low_bytes[0]) * (cols.c_sign_extend * (255 : ZMod p)) + ((input.b[0] - cols.b_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) * (cols.c_sign_extend * (255 : ZMod p)) + (cols.b_lower_byte.low_bytes[1]) * (cols.c_sign_extend * (255 : ZMod p)) + ((input.b[1] - cols.b_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) * (cols.c_sign_extend * (255 : ZMod p)) + (cols.b_lower_byte.low_bytes[2]) * (cols.c_sign_extend * (255 : ZMod p)) + ((input.b[2] - cols.b_lower_byte.low_bytes[2]) * (256 : ZMod p)⁻¹) * (cols.c_sign_extend * (255 : ZMod p)) + (cols.b_lower_byte.low_bytes[3]) * ((input.c[3] - cols.c_lower_byte.low_bytes[3]) * (256 : ZMod p)⁻¹) + ((input.b[3] - cols.b_lower_byte.low_bytes[3]) * (256 : ZMod p)⁻¹) * (cols.c_lower_byte.low_bytes[3]) + (cols.b_sign_extend * (255 : ZMod p)) * ((input.c[2] - cols.c_lower_byte.low_bytes[2]) * (256 : ZMod p)⁻¹) + (cols.b_sign_extend * (255 : ZMod p)) * (cols.c_lower_byte.low_bytes[2]) + (cols.b_sign_extend * (255 : ZMod p)) * ((input.c[1] - cols.c_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) + (cols.b_sign_extend * (255 : ZMod p)) * (cols.c_lower_byte.low_bytes[1]) + (cols.b_sign_extend * (255 : ZMod p)) * ((input.c[0] - cols.c_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) + (cols.b_sign_extend * (255 : ZMod p)) * (cols.c_lower_byte.low_bytes[0])) + cols.carry[12] - cols.carry[13] * 256)) === 0
  is_real * (cols.product[14] - (((cols.b_lower_byte.low_bytes[0]) * (cols.c_sign_extend * (255 : ZMod p)) + ((input.b[0] - cols.b_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) * (cols.c_sign_extend * (255 : ZMod p)) + (cols.b_lower_byte.low_bytes[1]) * (cols.c_sign_extend * (255 : ZMod p)) + ((input.b[1] - cols.b_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) * (cols.c_sign_extend * (255 : ZMod p)) + (cols.b_lower_byte.low_bytes[2]) * (cols.c_sign_extend * (255 : ZMod p)) + ((input.b[2] - cols.b_lower_byte.low_bytes[2]) * (256 : ZMod p)⁻¹) * (cols.c_sign_extend * (255 : ZMod p)) + (cols.b_lower_byte.low_bytes[3]) * (cols.c_sign_extend * (255 : ZMod p)) + ((input.b[3] - cols.b_lower_byte.low_bytes[3]) * (256 : ZMod p)⁻¹) * ((input.c[3] - cols.c_lower_byte.low_bytes[3]) * (256 : ZMod p)⁻¹) + (cols.b_sign_extend * (255 : ZMod p)) * (cols.c_lower_byte.low_bytes[3]) + (cols.b_sign_extend * (255 : ZMod p)) * ((input.c[2] - cols.c_lower_byte.low_bytes[2]) * (256 : ZMod p)⁻¹) + (cols.b_sign_extend * (255 : ZMod p)) * (cols.c_lower_byte.low_bytes[2]) + (cols.b_sign_extend * (255 : ZMod p)) * ((input.c[1] - cols.c_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) + (cols.b_sign_extend * (255 : ZMod p)) * (cols.c_lower_byte.low_bytes[1]) + (cols.b_sign_extend * (255 : ZMod p)) * ((input.c[0] - cols.c_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) + (cols.b_sign_extend * (255 : ZMod p)) * (cols.c_lower_byte.low_bytes[0])) + cols.carry[13] - cols.carry[14] * 256)) === 0
  is_real * (cols.product[15] - (((cols.b_lower_byte.low_bytes[0]) * (cols.c_sign_extend * (255 : ZMod p)) + ((input.b[0] - cols.b_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) * (cols.c_sign_extend * (255 : ZMod p)) + (cols.b_lower_byte.low_bytes[1]) * (cols.c_sign_extend * (255 : ZMod p)) + ((input.b[1] - cols.b_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) * (cols.c_sign_extend * (255 : ZMod p)) + (cols.b_lower_byte.low_bytes[2]) * (cols.c_sign_extend * (255 : ZMod p)) + ((input.b[2] - cols.b_lower_byte.low_bytes[2]) * (256 : ZMod p)⁻¹) * (cols.c_sign_extend * (255 : ZMod p)) + (cols.b_lower_byte.low_bytes[3]) * (cols.c_sign_extend * (255 : ZMod p)) + ((input.b[3] - cols.b_lower_byte.low_bytes[3]) * (256 : ZMod p)⁻¹) * (cols.c_sign_extend * (255 : ZMod p)) + (cols.b_sign_extend * (255 : ZMod p)) * ((input.c[3] - cols.c_lower_byte.low_bytes[3]) * (256 : ZMod p)⁻¹) + (cols.b_sign_extend * (255 : ZMod p)) * (cols.c_lower_byte.low_bytes[3]) + (cols.b_sign_extend * (255 : ZMod p)) * ((input.c[2] - cols.c_lower_byte.low_bytes[2]) * (256 : ZMod p)⁻¹) + (cols.b_sign_extend * (255 : ZMod p)) * (cols.c_lower_byte.low_bytes[2]) + (cols.b_sign_extend * (255 : ZMod p)) * ((input.c[1] - cols.c_lower_byte.low_bytes[1]) * (256 : ZMod p)⁻¹) + (cols.b_sign_extend * (255 : ZMod p)) * (cols.c_lower_byte.low_bytes[1]) + (cols.b_sign_extend * (255 : ZMod p)) * ((input.c[0] - cols.c_lower_byte.low_bytes[0]) * (256 : ZMod p)⁻¹) + (cols.b_sign_extend * (255 : ZMod p)) * (cols.c_lower_byte.low_bytes[0])) + cols.carry[14] - cols.carry[15] * 256)) === 0

instance elaborated : ElaboratedCircuit (ZMod p) Inputs unit main := by
  elaborate_circuit_with {
    channelsWithGuarantees := [byteChannel.toRaw]
  }

set_option linter.unusedSectionVars false in
@[circuit_norm] lemma channelsWithGuarantees_eq :
    ((elaborated (p := p)).channelsWithGuarantees : List (RawChannel (ZMod p)))
      = [byteChannel.toRaw] := by
  rfl
set_option linter.unusedSectionVars false in
@[circuit_norm] lemma localLength_eq (x : Var Inputs (ZMod p)) :
    (elaborated (p := p)).localLength x = 0 := by
  rfl


end SP1Clean.MulOperation
