import SP1CleanTest.NonVacuityReal
import SP1CleanTest.Audit.OneAddNativePremises

/-! Auto-generated by `scripts/gen_axiom_probe.py` — do not edit by hand.
Test-library census probe (the `SP1CleanTest` conformance anchors; requires the
test-library oleans — run `lake test` first).
Run via `lake env lean scripts/axiom_probe_test.lean` (see `scripts/run_audit.sh`). -/

#print axioms SP1Clean.NonVacuityRealTests.constraintsHold_of_check
#print axioms SP1Clean.NonVacuityRealTests.rTypeEventInputs_is_real
#print axioms SP1Clean.NonVacuityRealTests.aluTypeEventInputs_is_real
#print axioms SP1Clean.NonVacuityRealTests.lt_slt_true_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.lt_slt_false_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.lt_slt_true_bit
#print axioms SP1Clean.NonVacuityRealTests.lt_slt_false_bit
#print axioms SP1Clean.NonVacuityRealTests.bitwise_and_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.bitwise_xor_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.utype_lui_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.utype_auipc_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.jalr_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.loadword_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.loadbyte_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.loadhalf_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.loaddouble_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.loadx0_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.addi_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.divrem_divu_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.shiftleft_sll_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.shiftright_srl_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.add_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.sub_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.addw_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.subw_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.mul_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.branch_beq_taken_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.jal_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.storeword_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.storehalf_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.storebyte_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.storedouble_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.alux0_real_row_satisfiable
#print axioms SP1Clean.NonVacuityRealTests.constraint_systems_nonempty
#print axioms SP1Clean.Audit.OneAddNativePremises.constraints_hold
#print axioms SP1Clean.Audit.OneAddNativePremises.interactions_exact
#print axioms SP1Clean.Audit.OneAddNativePremises.program_projection
