#!/usr/bin/env bash
# The reproducible audit harness behind `docs/release-audit.md` / `docs/snapshots/axiom-ledger.md`.
#
# Runs, in order: (A0) pin record, (A2) sorry/axiom text inventory with gates, (A3) the
# authoritative `#print axioms` census over the released theorem set (via
# `scripts/gen_axiom_probe.py` → `scripts/axiom_probe.lean`), writing the raw census to
# `docs/snapshots/axiom-census.txt` and gating that `sorryAx` is reachable only from the
# known-debt set. Run on a green tree (`lake build SP1Clean` first). Exit 0 = all gates pass.
#
# Usage: scripts/run_audit.sh   (from the repo root; ~3-5 min, dominated by the probe run)

set -uo pipefail
cd "$(dirname "$0")/.."
fail=0

echo "== A0 pins =="
echo "sp1-lean:  $(git rev-parse HEAD)"
echo "toolchain: $(cat lean-toolchain)"
SP1_DIR="${SP1_DIR:-../sp1}"
echo "sp1:       $(git -C "$SP1_DIR" rev-parse HEAD) ($(git -C "$SP1_DIR" describe --tags 2>/dev/null), branch $(git -C "$SP1_DIR" branch --show-current))"
echo "Clean:     $(git -C .lake/packages/Clean rev-parse HEAD 2>/dev/null || echo '<missing>')"
echo "LeanRV64D: $(git -C .lake/packages/LeanRV64D rev-parse HEAD 2>/dev/null || echo '<missing>')"

echo
echo "== A2 sorry inventory (gate: exactly the known-debt set) =="
# The known direct `sorry` proof-holes. Update this list (and the docs) when one is closed.
expected_sorries="SP1Clean/Soundness/SP1GatedVm.lean"
sorry_re='(^[[:space:]]*sorry[[:space:]]*$)|(:=[[:space:]]*sorry)|(=>[[:space:]]*sorry)'
actual=$(grep -rlE "$sorry_re" SP1Clean --include='*.lean' | sort)
grep -rnE "$sorry_re" SP1Clean --include='*.lean'
if [ "$actual" = "$(echo "$expected_sorries" | sort)" ]; then
  echo "PASS: sorry files = expected 1"
else
  echo "FAIL: sorry inventory drifted from the documented set"; fail=1
fi

echo
echo "== A2 axiom declarations (gate: none in SP1Clean/) =="
if grep -rnE '^[[:space:]]*axiom[[:space:]]' SP1Clean --include='*.lean'; then
  echo "FAIL: unexpected axiom declaration(s) above"; fail=1
else
  echo "PASS: no axiom declarations"
fi
echo "native_decide occurrences (disclosed, witness battery + Sail memory bridges):"
grep -rn 'native_decide' SP1Clean --include='*.lean' | wc -l

echo
echo "== A3 axiom census (the authoritative oracle) =="
python3 scripts/gen_axiom_probe.py || { echo "FAIL: probe generation"; exit 1; }
census=docs/snapshots/axiom-census.txt
{
  echo "# Raw #print axioms census — generated by scripts/run_audit.sh"
  echo "# sp1-lean $(git rev-parse HEAD) · $(date -u +%Y-%m-%d)"
  lake env lean scripts/axiom_probe.lean
} > "$census" 2>&1
if grep -q "error" "$census"; then
  echo "FAIL: probe elaboration errors:"; grep "error" "$census"; fail=1
fi

python3 - "$census" <<'EOF' || fail=1
import re, sys
text = open(sys.argv[1]).read()
entries = re.findall(r"'([\w.]+)' (?:depends on axioms: \[([^\]]*)\]|does not depend on any axioms)", text, re.S)
print(f"census entries: {len(entries)}")
# Declarations allowed to (transitively) carry sorryAx: the DivRem completeness hole, the
# decode seam `sp1_witness_decode` (the sorried W1b/W1c premise; `sp1_gatedExecution_prereqs`
# is now a proven assembly that consumes it), and the capstone chain that embeds them
# (sp1Tables bundles the chip `circuit` structures whose completeness fields are sorried;
# the soundness proofs never consume those fields, but #print axioms is structural and
# cannot see that).
allowed = {
    "SP1Clean.DivRemChip.completeness",
    "SP1Clean.Soundness.sp1_witness_decode",
    "SP1Clean.Soundness.sp1_gatedExecution_prereqs",
    "SP1Clean.Soundness.sp1Tables", "SP1Clean.Soundness.sp1Tables_length",
    "SP1Clean.Soundness.sp1GatedVm",
    "SP1Clean.Soundness.sp1FormalEnsemble", "SP1Clean.Soundness.sp1_machine_soundness",
    "SP1Clean.Soundness.Target.sp1_target_soundness",
}
bad = [f for f, axs in entries if "sorryAx" in axs and f not in allowed]
buckets = {}
for fqn, axs in entries:
    key = frozenset(a.strip() for a in axs.split(",") if a.strip())
    buckets.setdefault(key, []).append(fqn)
print("bucket sizes:")
for key, fqns in sorted(buckets.items(), key=lambda kv: -len(kv[1])):
    print(f"  [{len(fqns):3}] {{{', '.join(sorted(key))}}}")
if bad:
    print("FAIL: unexpected sorryAx carriers:", *bad, sep="\n  "); sys.exit(1)
print(f"PASS: sorryAx confined to the known-debt set "
      f"({sum(1 for f, a in entries if 'sorryAx' in a)} carriers, all allowed)")
EOF

echo
[ "$fail" -eq 0 ] && echo "== AUDIT PASS ==" || echo "== AUDIT FAIL =="
exit "$fail"
