#!/usr/bin/env bash
# The reproducible audit harness behind `docs/release-audit.md` / `docs/snapshots/axiom-ledger.md`.
#
# Runs, in order: (A0) pin record, (A2) sorry/axiom text inventory with gates, (A3) the
# authoritative `#print axioms` census over the released theorem set (via
# `scripts/gen_axiom_probe.py` → `scripts/axiom_probe.lean`), writing the raw census to
# `docs/snapshots/axiom-census.txt` and gating that `sorryAx` is reachable only from the
# known-debt set. Run on a green tree (`lake build SP1Clean` first). Exit 0 = all gates pass.
#
# Usage: scripts/run_audit.sh   (from the repo root; ~3-5 min, dominated by the probe run)

set -uo pipefail
cd "$(dirname "$0")/.."
fail=0

echo "== A0 pins =="
echo "sp1-lean:  $(git rev-parse HEAD)"
echo "toolchain: $(cat lean-toolchain)"
SP1_DIR="${SP1_DIR:-../sp1}"
echo "sp1:       $(git -C "$SP1_DIR" rev-parse HEAD) ($(git -C "$SP1_DIR" describe --tags 2>/dev/null), branch $(git -C "$SP1_DIR" branch --show-current))"
echo "Clean:     $(git -C .lake/packages/Clean rev-parse HEAD 2>/dev/null || echo '<missing>')"
echo "LeanRV64D: $(git -C .lake/packages/LeanRV64D rev-parse HEAD 2>/dev/null || echo '<missing>')"

echo
echo "== A2 proof-deferral inventory (gate: exactly the known-debt set) =="
# The known direct proof-holes — both `sorry` and start-of-proof `stop` (`stop` discards the
# following tactic block and closes via `sorryAx`, so it is a deferral just like `sorry` and must
# be tracked here). Update this list (and the docs) when one is closed.
#   · SP1Ensemble        — `sp1_witness_decode` (the long-known W1b/W1c decode seam)
#   · MulChip/Formal      — completeness (Clean-4.30 nativeValue/combinedSize' blowup)
#   · DivRemChip/Completeness/Driver — completeness (same blowup; `stop`)
#   · DivRemChip/Soundness/{Reader,Div,Divu,Divw,Divuw,Rem,Remu,Remw,Remuw} — MIGRATION-DEFERRED
#     SOUNDNESS: the 4.30 whnf-timeout regression (see docs/proposals/consolidation-progress.md,
#     2026-07-11 session). `stop`-stubbed; RESTORE before the consolidation PR.
expected_sorries="$(cat <<'LIST'
SP1Clean/Proofs/Chips/DivRemChip/Completeness/Driver.lean
SP1Clean/Proofs/Chips/DivRemChip/Soundness/Div.lean
SP1Clean/Proofs/Chips/DivRemChip/Soundness/Divu.lean
SP1Clean/Proofs/Chips/DivRemChip/Soundness/Divuw.lean
SP1Clean/Proofs/Chips/DivRemChip/Soundness/Divw.lean
SP1Clean/Proofs/Chips/DivRemChip/Soundness/Reader.lean
SP1Clean/Proofs/Chips/DivRemChip/Soundness/Rem.lean
SP1Clean/Proofs/Chips/DivRemChip/Soundness/Remu.lean
SP1Clean/Proofs/Chips/DivRemChip/Soundness/Remuw.lean
SP1Clean/Proofs/Chips/DivRemChip/Soundness/Remw.lean
SP1Clean/Proofs/Chips/MulChip/Formal.lean
SP1Clean/Soundness/SP1Ensemble.lean
LIST
)"
sorry_re='(^[[:space:]]*sorry[[:space:]]*$)|(:=[[:space:]]*sorry)|(=>[[:space:]]*sorry)|(^[[:space:]]*stop([[:space:]]|$))'
actual=$(grep -rlE "$sorry_re" SP1Clean --include='*.lean' | sort)
grep -rnE "$sorry_re" SP1Clean --include='*.lean'
n_exp=$(echo "$expected_sorries" | grep -c .)
if [ "$actual" = "$(echo "$expected_sorries" | sort)" ]; then
  echo "PASS: proof-deferral files = expected $n_exp (2 completeness + 9 DivRem-soundness stop + witness_decode)"
else
  echo "FAIL: proof-deferral inventory drifted from the documented set"; fail=1
fi

echo
echo "== A2 axiom declarations (gate: none in SP1Clean/) =="
if grep -rnE '^[[:space:]]*axiom[[:space:]]' SP1Clean --include='*.lean'; then
  echo "FAIL: unexpected axiom declaration(s) above"; fail=1
else
  echo "PASS: no axiom declarations"
fi

echo
echo "== A2 skipKernelTC guard (gate: none in SP1Clean/) =="
if scripts/check_no_skipkerneltc.sh; then
  echo "PASS: no skipKernelTC usage"
else
  echo "FAIL: skipKernelTC reintroduced (see above)"; fail=1
fi

echo
echo "== A2 native_decide guard (gate: none in SP1Clean/) =="
if scripts/check_no_native_decide.sh; then
  echo "PASS: no native_decide in the main library"
else
  echo "FAIL: native_decide in SP1Clean/ (see above)"; fail=1
fi
echo "native_decide occurrences in SP1CleanTest/ (disclosed — the witness/trace conformance battery,"
echo "the sole sanctioned native_decide; adds Lean.ofReduceBool/trustCompiler, confined off the main library):"
grep -rn 'native_decide' SP1CleanTest --include='*.lean' | wc -l

echo
echo "== A3 axiom census (the authoritative oracle) =="
python3 scripts/gen_axiom_probe.py || { echo "FAIL: probe generation"; exit 1; }
census=docs/snapshots/axiom-census.txt
{
  echo "# Raw #print axioms census — generated by scripts/run_audit.sh"
  echo "# sp1-lean $(git rev-parse HEAD) · $(date -u +%Y-%m-%d)"
  lake env lean scripts/axiom_probe.lean
} > "$census" 2>&1
if grep -q "error" "$census"; then
  echo "FAIL: probe elaboration errors:"; grep "error" "$census"; fail=1
fi

python3 - "$census" <<'EOF' || fail=1
import re, sys
text = open(sys.argv[1]).read()
entries = re.findall(r"'([\w.]+)' (?:depends on axioms: \[([^\]]*)\]|does not depend on any axioms)", text, re.S)
print(f"census entries: {len(entries)}")
# Declarations allowed to (transitively) carry sorryAx: the DivRem completeness hole, the
# decode seam `sp1_witness_decode` (the sorried W1b/W1c premise; `sp1_gatedExecution_prereqs`
# is now a proven assembly that consumes it), and the capstone chain that embeds them
# (sp1Tables bundles the chip `circuit` structures whose completeness fields are sorried;
# the soundness proofs never consume those fields, but #print axioms is structural and
# cannot see that).
#
# *** MIGRATION-DEFERRED SOUNDNESS (Lean 4.30, 2026-07-11 — TEMPORARY, restore before consolidation
# PR). *** The 9 DivRem per-variant `soundness` sub-lemmas hit a 4.30 `whnf`-timeout regression and
# are `stop`-stubbed (docs/proposals/consolidation-progress.md). Unlike the completeness/decode
# holes, this is a *soundness* gap: `SP1Clean.DivRemChip.soundness` and hence the capstone now
# inherit sorryAx through the DivRem chip's soundness, not only its completeness. Disclosed here and
# in the docs; the DivRem chip's Sail-bridge + faithfulness are unaffected.
allowed = {
    "SP1Clean.DivRemChip.completeness",
    # DivRem soundness deferral (4.30 whnf regression) — the 9 sub-lemmas + the top-level roll-up + GFC bundle:
    "SP1Clean.DivRemChip.SoundReader.soundness", "SP1Clean.DivRemChip.SoundDiv.soundness",
    "SP1Clean.DivRemChip.SoundDivu.soundness", "SP1Clean.DivRemChip.SoundDivw.soundness",
    "SP1Clean.DivRemChip.SoundDivuw.soundness", "SP1Clean.DivRemChip.SoundRem.soundness",
    "SP1Clean.DivRemChip.SoundRemu.soundness", "SP1Clean.DivRemChip.SoundRemw.soundness",
    "SP1Clean.DivRemChip.SoundRemuw.soundness",
    "SP1Clean.DivRemChip.soundness", "SP1Clean.DivRemChip.circuit",
    "SP1Clean.Soundness.sp1_witness_decode",
    "SP1Clean.Soundness.sp1_gatedExecution_prereqs",
    "SP1Clean.Soundness.sp1Tables", "SP1Clean.Soundness.sp1Tables_length",
    "SP1Clean.Soundness.sp1Ensemble", "SP1Clean.Soundness.sp1ProviderTables",
    "SP1Clean.Soundness.sp1ProviderTables_length",
    "SP1Clean.Soundness.sp1FormalEnsemble", "SP1Clean.Soundness.sp1_machine_soundness",
    "SP1Clean.Soundness.Target.sp1_target_soundness",
}
bad = [f for f, axs in entries if "sorryAx" in axs and f not in allowed]
buckets = {}
for fqn, axs in entries:
    key = frozenset(a.strip() for a in axs.split(",") if a.strip())
    buckets.setdefault(key, []).append(fqn)
print("bucket sizes:")
for key, fqns in sorted(buckets.items(), key=lambda kv: -len(kv[1])):
    print(f"  [{len(fqns):3}] {{{', '.join(sorted(key))}}}")
if bad:
    print("FAIL: unexpected sorryAx carriers:", *bad, sep="\n  "); sys.exit(1)
print(f"PASS: sorryAx confined to the known-debt set "
      f"({sum(1 for f, a in entries if 'sorryAx' in a)} carriers, all allowed)")
EOF

echo
[ "$fail" -eq 0 ] && echo "== AUDIT PASS ==" || echo "== AUDIT FAIL =="
exit "$fail"
