#!/usr/bin/env bash
# The reproducible audit harness behind `docs/release-audit.md` / `docs/snapshots/axiom-ledger.md`.
#
# Runs, in order: (A0) pin record, (A2) sorry/axiom text inventory with gates, (A3) the
# authoritative `#print axioms` census over the released theorem set (via
# `scripts/gen_axiom_probe.py` → `scripts/axiom_probe.lean`), writing the raw census to
# `docs/snapshots/axiom-census.txt` and gating that no released declaration carries `sorryAx`.
# Run on a green tree (`lake build SP1Clean` first). Exit 0 = all gates pass.
#
# Usage: scripts/run_audit.sh   (from the repo root; ~3-5 min, dominated by the probe run)

set -uo pipefail
cd "$(dirname "$0")/.."
fail=0

echo "== A0 pins =="
echo "sp1-lean:  $(git rev-parse HEAD)"
echo "toolchain: $(cat lean-toolchain)"
SP1_DIR="${SP1_DIR:-../sp1}"
echo "sp1:       $(git -C "$SP1_DIR" rev-parse HEAD) ($(git -C "$SP1_DIR" describe --tags 2>/dev/null), branch $(git -C "$SP1_DIR" branch --show-current))"
CLEAN_DIR="${CLEAN_DIR:-../clean}"
SAIL_RISCV_DIR="${SAIL_RISCV_DIR:-../sail-riscv-lean}"
RISCV_DIR="${RISCV_DIR:-../riscv-lean}"
LEAN_SAIL_DIR="${LEAN_SAIL_DIR:-../lean-sail}"
echo "Clean:     $(git -C "$CLEAN_DIR" rev-parse HEAD 2>/dev/null || echo '<missing>')"
echo "LeanRV64D: $(git -C "$SAIL_RISCV_DIR" rev-parse HEAD 2>/dev/null || echo '<missing>')"
echo "RISCV:     $(git -C "$RISCV_DIR" rev-parse HEAD 2>/dev/null || echo '<missing>')"
echo "Sail:      $(git -C "$LEAN_SAIL_DIR" rev-parse HEAD 2>/dev/null || echo '<missing>')"
echo "PolyFun:   $(git -C .lake/packages/PolyFun rev-parse HEAD 2>/dev/null || echo '<missing>')"

echo
echo "== A2 proof-deferral inventory (gate: none) =="
# Both `sorry` and start-of-proof `stop` introduce `sorryAx`; neither is permitted in the main
# library. Conditional theorem hypotheses and relation parameters are audited at the statement
# boundary instead of being disguised as proof deferrals.
sorry_re='(^[[:space:]]*sorry[[:space:]]*$)|(:=[[:space:]]*sorry)|(=>[[:space:]]*sorry)|(^[[:space:]]*stop([[:space:]]|$))'
actual=$(grep -rlE "$sorry_re" SP1Clean --include='*.lean' | sort)
grep -rnE "$sorry_re" SP1Clean --include='*.lean'
if [ -z "$actual" ]; then
  echo "PASS: no proof deferrals"
else
  echo "FAIL: proof deferral(s) found"; fail=1
fi

echo
echo "== A2 axiom declarations (gate: none in SP1Clean/) =="
if grep -rnE '^[[:space:]]*axiom[[:space:]]' SP1Clean --include='*.lean'; then
  echo "FAIL: unexpected axiom declaration(s) above"; fail=1
else
  echo "PASS: no axiom declarations"
fi

echo
echo "== A2 skipKernelTC guard (gate: none in SP1Clean/) =="
if scripts/check_no_skipkerneltc.sh; then
  echo "PASS: no skipKernelTC usage"
else
  echo "FAIL: skipKernelTC reintroduced (see above)"; fail=1
fi

echo
echo "== A2 native_decide guard (gate: none in SP1Clean/) =="
if scripts/check_no_native_decide.sh; then
  echo "PASS: no native_decide in the main library"
else
  echo "FAIL: native_decide in SP1Clean/ (see above)"; fail=1
fi
echo "native_decide occurrences in SP1CleanTest/ (disclosed — the witness/trace conformance battery,"
echo "the sole sanctioned native_decide; adds Lean.ofReduceBool/trustCompiler, confined off the main library):"
grep -rn 'native_decide' SP1CleanTest --include='*.lean' | wc -l

echo
echo "== A2 maxHeartbeats no-increase guard (fold blowups, don't bump ceilings) =="
if scripts/check_heartbeats.sh; then
  echo "PASS: maxHeartbeats override count at/below baseline"
else
  echo "FAIL: maxHeartbeats overrides increased — fold instead of bumping (see above)"; fail=1
fi

echo
echo "== A3 axiom census (the authoritative oracle) =="
python3 scripts/gen_axiom_probe.py || { echo "FAIL: probe generation"; exit 1; }
census=docs/snapshots/axiom-census.txt
{
  echo "# Raw #print axioms census — generated by scripts/run_audit.sh"
  echo "# sp1-lean $(git rev-parse HEAD) · $(date -u +%Y-%m-%d)"
  lake env lean scripts/axiom_probe.lean
} > "$census" 2>&1
if grep -q "error" "$census"; then
  echo "FAIL: probe elaboration errors:"; grep "error" "$census"; fail=1
fi

python3 - "$census" <<'EOF' || fail=1
import re, sys
text = open(sys.argv[1]).read()
entries = re.findall(r"'([^']+)' (?:depends on axioms: \[([^\]]*)\]|does not depend on any axioms)", text, re.S)
print(f"census entries: {len(entries)}")
expected = sum(
    1 for line in open("scripts/axiom_probe.lean")
    if line.startswith("#print axioms ")
)
if len(entries) != expected:
    print(f"FAIL: parsed {len(entries)} census entries for {expected} generated probes")
    sys.exit(1)
allowed = set()
bad = [f for f, axs in entries if "sorryAx" in axs and f not in allowed]
buckets = {}
for fqn, axs in entries:
    key = frozenset(a.strip() for a in axs.split(",") if a.strip())
    buckets.setdefault(key, []).append(fqn)
print("bucket sizes:")
for key, fqns in sorted(buckets.items(), key=lambda kv: -len(kv[1])):
    print(f"  [{len(fqns):3}] {{{', '.join(sorted(key))}}}")
if bad:
    print("FAIL: unexpected sorryAx carriers:", *bad, sep="\n  "); sys.exit(1)
count = sum(1 for _, axioms in entries if "sorryAx" in axioms)
if count:
    print(f"FAIL: {count} probed declaration(s) still carry sorryAx"); sys.exit(1)
main_compiler_trust = [
    fqn for fqn, axioms in entries
    if ("native_decide" in axioms or "Lean.ofReduceBool" in axioms or
        "Lean.trustCompiler" in axioms)
    and not (fqn.startswith("SP1Clean.WitnessTests.") or
             fqn.startswith("SP1Clean.TraceGenTests."))
]
if main_compiler_trust:
    print("FAIL: compiler-trusted proof escaped the test library:",
          *main_compiler_trust, sep="\n  ")
    sys.exit(1)
print("PASS: no probed declaration carries sorryAx")
print("PASS: compiler-trusted proof constants are confined to SP1CleanTest")
EOF

echo
[ "$fail" -eq 0 ] && echo "== AUDIT PASS ==" || echo "== AUDIT FAIL =="
exit "$fail"
