import SP1Clean.Model.SailWrap
import SP1Clean.Math.Word

set_option linter.style.longLine false
set_option linter.unusedSimpArgs false

namespace SP1Clean.SailMem

open LeanRV64D.Functions Sail SailState

set_option linter.style.setOption false
-- Sail-bridge `simp` and `run_*` lemmas unfold deep `SailM` monadic programs.
set_option maxHeartbeats 10000000

-- Helper functions generated by sail that we generally don't want in practice
attribute [simp] bit_to_bool bits_of_virtaddr bool_bit_backwards Sail.BitVec.access
  ext_control_check_pc currentlyEnabled Sail.BitVec.signExtend

attribute [local simp]
  regidxToRegister_inj
  nextPC_ne_reg_idx_toRegister
  PC_ne_reg_idx_toRegister
  encdec_reg_forwards_matches
  Sail.readReg
  PreSail.readReg
  Std.ExtDHashMap.get?_insert
  Std.ExtDHashMap.get?_insert_self
  Sail.BitVec.toNatInt

attribute [local simp] LeanRV64D.Functions.xlen_bytes Sail.assert PreSail.assert
  ext_data_get_addr
  split_misaligned misaligned_order
  allowed_misaligned sys_misaligned_order_decreasing
  LeanRV64D.Functions.xlen
  _get_Mstatus_MPP _get_Mstatus_MPRV
  effectivePrivilege
  zopz0zI_u zopz0zK_u
  htif_tohost_size
  LeanRV64D.Functions.not

section isValidMemConfig

/-- `plat_have_clint` is manually set in our fork of sail in the `PlatformConfig.lean` file. -/
@[simp] lemma plat_have_clint_eq_false : plat_have_clint = false := rfl

/-- `plat_have_sig` is manually set in our fork of sail in the `PlatformConfig.lean` file. -/
@[simp] lemma plat_have_sig_eq_false : plat_have_sig = false := rfl

/-- `sys_pmp_count` is manually set to zero in our fork in the `PmpRegs.lean` file. -/
@[simp] lemma sys_pmp_count_eq_zero : sys_pmp_count = 0 := rfl

/-- Memory access setting for all of memory in our model. -/
@[reducible]
def SP1_PMA : PMA where
  mem_type := MemoryRegionType.MainMemory
  cacheable := false
  coherent := true
  executable := true
  readable := true
  writable := true
  read_idempotent := false
  write_idempotent := false
  misaligned_exceptions := {
    load_store := none
    vector := none
    amo := .AlignmentException
  }
  atomic_support := AtomicSupport.AMONone
  reservability := Reservability.RsrvNone
  supports_cbo_zero := false
  supports_pte_read := false
  supports_pte_write := false

/-- Single memory region with uniform access across all memory. -/
@[reducible]
def SP1_PMA_Region : PMA_Region where
  base := 2 ^ 16
  size := 2 ^ 48 - 2 ^ 16
  attributes := SP1_PMA
  include_in_device_tree := false

/-- All the registers needed for memory ops are set appropriately. -/
structure SailState.isValidMemConfig (s : SailState) (hs : SailState.isInitialized s) where
  h_cur_privilege : s.regs.get Register.cur_privilege (hs _) = Privilege.Machine
  h_mprv_disabled : BitVec.ofNat 1 ((s.regs.get Register.mstatus (hs _)).toNat >>> 17) = 0#1
  h_mseccfg_disabled : BitVec.ofNat 1 ((s.regs.get Register.mseccfg (hs _)).toNat >>> 10) = 0#1
  h_htif_disabled : s.regs.get Register.htif_tohost_base (hs _) = none
  h_pma_regions : s.regs.get Register.pma_regions (hs _) = [SP1_PMA_Region]

end isValidMemConfig

/-- `update_elp_state rs1` (the Zicfilp landing-pad bookkeeping that prefixes `execute_JALR`) is
state-preserving under the SP1 kernel config: the `Ext_Zicfilp` enable check resolves through the
`mseccfg` MLPE bit (disabled), so the `writeReg elp …` branch is dead and the whole step is `pure ()`. -/
lemma update_elp_state_of_isInitialized (rs1 : regidx) (s : SailState)
    (hs : SailState.isInitialized s) (hs' : SailState.isValidMemConfig s hs) :
    EStateM.run (update_elp_state rs1) s = EStateM.Result.ok () s := by
  -- `Seccfg.MLPE` (bit 10 of `mseccfg`) is `0` ⇒ `get_xLPE Machine = false` ⇒ Zicfilp disabled.
  have hmlpe : Sail.BitVec.extractLsb (s.regs.get Register.mseccfg (hs _)) 10 10 = 0#1 := by
    apply BitVec.eq_of_toNat_eq
    rw [Sail.BitVec.extractLsb, BitVec.extractLsb, BitVec.extractLsb'_toNat]
    have h2 := congrArg BitVec.toNat hs'.h_mseccfg_disabled
    simp only [BitVec.toNat_ofNat, BitVec.toNat_zero] at h2 ⊢
    omega
  simp only [update_elp_state, currentlyEnabled, get_xLPE, hartSupports, _get_Seccfg_MLPE,
    bool_bit_backwards, bit_to_bool, pure_bind, bind_assoc,
    Sail.run_readReg_bind_of_isInitialized s _ hs, hs'.h_cur_privilege, hmlpe,
    Bool.true_and, Bool.and_false, Bool.false_and, if_false]
  rfl

set_option linter.style.nativeDecide false in
/-- Read counterpart of `run_within_mmio_writable_mmio`. -/
lemma run_within_mmio_readable_mmio (reg_val : BitVec 64) (offset : BitVec 64)
    (width : ℕ) (s : SailState) (hs : SailState.isInitialized s)
    (h_htif : s.regs.get Register.htif_tohost_base (hs _) = none) :
    (within_mmio_readable (physaddr.Physaddr
      (zero_extend (BitVec.addInt (reg_val + offset) 0))) width).run s = .ok false s := by
  have h_base : BitVec.toNat plat_clint_base = 33554432 := by rfl
  have h_bv : (reg_val + offset).toNat = (reg_val.toNat + offset.toNat) % 18446744073709551616 :=
    BitVec.toNat_add reg_val offset
  simp [within_mmio_readable, get_config_rvfi, within_clint]
  simp [within_htif_readable, within_htif_writable, BitVec.addInt, zero_extend,
    Sail.BitVec.zeroExtend, Sail.BitVec.toNatInt, within_sig,
    Std.ExtDHashMap.get?_eq_some_get (hs _), h_htif]

set_option linter.style.nativeDecide false in
/-- Write counterpart of `run_within_mmio_readable_mmio`. -/
lemma run_within_mmio_writable_mmio (reg_val : BitVec 64) (offset : BitVec 64)
    (width : ℕ) (s : SailState) (hs : SailState.isInitialized s)
    (h_htif : s.regs.get Register.htif_tohost_base (hs _) = none) :
    (within_mmio_writable (physaddr.Physaddr
      (zero_extend (BitVec.addInt (reg_val + offset) 0))) width).run s = .ok false s := by
  have h_base : BitVec.toNat plat_clint_base = 33554432 := by rfl
  have h_bv : (reg_val + offset).toNat = (reg_val.toNat + offset.toNat) % 18446744073709551616 :=
    BitVec.toNat_add reg_val offset
  simp [within_mmio_writable, get_config_rvfi, within_clint]
  simp [within_htif_readable, within_htif_writable, BitVec.addInt, zero_extend,
    Sail.BitVec.zeroExtend, Sail.BitVec.toNatInt, within_sig,
    Std.ExtDHashMap.get?_eq_some_get (hs _), h_htif]

/-- Eight-byte `checked_mem_read` under kernel config. -/
lemma run_checked_mem_read_eight_bytes_of_isInitialized
    (reg_val offset : BitVec 64)
    (data₀ data₁ data₂ data₃ data₄ data₅ data₆ data₇ : BitVec 8)
    (s : SailState) (hs : SailState.isInitialized s)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 8) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true)
    (h_htif : s.regs.get Register.htif_tohost_base (hs _) = none)
    (h_pma : s.regs.get Register.pma_regions (hs _) = [SP1_PMA_Region])
    (hmem₀ : s.mem[(reg_val + offset).toNat]? = some data₀)
    (hmem₁ : s.mem[(reg_val + offset).toNat + 1]? = some data₁)
    (hmem₂ : s.mem[(reg_val + offset).toNat + 2]? = some data₂)
    (hmem₃ : s.mem[(reg_val + offset).toNat + 3]? = some data₃)
    (hmem₄ : s.mem[(reg_val + offset).toNat + 4]? = some data₄)
    (hmem₅ : s.mem[(reg_val + offset).toNat + 5]? = some data₅)
    (hmem₆ : s.mem[(reg_val + offset).toNat + 6]? = some data₆)
    (hmem₇ : s.mem[(reg_val + offset).toNat + 7]? = some data₇) :
    (checked_mem_read (MemoryAccessType.Load mem_payload.Data)
        page_based_mem_type.PBMT_PMA Privilege.Machine
        (physaddr.Physaddr (zero_extend (BitVec.addInt (reg_val + offset) 0))) 8
        false false false false).run s
      = .ok (.Ok (data₇ ++ data₆ ++ data₅ ++ data₄ ++ data₃ ++ data₂ ++ data₁ ++ data₀, ())) s := by
  simp [checked_mem_read, phys_access_check, pmpCheck, SailME.run, PreSail.PreSailME.run]
  simp [pmaCheck, Std.ExtDHashMap.get?_eq_some_get (hs _), h_pma]
  simp [matching_pma_region, matching_pma_region_bits_range]
  erw [h_in_range]
  simp [EStateM.Result.map, accessFaultFromAccessType,
    pma_misaligned_exception, SP1_PMA]
  simp [is_aligned_paddr, override_PMA, - EStateM.run_bind]
  erw [EStateM.run_bind, run_within_mmio_readable_mmio reg_val offset 8 s hs h_htif]
  simp [read_kind_of_flags, read_ram]
  simp [ConcurrencyInterfaceV1.sail_mem_read, PreSail.ConcurrencyInterfaceV1.sail_mem_read]
  simp only [zero_extend, BitVec.addInt, Sail.BitVec.zeroExtend]
  have hmod : (reg_val + offset).toNat = (reg_val.toNat + offset.toNat) % 18446744073709551616 :=
    BitVec.toNat_add reg_val offset
  have hmem₀' : s.mem[(reg_val.toNat + offset.toNat) % 18446744073709551616]? = some data₀ := by
    rw [← hmod]; exact hmem₀
  have hmem₁' : s.mem[(reg_val.toNat + offset.toNat) % 18446744073709551616 + 1]? = some data₁ := by
    rw [← hmod]; exact hmem₁
  have hmem₂' : s.mem[(reg_val.toNat + offset.toNat) % 18446744073709551616 + 2]? = some data₂ := by
    rw [← hmod]; exact hmem₂
  have hmem₃' : s.mem[(reg_val.toNat + offset.toNat) % 18446744073709551616 + 3]? = some data₃ := by
    rw [← hmod]; exact hmem₃
  have hmem₄' : s.mem[(reg_val.toNat + offset.toNat) % 18446744073709551616 + 4]? = some data₄ := by
    rw [← hmod]; exact hmem₄
  have hmem₅' : s.mem[(reg_val.toNat + offset.toNat) % 18446744073709551616 + 5]? = some data₅ := by
    rw [← hmod]; exact hmem₅
  have hmem₆' : s.mem[(reg_val.toNat + offset.toNat) % 18446744073709551616 + 6]? = some data₆ := by
    rw [← hmod]; exact hmem₆
  have hmem₇' : s.mem[(reg_val.toNat + offset.toNat) % 18446744073709551616 + 7]? = some data₇ := by
    rw [← hmod]; exact hmem₇
  simp [PreSail.readBytes, PreSail.readByte,
    hmem₀', hmem₁', hmem₂', hmem₃', hmem₄', hmem₅', hmem₆', hmem₇',
    bind, Bind.bind, EStateM.bind, EStateM.map, EStateM.pure,
    EStateM.run, pure, Pure.pure, Functor.map, getThe, MonadStateOf.get, MonadState.get,
    get, EStateM.get, MemoryOpResult_add_meta]

/-- Eight-byte `mem_read` under kernel config. -/
lemma run_mem_read_eight_bytes_of_isInitialized
    (reg_val offset : BitVec 64)
    (data₀ data₁ data₂ data₃ data₄ data₅ data₆ data₇ : BitVec 8)
    (s : SailState) (hs : SailState.isInitialized s)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 8) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true)
    (hconfig : SailState.isValidMemConfig s hs)
    (hmem₀ : s.mem[(reg_val + offset).toNat]? = some data₀)
    (hmem₁ : s.mem[(reg_val + offset).toNat + 1]? = some data₁)
    (hmem₂ : s.mem[(reg_val + offset).toNat + 2]? = some data₂)
    (hmem₃ : s.mem[(reg_val + offset).toNat + 3]? = some data₃)
    (hmem₄ : s.mem[(reg_val + offset).toNat + 4]? = some data₄)
    (hmem₅ : s.mem[(reg_val + offset).toNat + 5]? = some data₅)
    (hmem₆ : s.mem[(reg_val + offset).toNat + 6]? = some data₆)
    (hmem₇ : s.mem[(reg_val + offset).toNat + 7]? = some data₇) :
    (mem_read (MemoryAccessType.Load mem_payload.Data)
        page_based_mem_type.PBMT_PMA
        (physaddr.Physaddr (zero_extend (BitVec.addInt (reg_val + offset) 0))) 8
        false false false).run s
      = .ok (.Ok (data₇ ++ data₆ ++ data₅ ++ data₄ ++ data₃ ++ data₂ ++ data₁ ++ data₀)) s := by
  obtain ⟨h_cur_privilege, h_mprv_disabled, _, h_htif, h_pma⟩ := hconfig
  have hmprv' : Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 = 0#1 := by
    rw [show Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 =
      BitVec.ofNat 1 (BitVec.toNat (s.regs.get Register.mstatus (hs _)) >>> 17) from rfl]
    exact h_mprv_disabled
  simp [mem_read, mem_read_priv, mem_read_priv_meta, MemoryOpResult_drop_meta,
    Std.ExtDHashMap.get?_eq_some_get (hs _),
    h_cur_privilege, effectivePrivilege, _get_Mstatus_MPRV, hmprv']
  exact ⟨_, run_checked_mem_read_eight_bytes_of_isInitialized reg_val offset
    data₀ data₁ data₂ data₃ data₄ data₅ data₆ data₇ s hs h_in_range h_htif h_pma
    hmem₀ hmem₁ hmem₂ hmem₃ hmem₄ hmem₅ hmem₆ hmem₇, rfl⟩

/-- Convert the Sail-level alignment check to a plain `Nat`-mod fact. -/
lemma is_aligned_vaddr_iff_mod (addr : BitVec 64) (N : ℕ) :
    is_aligned_vaddr (virtaddr.Virtaddr addr) N = true ↔ addr.toNat % N = 0 := by
  rw [is_aligned_vaddr]
  simp only [Sail.BitVec.toNatInt, beq_iff_eq]
  rw [show (Int.ofNat addr.toNat : ℤ) = ((addr.toNat : ℕ) : ℤ) from rfl,
      show (N : ℤ) = ((N : ℕ) : ℤ) from rfl, ← Int.ofNat_tmod, Nat.cast_eq_zero]

/-- Bridge: every access whose `addr` lives in `[2^16, 2^48 - N]` falls inside
the SP1 PMA window `[2^16, 2^48)`. Chip-side proofs derive `addr ≥ 2^16` from
the `AddressOperation` top-two-limb inverse trick and `addr.toNat + N ≤ 2^48`
from the AddrAddOperation u48 bound (plus per-width alignment), then call this
to satisfy the `h_in_range` precondition of every `run_vmem_*_of_width_*'`. -/
lemma range_subset_sp1_pma (addr : BitVec 64) (N : ℕ) (hN_pos : 0 < N)
    (h_lo : 2 ^ 16 ≤ addr.toNat) (h_hi : addr.toNat + N ≤ 2 ^ 48) :
    range_subset (zero_extend (BitVec.addInt addr 0) : BitVec 64)
      (to_bits N : BitVec 64) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true := by
  have hzext : (zero_extend (BitVec.addInt addr 0) : BitVec 64) = addr := by
    simp [zero_extend, BitVec.addInt, Sail.BitVec.zeroExtend, BitVec.ofInt]
  rw [hzext]
  have h_to_bits : (to_bits N : BitVec 64).toNat = N := by
    simp [to_bits, get_slice_int, BitVec.toNat_ofInt]; omega
  have h_p16 : (2#64 ^ 16).toNat = 65536 := by decide
  have h_p48 : (2#64 ^ 48).toNat = 281474976710656 := by decide
  have h_eq : ∀ x y : BitVec 64, (zopz0zIzJ_u x y = true) ↔ (x.toNat ≤ y.toNat) :=
    fun _ _ => by simp [zopz0zIzJ_u, BitVec.toNatInt]
  unfold range_subset
  rw [Bool.and_eq_true, Bool.and_eq_true, h_eq, h_eq, h_eq]
  refine ⟨?_, ?_, ?_⟩ <;>
    simp only [BitVec.toNat_sub, BitVec.toNat_add, h_to_bits, h_p16, h_p48] <;> omega

lemma run_vmem_read_of_width_8'
    (rs_addr_bv : BitVec 5)
    (reg_val : BitVec 64) -- thing inside `rs_addr_bv`
    (offset : BitVec 64)
    (data₀ data₁ data₂ data₃ data₄ data₅ data₆ data₇ : BitVec 8) -- bigger for others
    (s : SailState)
    (hs : SailState.isInitialized s)
    (h_reg_val : s.get_reg? rs_addr_bv = some reg_val)
    (h_aligned : is_aligned_vaddr (virtaddr.Virtaddr (reg_val + offset)) 8 = true) ---width
    (hconfig : SailState.isValidMemConfig s hs)
    (h_does_fit : reg_val.toNat + offset.toNat + 8 < 2 ^ 64)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 8) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true)
    (hmem₀ : s.mem[reg_val.toNat + offset.toNat]? = some data₀)
    (hmem₁ : s.mem[reg_val.toNat + offset.toNat + 1]? = some data₁)
    (hmem₂ : s.mem[reg_val.toNat + offset.toNat + 2]? = some data₂)
    (hmem₃ : s.mem[reg_val.toNat + offset.toNat + 3]? = some data₃)
    (hmem₄ : s.mem[reg_val.toNat + offset.toNat + 4]? = some data₄)
    (hmem₅ : s.mem[reg_val.toNat + offset.toNat + 5]? = some data₅)
    (hmem₆ : s.mem[reg_val.toNat + offset.toNat + 6]? = some data₆)
    (hmem₇ : s.mem[reg_val.toNat + offset.toNat + 7]? = some data₇) :
    let width := 8
    let data := data₇ ++ data₆ ++ data₅ ++ data₄ ++ data₃ ++ data₂ ++ data₁ ++ data₀
    (vmem_read (.Regidx rs_addr_bv) offset width (MemoryAccessType.Load mem_payload.Data)
      false false false).run s = .ok (.Ok data) s := by
  have h_mprv_disabled := hconfig.h_mprv_disabled
  have h_cur_privilege := hconfig.h_cur_privilege
  have hmachine : (Privilege.Machine == Privilege.Machine) = true := rfl
  have hsatp_bare : (SATPMode.Bare == SATPMode.Bare) = true := rfl
  have hfetch : (MemoryAccessType.Load mem_payload.Data !=
      MemoryAccessType.InstructionFetch ()) = true := rfl
  have hrx : rX_bits (regidx.Regidx rs_addr_bv) s = .ok reg_val s := by
    have h := @run_rX_bits rs_addr_bv s
    simp only [EStateM.run] at h
    rw [h, h_reg_val]
  have hmod : (reg_val + offset).toNat = reg_val.toNat + offset.toNat := by
    rw [BitVec.toNat_add, Nat.mod_eq_of_lt]; omega
  have hmem₀' : s.mem[(reg_val + offset).toNat]? = some data₀ := by rw [hmod]; exact hmem₀
  have hmem₁' : s.mem[(reg_val + offset).toNat + 1]? = some data₁ := by rw [hmod]; exact hmem₁
  have hmem₂' : s.mem[(reg_val + offset).toNat + 2]? = some data₂ := by rw [hmod]; exact hmem₂
  have hmem₃' : s.mem[(reg_val + offset).toNat + 3]? = some data₃ := by rw [hmod]; exact hmem₃
  have hmem₄' : s.mem[(reg_val + offset).toNat + 4]? = some data₄ := by rw [hmod]; exact hmem₄
  have hmem₅' : s.mem[(reg_val + offset).toNat + 5]? = some data₅ := by rw [hmod]; exact hmem₅
  have hmem₆' : s.mem[(reg_val + offset).toNat + 6]? = some data₆ := by rw [hmod]; exact hmem₆
  have hmem₇' : s.mem[(reg_val + offset).toNat + 7]? = some data₇ := by rw [hmod]; exact hmem₇
  have hmprv' : Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 = 0#1 := by
    rw [show Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 =
      BitVec.ofNat 1 (BitVec.toNat (s.regs.get Register.mstatus (hs _)) >>> 17) from rfl]
    exact h_mprv_disabled
  unfold vmem_read vmem_read_addr ext_data_get_addr
  simp [SailME.run, PreSail.PreSailME.run, ExceptT.run, ExceptT.bind, ExceptT.mk,
    ExceptT.bindCont, ExceptT.lift, ExceptT.map, ExceptT.pure,
    MonadLift.monadLift, liftM, monadLift, Functor.map, Except.map,
    Bind.bind, Pure.pure, SailME.throw, PreSail.PreSailME.throw,
    bind, pure, EStateM.bind, EStateM.map, EStateM.pure, EStateM.run,
    hrx, h_aligned, split_misaligned, misaligned_order, untilFuelM, untilFuelM.go,
    LeanRV64D.Functions.not]
  simp [translateAddr, translationMode, effectivePrivilege,
    SailME.run, PreSail.PreSailME.run, ExceptT.run, ExceptT.bind, ExceptT.mk,
    ExceptT.bindCont, ExceptT.lift, ExceptT.map, ExceptT.pure,
    MonadLift.monadLift, liftM, monadLift,
    bind, pure, EStateM.bind, EStateM.map, EStateM.pure, Functor.map,
    Sail.readReg, PreSail.readReg, run_readReg_of_isInitialized s _ hs,
    Std.ExtDHashMap.get?_eq_some_get (hs _),
    getThe, MonadStateOf.get, MonadState.get, get, EStateM.get,
    modifyGet, MonadStateOf.modifyGet, MonadState.modifyGet, EStateM.modifyGet,
    privLevel_bits_backwards, privLevel_bits_forwards,
    hmprv', h_cur_privilege, hmachine, hsatp_bare,
    hfetch, is_shadow_stack_access]
  have h := run_mem_read_eight_bytes_of_isInitialized reg_val offset
    data₀ data₁ data₂ data₃ data₄ data₅ data₆ data₇ s hs h_in_range hconfig
    hmem₀' hmem₁' hmem₂' hmem₃' hmem₄' hmem₅' hmem₆' hmem₇'
  simp only [EStateM.run] at h
  simp [zero_extend, BitVec.addInt, Sail.BitVec.zeroExtend] at h ⊢
  conv_lhs => rw [h]
  simp [BitVec.updateSubrange, BitVec.updateSubrange', Sail.BitVec.updateSubrange,
    BitVec.setWidth_eq]
  rfl

/-- Four-byte `checked_mem_read` under kernel config (the width-4 analogue of the eight-byte
version, for `LW`/`LWU`). -/
lemma run_checked_mem_read_four_bytes_of_isInitialized
    (reg_val offset : BitVec 64)
    (data₀ data₁ data₂ data₃ : BitVec 8)
    (s : SailState) (hs : SailState.isInitialized s)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 4) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true)
    (h_htif : s.regs.get Register.htif_tohost_base (hs _) = none)
    (h_pma : s.regs.get Register.pma_regions (hs _) = [SP1_PMA_Region])
    (hmem₀ : s.mem[(reg_val + offset).toNat]? = some data₀)
    (hmem₁ : s.mem[(reg_val + offset).toNat + 1]? = some data₁)
    (hmem₂ : s.mem[(reg_val + offset).toNat + 2]? = some data₂)
    (hmem₃ : s.mem[(reg_val + offset).toNat + 3]? = some data₃) :
    (checked_mem_read (MemoryAccessType.Load mem_payload.Data)
        page_based_mem_type.PBMT_PMA Privilege.Machine
        (physaddr.Physaddr (zero_extend (BitVec.addInt (reg_val + offset) 0))) 4
        false false false false).run s
      = .ok (.Ok (data₃ ++ data₂ ++ data₁ ++ data₀, ())) s := by
  simp [checked_mem_read, phys_access_check, pmpCheck, SailME.run, PreSail.PreSailME.run]
  simp [pmaCheck, Std.ExtDHashMap.get?_eq_some_get (hs _), h_pma]
  simp [matching_pma_region, matching_pma_region_bits_range]
  erw [h_in_range]
  simp [EStateM.Result.map, accessFaultFromAccessType,
    pma_misaligned_exception, SP1_PMA]
  simp [is_aligned_paddr, override_PMA, - EStateM.run_bind]
  erw [EStateM.run_bind, run_within_mmio_readable_mmio reg_val offset 4 s hs h_htif]
  simp [read_kind_of_flags, read_ram]
  simp [ConcurrencyInterfaceV1.sail_mem_read, PreSail.ConcurrencyInterfaceV1.sail_mem_read]
  simp only [zero_extend, BitVec.addInt, Sail.BitVec.zeroExtend]
  have hmod : (reg_val + offset).toNat = (reg_val.toNat + offset.toNat) % 18446744073709551616 :=
    BitVec.toNat_add reg_val offset
  have hmem₀' : s.mem[(reg_val.toNat + offset.toNat) % 18446744073709551616]? = some data₀ := by
    rw [← hmod]; exact hmem₀
  have hmem₁' : s.mem[(reg_val.toNat + offset.toNat) % 18446744073709551616 + 1]? = some data₁ := by
    rw [← hmod]; exact hmem₁
  have hmem₂' : s.mem[(reg_val.toNat + offset.toNat) % 18446744073709551616 + 2]? = some data₂ := by
    rw [← hmod]; exact hmem₂
  have hmem₃' : s.mem[(reg_val.toNat + offset.toNat) % 18446744073709551616 + 3]? = some data₃ := by
    rw [← hmod]; exact hmem₃
  simp [PreSail.readBytes, PreSail.readByte,
    hmem₀', hmem₁', hmem₂', hmem₃',
    bind, Bind.bind, EStateM.bind, EStateM.map, EStateM.pure,
    EStateM.run, pure, Pure.pure, Functor.map, getThe, MonadStateOf.get, MonadState.get,
    get, EStateM.get, MemoryOpResult_add_meta]

/-- Four-byte `checked_mem_read` on the **`InstructionFetch`** path under kernel config. Identical to the
`Load` version — `SP1_PMA` grants `executable := true` alongside `readable := true`, so `phys_access_check`
passes for a fetch exactly as for a load. The fetch reduction (`fetch () = F_Base w`) reuses this. -/
lemma run_checked_mem_read_four_bytes_fetch_of_isInitialized
    (reg_val offset : BitVec 64)
    (data₀ data₁ data₂ data₃ : BitVec 8)
    (s : SailState) (hs : SailState.isInitialized s)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 4) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true)
    (h_align : Int.tmod (↑(zero_extend (BitVec.addInt (reg_val + offset) 0) : BitVec 64).toNat) 4 = 0)
    (h_htif : s.regs.get Register.htif_tohost_base (hs _) = none)
    (h_pma : s.regs.get Register.pma_regions (hs _) = [SP1_PMA_Region])
    (hmem₀ : s.mem[(reg_val + offset).toNat]? = some data₀)
    (hmem₁ : s.mem[(reg_val + offset).toNat + 1]? = some data₁)
    (hmem₂ : s.mem[(reg_val + offset).toNat + 2]? = some data₂)
    (hmem₃ : s.mem[(reg_val + offset).toNat + 3]? = some data₃) :
    (checked_mem_read (MemoryAccessType.InstructionFetch ())
        page_based_mem_type.PBMT_PMA Privilege.Machine
        (physaddr.Physaddr (zero_extend (BitVec.addInt (reg_val + offset) 0))) 4
        false false false false).run s
      = .ok (.Ok (data₃ ++ data₂ ++ data₁ ++ data₀, ())) s := by
  simp [checked_mem_read, phys_access_check, pmpCheck, SailME.run, PreSail.PreSailME.run]
  simp [pmaCheck, Std.ExtDHashMap.get?_eq_some_get (hs _), h_pma]
  simp [matching_pma_region, matching_pma_region_bits_range]
  erw [h_in_range]
  simp [EStateM.Result.map, accessFaultFromAccessType,
    pma_misaligned_exception, SP1_PMA]
  simp [is_aligned_paddr, override_PMA, h_align, - EStateM.run_bind]
  erw [EStateM.run_bind, run_within_mmio_readable_mmio reg_val offset 4 s hs h_htif]
  simp [read_kind_of_flags, read_ram]
  simp [ConcurrencyInterfaceV1.sail_mem_read, PreSail.ConcurrencyInterfaceV1.sail_mem_read]
  simp only [zero_extend, BitVec.addInt, Sail.BitVec.zeroExtend]
  have hmod : (reg_val + offset).toNat = (reg_val.toNat + offset.toNat) % 18446744073709551616 :=
    BitVec.toNat_add reg_val offset
  have hmem₀' : s.mem[(reg_val.toNat + offset.toNat) % 18446744073709551616]? = some data₀ := by
    rw [← hmod]; exact hmem₀
  have hmem₁' : s.mem[(reg_val.toNat + offset.toNat) % 18446744073709551616 + 1]? = some data₁ := by
    rw [← hmod]; exact hmem₁
  have hmem₂' : s.mem[(reg_val.toNat + offset.toNat) % 18446744073709551616 + 2]? = some data₂ := by
    rw [← hmod]; exact hmem₂
  have hmem₃' : s.mem[(reg_val.toNat + offset.toNat) % 18446744073709551616 + 3]? = some data₃ := by
    rw [← hmod]; exact hmem₃
  simp [PreSail.readBytes, PreSail.readByte,
    hmem₀', hmem₁', hmem₂', hmem₃',
    bind, Bind.bind, EStateM.bind, EStateM.map, EStateM.pure,
    EStateM.run, pure, Pure.pure, Functor.map, getThe, MonadStateOf.get, MonadState.get,
    get, EStateM.get, MemoryOpResult_add_meta]

/-- Four-byte `mem_read` on the **`InstructionFetch`** path under kernel config. `effectivePrivilege` for a
fetch ignores `MPRV` (the `bne` is false), landing directly at `cur_privilege = Machine`. -/
lemma run_mem_read_four_bytes_fetch_of_isInitialized
    (reg_val offset : BitVec 64)
    (data₀ data₁ data₂ data₃ : BitVec 8)
    (s : SailState) (hs : SailState.isInitialized s)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 4) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true)
    (h_align : Int.tmod (↑(zero_extend (BitVec.addInt (reg_val + offset) 0) : BitVec 64).toNat) 4 = 0)
    (hconfig : SailState.isValidMemConfig s hs)
    (hmem₀ : s.mem[(reg_val + offset).toNat]? = some data₀)
    (hmem₁ : s.mem[(reg_val + offset).toNat + 1]? = some data₁)
    (hmem₂ : s.mem[(reg_val + offset).toNat + 2]? = some data₂)
    (hmem₃ : s.mem[(reg_val + offset).toNat + 3]? = some data₃) :
    (mem_read (MemoryAccessType.InstructionFetch ())
        page_based_mem_type.PBMT_PMA
        (physaddr.Physaddr (zero_extend (BitVec.addInt (reg_val + offset) 0))) 4
        false false false).run s
      = .ok (.Ok (data₃ ++ data₂ ++ data₁ ++ data₀)) s := by
  obtain ⟨h_cur_privilege, h_mprv_disabled, _, h_htif, h_pma⟩ := hconfig
  -- the `effectivePrivilege` MPRV branch is dead: `mstatus.MPRV = 0` ⇒ the `∧`'s second conjunct is false,
  -- so the fetch lands directly at `cur_privilege = Machine` (no need to evaluate the `access ≠ fetch` bne).
  have hmprv' : Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 = 0#1 := by
    rw [show Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 =
      BitVec.ofNat 1 (BitVec.toNat (s.regs.get Register.mstatus (hs _)) >>> 17) from rfl]
    exact h_mprv_disabled
  simp [mem_read, mem_read_priv, mem_read_priv_meta, MemoryOpResult_drop_meta,
    Std.ExtDHashMap.get?_eq_some_get (hs _),
    h_cur_privilege, effectivePrivilege, hmprv', EStateM.Result.map,
    run_checked_mem_read_four_bytes_fetch_of_isInitialized reg_val offset
      data₀ data₁ data₂ data₃ s hs h_in_range h_align h_htif h_pma
      hmem₀ hmem₁ hmem₂ hmem₃]

/-- Four-byte `mem_read` under kernel config. -/
lemma run_mem_read_four_bytes_of_isInitialized
    (reg_val offset : BitVec 64)
    (data₀ data₁ data₂ data₃ : BitVec 8)
    (s : SailState) (hs : SailState.isInitialized s)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 4) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true)
    (hconfig : SailState.isValidMemConfig s hs)
    (hmem₀ : s.mem[(reg_val + offset).toNat]? = some data₀)
    (hmem₁ : s.mem[(reg_val + offset).toNat + 1]? = some data₁)
    (hmem₂ : s.mem[(reg_val + offset).toNat + 2]? = some data₂)
    (hmem₃ : s.mem[(reg_val + offset).toNat + 3]? = some data₃) :
    (mem_read (MemoryAccessType.Load mem_payload.Data)
        page_based_mem_type.PBMT_PMA
        (physaddr.Physaddr (zero_extend (BitVec.addInt (reg_val + offset) 0))) 4
        false false false).run s
      = .ok (.Ok (data₃ ++ data₂ ++ data₁ ++ data₀)) s := by
  obtain ⟨h_cur_privilege, h_mprv_disabled, _, h_htif, h_pma⟩ := hconfig
  have hmprv' : Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 = 0#1 := by
    rw [show Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 =
      BitVec.ofNat 1 (BitVec.toNat (s.regs.get Register.mstatus (hs _)) >>> 17) from rfl]
    exact h_mprv_disabled
  simp [mem_read, mem_read_priv, mem_read_priv_meta, MemoryOpResult_drop_meta,
    Std.ExtDHashMap.get?_eq_some_get (hs _),
    h_cur_privilege, effectivePrivilege, _get_Mstatus_MPRV, hmprv']
  exact ⟨_, run_checked_mem_read_four_bytes_of_isInitialized reg_val offset
    data₀ data₁ data₂ data₃ s hs h_in_range h_htif h_pma
    hmem₀ hmem₁ hmem₂ hmem₃, rfl⟩

lemma run_vmem_read_of_width_4'
    (rs_addr_bv : BitVec 5)
    (reg_val : BitVec 64)
    (offset : BitVec 64)
    (data₀ data₁ data₂ data₃ : BitVec 8)
    (s : SailState)
    (hs : SailState.isInitialized s)
    (h_reg_val : s.get_reg? rs_addr_bv = some reg_val)
    (h_aligned : is_aligned_vaddr (virtaddr.Virtaddr (reg_val + offset)) 4 = true)
    (hconfig : SailState.isValidMemConfig s hs)
    (h_does_fit : reg_val.toNat + offset.toNat + 4 < 2 ^ 64)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 4) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true)
    (hmem₀ : s.mem[reg_val.toNat + offset.toNat]? = some data₀)
    (hmem₁ : s.mem[reg_val.toNat + offset.toNat + 1]? = some data₁)
    (hmem₂ : s.mem[reg_val.toNat + offset.toNat + 2]? = some data₂)
    (hmem₃ : s.mem[reg_val.toNat + offset.toNat + 3]? = some data₃) :
    let width := 4
    let data := data₃ ++ data₂ ++ data₁ ++ data₀
    (vmem_read (.Regidx rs_addr_bv) offset width (MemoryAccessType.Load mem_payload.Data)
      false false false).run s = .ok (.Ok data) s := by
  have h_mprv_disabled := hconfig.h_mprv_disabled
  have h_cur_privilege := hconfig.h_cur_privilege
  have hmachine : (Privilege.Machine == Privilege.Machine) = true := rfl
  have hsatp_bare : (SATPMode.Bare == SATPMode.Bare) = true := rfl
  have hfetch : (MemoryAccessType.Load mem_payload.Data !=
      MemoryAccessType.InstructionFetch ()) = true := rfl
  have hrx : rX_bits (regidx.Regidx rs_addr_bv) s = .ok reg_val s := by
    have h := @run_rX_bits rs_addr_bv s
    simp only [EStateM.run] at h
    rw [h, h_reg_val]
  have hmod : (reg_val + offset).toNat = reg_val.toNat + offset.toNat := by
    rw [BitVec.toNat_add, Nat.mod_eq_of_lt]; omega
  have hmem₀' : s.mem[(reg_val + offset).toNat]? = some data₀ := by rw [hmod]; exact hmem₀
  have hmem₁' : s.mem[(reg_val + offset).toNat + 1]? = some data₁ := by rw [hmod]; exact hmem₁
  have hmem₂' : s.mem[(reg_val + offset).toNat + 2]? = some data₂ := by rw [hmod]; exact hmem₂
  have hmem₃' : s.mem[(reg_val + offset).toNat + 3]? = some data₃ := by rw [hmod]; exact hmem₃
  have hmprv' : Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 = 0#1 := by
    rw [show Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 =
      BitVec.ofNat 1 (BitVec.toNat (s.regs.get Register.mstatus (hs _)) >>> 17) from rfl]
    exact h_mprv_disabled
  unfold vmem_read vmem_read_addr ext_data_get_addr
  simp [SailME.run, PreSail.PreSailME.run, ExceptT.run, ExceptT.bind, ExceptT.mk,
    ExceptT.bindCont, ExceptT.lift, ExceptT.map, ExceptT.pure,
    MonadLift.monadLift, liftM, monadLift, Functor.map, Except.map,
    Bind.bind, Pure.pure, SailME.throw, PreSail.PreSailME.throw,
    bind, pure, EStateM.bind, EStateM.map, EStateM.pure, EStateM.run,
    hrx, h_aligned, split_misaligned, misaligned_order, untilFuelM, untilFuelM.go,
    LeanRV64D.Functions.not]
  simp [translateAddr, translationMode, effectivePrivilege,
    SailME.run, PreSail.PreSailME.run, ExceptT.run, ExceptT.bind, ExceptT.mk,
    ExceptT.bindCont, ExceptT.lift, ExceptT.map, ExceptT.pure,
    MonadLift.monadLift, liftM, monadLift,
    bind, pure, EStateM.bind, EStateM.map, EStateM.pure, Functor.map,
    Sail.readReg, PreSail.readReg, run_readReg_of_isInitialized s _ hs,
    Std.ExtDHashMap.get?_eq_some_get (hs _),
    getThe, MonadStateOf.get, MonadState.get, get, EStateM.get,
    modifyGet, MonadStateOf.modifyGet, MonadState.modifyGet, EStateM.modifyGet,
    privLevel_bits_backwards, privLevel_bits_forwards,
    hmprv', h_cur_privilege, hmachine, hsatp_bare,
    hfetch, is_shadow_stack_access]
  have h := run_mem_read_four_bytes_of_isInitialized reg_val offset
    data₀ data₁ data₂ data₃ s hs h_in_range hconfig
    hmem₀' hmem₁' hmem₂' hmem₃'
  simp only [EStateM.run] at h
  simp [zero_extend, BitVec.addInt, Sail.BitVec.zeroExtend] at h ⊢
  conv_lhs => rw [h]
  simp [BitVec.updateSubrange, BitVec.updateSubrange', Sail.BitVec.updateSubrange,
    BitVec.setWidth_eq]
  rfl

/-- Eight-byte `checked_mem_write` under kernel config. -/
lemma run_checked_mem_write_eight_bytes_of_isInitialized
    (reg_val offset : BitVec 64) (data : BitVec 64)
    (s : SailState) (hs : SailState.isInitialized s)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 8) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true)
    (h_htif : s.regs.get Register.htif_tohost_base (hs _) = none)
    (h_pma : s.regs.get Register.pma_regions (hs _) = [SP1_PMA_Region]) :
    let paddr_nat :=
      BitVec.toNat ((zero_extend (BitVec.addInt (reg_val + offset) 0)) : BitVec 64)
    let new_mem := ((((((((s.mem.insert paddr_nat
      (BitVec.ofNat 8 data.toNat)).insert
      (paddr_nat + 1) (BitVec.ofNat 8 (data.toNat >>> 8))).insert
      (paddr_nat + 2) (BitVec.ofNat 8 (data.toNat >>> 16))).insert
      (paddr_nat + 3) (BitVec.ofNat 8 (data.toNat >>> 24))).insert
      (paddr_nat + 4) (BitVec.ofNat 8 (data.toNat >>> 32))).insert
      (paddr_nat + 5) (BitVec.ofNat 8 (data.toNat >>> 40))).insert
      (paddr_nat + 6) (BitVec.ofNat 8 (data.toNat >>> 48))).insert
      (paddr_nat + 7) (BitVec.ofNat 8 (data.toNat >>> 56)))
    (checked_mem_write
        (physaddr.Physaddr (zero_extend (BitVec.addInt (reg_val + offset) 0))) 8
        data (MemoryAccessType.Store mem_payload.Data)
        page_based_mem_type.PBMT_PMA Privilege.Machine () false false false).run s
      = .ok (.Ok true) { s with mem := new_mem } := by
  simp [checked_mem_write, phys_access_check, pmpCheck, SailME.run, PreSail.PreSailME.run]
  simp [pmaCheck, Std.ExtDHashMap.get?_eq_some_get (hs _), h_pma]
  simp [matching_pma_region, matching_pma_region_bits_range]
  erw [h_in_range]
  simp [EStateM.Result.map, accessFaultFromAccessType,
    pma_misaligned_exception, SP1_PMA]
  simp [is_aligned_paddr, override_PMA, - EStateM.run_bind]
  erw [EStateM.run_bind, run_within_mmio_writable_mmio reg_val offset 8 s hs h_htif]
  simp [write_kind_of_flags, write_ram]
  simp [ConcurrencyInterfaceV1.sail_mem_write, PreSail.ConcurrencyInterfaceV1.sail_mem_write]
  simp [PreSail.writeBytes, PreSail.writeByte,
    List.ofFn, List.forM, Fin.foldr, Fin.foldr.loop,
    BitVec.extractLsb', BitVec.toNat_setWidth]

/-- Eight-byte `mem_write_value` under kernel config. -/
lemma run_mem_write_value_eight_bytes_of_isInitialized
    (reg_val offset : BitVec 64) (data : BitVec 64)
    (s : SailState) (hs : SailState.isInitialized s)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 8) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true)
    (hconfig : SailState.isValidMemConfig s hs) :
    let paddr_nat :=
      BitVec.toNat ((zero_extend (BitVec.addInt (reg_val + offset) 0)) : BitVec 64)
    let new_mem := ((((((((s.mem.insert paddr_nat
      (BitVec.ofNat 8 data.toNat)).insert
      (paddr_nat + 1) (BitVec.ofNat 8 (data.toNat >>> 8))).insert
      (paddr_nat + 2) (BitVec.ofNat 8 (data.toNat >>> 16))).insert
      (paddr_nat + 3) (BitVec.ofNat 8 (data.toNat >>> 24))).insert
      (paddr_nat + 4) (BitVec.ofNat 8 (data.toNat >>> 32))).insert
      (paddr_nat + 5) (BitVec.ofNat 8 (data.toNat >>> 40))).insert
      (paddr_nat + 6) (BitVec.ofNat 8 (data.toNat >>> 48))).insert
      (paddr_nat + 7) (BitVec.ofNat 8 (data.toNat >>> 56)))
    (mem_write_value
        (physaddr.Physaddr (zero_extend (BitVec.addInt (reg_val + offset) 0))) 8
        data (MemoryAccessType.Store mem_payload.Data)
        page_based_mem_type.PBMT_PMA false false false).run s
      = .ok (.Ok true) { s with mem := new_mem } := by
  obtain ⟨h_cur_privilege, h_mprv_disabled, _, h_htif, h_pma⟩ := hconfig
  have hmprv' : Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 = 0#1 := by
    rw [show Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 =
      BitVec.ofNat 1 (BitVec.toNat (s.regs.get Register.mstatus (hs _)) >>> 17) from rfl]
    exact h_mprv_disabled
  simp [mem_write_value, mem_write_value_meta, mem_write_value_priv_meta,
    Std.ExtDHashMap.get?_eq_some_get (hs _),
    h_cur_privilege, effectivePrivilege, _get_Mstatus_MPRV, hmprv']
  apply run_checked_mem_write_eight_bytes_of_isInitialized reg_val offset data
    s hs h_in_range h_htif h_pma

lemma run_vmem_write_of_width_8
    (rs_addr_bv : BitVec 5)
    (reg_val : BitVec 64)
    (offset : BitVec 64)
    (data : BitVec 64)
    (s : SailState)
    (hs : SailState.isInitialized s)
    (h_reg_val : s.get_reg? rs_addr_bv = some reg_val)
    (h_aligned : is_aligned_vaddr (virtaddr.Virtaddr (reg_val + offset)) 8 = true)
    (hconfig : SailState.isValidMemConfig s hs)
    (_h_does_fit : reg_val.toNat + offset.toNat + 8 < 2 ^ 64)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 8) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true) :
    (vmem_write (.Regidx rs_addr_bv) offset 8 data
      (MemoryAccessType.Store mem_payload.Data) false false false).run s = .ok (.Ok true)
        { s with mem := ((((((((s.mem.insert
          (reg_val + offset).toNat (BitVec.ofNat 8 data.toNat)).insert
          ((reg_val + offset).toNat + 1) (BitVec.ofNat 8 (data.toNat >>> 8))).insert
          ((reg_val + offset).toNat + 2) (BitVec.ofNat 8 (data.toNat >>> 16))).insert
          ((reg_val + offset).toNat + 3) (BitVec.ofNat 8 (data.toNat >>> 24))).insert
          ((reg_val + offset).toNat + 4) (BitVec.ofNat 8 (data.toNat >>> 32))).insert
          ((reg_val + offset).toNat + 5) (BitVec.ofNat 8 (data.toNat >>> 40))).insert
          ((reg_val + offset).toNat + 6) (BitVec.ofNat 8 (data.toNat >>> 48))).insert
          ((reg_val + offset).toNat + 7) (BitVec.ofNat 8 (data.toNat >>> 56))) } := by
  obtain ⟨h_cur_privilege, h_mprv_disabled, h_mseccfg_disabled, h_htif, h_pma⟩ := hconfig
  have hmachine : (Privilege.Machine == Privilege.Machine) = true := rfl
  have hsatp_bare : (SATPMode.Bare == SATPMode.Bare) = true := rfl
  have hfetch : (MemoryAccessType.Store mem_payload.Data !=
      MemoryAccessType.InstructionFetch ()) = true := rfl
  have hrx : rX_bits (regidx.Regidx rs_addr_bv) s = .ok reg_val s := by
    have h := @run_rX_bits rs_addr_bv s
    simp only [EStateM.run] at h
    rw [h, h_reg_val]
  have hmprv' : Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 = 0#1 := by
    rw [show Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 =
      BitVec.ofNat 1 (BitVec.toNat (s.regs.get Register.mstatus (hs _)) >>> 17) from rfl]
    exact h_mprv_disabled
  unfold vmem_write vmem_write_addr ext_data_get_addr
  simp [SailME.run, PreSail.PreSailME.run, ExceptT.run, ExceptT.bind, ExceptT.mk,
    ExceptT.bindCont, ExceptT.lift, ExceptT.map, ExceptT.pure,
    MonadLift.monadLift, liftM, monadLift, Functor.map, Except.map,
    Bind.bind, Pure.pure, SailME.throw, PreSail.PreSailME.throw,
    bind, pure, EStateM.bind, EStateM.map, EStateM.pure, EStateM.run,
    hrx, h_aligned, split_misaligned, misaligned_order, untilFuelM, untilFuelM.go,
    LeanRV64D.Functions.not]
  simp [translateAddr, translationMode, effectivePrivilege,
    SailME.run, PreSail.PreSailME.run, ExceptT.run, ExceptT.bind, ExceptT.mk,
    ExceptT.bindCont, ExceptT.lift, ExceptT.map, ExceptT.pure,
    MonadLift.monadLift, liftM, monadLift,
    bind, pure, EStateM.bind, EStateM.map, EStateM.pure, Functor.map,
    Sail.readReg, PreSail.readReg, run_readReg_of_isInitialized s _ hs,
    Std.ExtDHashMap.get?_eq_some_get (hs _),
    getThe, MonadStateOf.get, MonadState.get, get, EStateM.get,
    modifyGet, MonadStateOf.modifyGet, MonadState.modifyGet, EStateM.modifyGet,
    privLevel_bits_backwards, privLevel_bits_forwards,
    hmprv', h_cur_privilege, hmachine, hsatp_bare,
    hfetch, is_shadow_stack_access]
  simp [mem_write_ea, is_store_conditional, write_kind_of_flags, hfetch,
    EStateM.map, EStateM.bind, EStateM.pure, EStateM.run,
    bind, Bind.bind, pure, Pure.pure, Functor.map,
    ExceptT.bindCont, ExceptT.pure, ExceptT.bind]
  have hconfig : SailState.isValidMemConfig s hs :=
    ⟨h_cur_privilege, h_mprv_disabled, h_mseccfg_disabled, h_htif, h_pma⟩
  have h := run_mem_write_value_eight_bytes_of_isInitialized reg_val offset data s hs h_in_range
    hconfig
  simp only [EStateM.run] at h
  simp [zero_extend, BitVec.addInt, Sail.BitVec.zeroExtend] at h ⊢
  rw [show Sail.BitVec.extractLsb data 63 0 = data from by
    simp [Sail.BitVec.extractLsb, BitVec.extractLsb, BitVec.extractLsb']]
  conv_lhs => rw [h]
  rfl

/-- Four-byte `checked_mem_write` under kernel config (width-4 analogue, for `SW`). -/
lemma run_checked_mem_write_four_bytes_of_isInitialized
    (reg_val offset : BitVec 64) (data : BitVec 32)
    (s : SailState) (hs : SailState.isInitialized s)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 4) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true)
    (h_htif : s.regs.get Register.htif_tohost_base (hs _) = none)
    (h_pma : s.regs.get Register.pma_regions (hs _) = [SP1_PMA_Region]) :
    let paddr_nat :=
      BitVec.toNat ((zero_extend (BitVec.addInt (reg_val + offset) 0)) : BitVec 64)
    let new_mem := ((((s.mem.insert paddr_nat
      (BitVec.ofNat 8 data.toNat)).insert
      (paddr_nat + 1) (BitVec.ofNat 8 (data.toNat >>> 8))).insert
      (paddr_nat + 2) (BitVec.ofNat 8 (data.toNat >>> 16))).insert
      (paddr_nat + 3) (BitVec.ofNat 8 (data.toNat >>> 24)))
    (checked_mem_write
        (physaddr.Physaddr (zero_extend (BitVec.addInt (reg_val + offset) 0))) 4
        data (MemoryAccessType.Store mem_payload.Data)
        page_based_mem_type.PBMT_PMA Privilege.Machine () false false false).run s
      = .ok (.Ok true) { s with mem := new_mem } := by
  simp [checked_mem_write, phys_access_check, pmpCheck, SailME.run, PreSail.PreSailME.run]
  simp [pmaCheck, Std.ExtDHashMap.get?_eq_some_get (hs _), h_pma]
  simp [matching_pma_region, matching_pma_region_bits_range]
  erw [h_in_range]
  simp [EStateM.Result.map, accessFaultFromAccessType,
    pma_misaligned_exception, SP1_PMA]
  simp [is_aligned_paddr, override_PMA, - EStateM.run_bind]
  erw [EStateM.run_bind, run_within_mmio_writable_mmio reg_val offset 4 s hs h_htif]
  simp [write_kind_of_flags, write_ram]
  simp [ConcurrencyInterfaceV1.sail_mem_write, PreSail.ConcurrencyInterfaceV1.sail_mem_write]
  simp [PreSail.writeBytes, PreSail.writeByte,
    List.ofFn, List.forM, Fin.foldr, Fin.foldr.loop,
    BitVec.extractLsb', BitVec.toNat_setWidth]

/-- Four-byte `mem_write_value` under kernel config. -/
lemma run_mem_write_value_four_bytes_of_isInitialized
    (reg_val offset : BitVec 64) (data : BitVec 32)
    (s : SailState) (hs : SailState.isInitialized s)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 4) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true)
    (hconfig : SailState.isValidMemConfig s hs) :
    let paddr_nat :=
      BitVec.toNat ((zero_extend (BitVec.addInt (reg_val + offset) 0)) : BitVec 64)
    let new_mem := ((((s.mem.insert paddr_nat
      (BitVec.ofNat 8 data.toNat)).insert
      (paddr_nat + 1) (BitVec.ofNat 8 (data.toNat >>> 8))).insert
      (paddr_nat + 2) (BitVec.ofNat 8 (data.toNat >>> 16))).insert
      (paddr_nat + 3) (BitVec.ofNat 8 (data.toNat >>> 24)))
    (mem_write_value
        (physaddr.Physaddr (zero_extend (BitVec.addInt (reg_val + offset) 0))) 4
        data (MemoryAccessType.Store mem_payload.Data)
        page_based_mem_type.PBMT_PMA false false false).run s
      = .ok (.Ok true) { s with mem := new_mem } := by
  obtain ⟨h_cur_privilege, h_mprv_disabled, _, h_htif, h_pma⟩ := hconfig
  have hmprv' : Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 = 0#1 := by
    rw [show Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 =
      BitVec.ofNat 1 (BitVec.toNat (s.regs.get Register.mstatus (hs _)) >>> 17) from rfl]
    exact h_mprv_disabled
  simp [mem_write_value, mem_write_value_meta, mem_write_value_priv_meta,
    Std.ExtDHashMap.get?_eq_some_get (hs _),
    h_cur_privilege, effectivePrivilege, _get_Mstatus_MPRV, hmprv']
  apply run_checked_mem_write_four_bytes_of_isInitialized reg_val offset data
    s hs h_in_range h_htif h_pma

lemma run_vmem_write_of_width_4
    (rs_addr_bv : BitVec 5)
    (reg_val : BitVec 64)
    (offset : BitVec 64)
    (data : BitVec 32)
    (s : SailState)
    (hs : SailState.isInitialized s)
    (h_reg_val : s.get_reg? rs_addr_bv = some reg_val)
    (h_aligned : is_aligned_vaddr (virtaddr.Virtaddr (reg_val + offset)) 4 = true)
    (hconfig : SailState.isValidMemConfig s hs)
    (_h_does_fit : reg_val.toNat + offset.toNat + 4 < 2 ^ 64)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 4) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true) :
    (vmem_write (.Regidx rs_addr_bv) offset 4 data
      (MemoryAccessType.Store mem_payload.Data) false false false).run s = .ok (.Ok true)
        { s with mem := ((((s.mem.insert
          (reg_val + offset).toNat (BitVec.ofNat 8 data.toNat)).insert
          ((reg_val + offset).toNat + 1) (BitVec.ofNat 8 (data.toNat >>> 8))).insert
          ((reg_val + offset).toNat + 2) (BitVec.ofNat 8 (data.toNat >>> 16))).insert
          ((reg_val + offset).toNat + 3) (BitVec.ofNat 8 (data.toNat >>> 24))) } := by
  obtain ⟨h_cur_privilege, h_mprv_disabled, h_mseccfg_disabled, h_htif, h_pma⟩ := hconfig
  have hmachine : (Privilege.Machine == Privilege.Machine) = true := rfl
  have hsatp_bare : (SATPMode.Bare == SATPMode.Bare) = true := rfl
  have hfetch : (MemoryAccessType.Store mem_payload.Data !=
      MemoryAccessType.InstructionFetch ()) = true := rfl
  have hrx : rX_bits (regidx.Regidx rs_addr_bv) s = .ok reg_val s := by
    have h := @run_rX_bits rs_addr_bv s
    simp only [EStateM.run] at h
    rw [h, h_reg_val]
  have hmprv' : Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 = 0#1 := by
    rw [show Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 =
      BitVec.ofNat 1 (BitVec.toNat (s.regs.get Register.mstatus (hs _)) >>> 17) from rfl]
    exact h_mprv_disabled
  unfold vmem_write vmem_write_addr ext_data_get_addr
  simp [SailME.run, PreSail.PreSailME.run, ExceptT.run, ExceptT.bind, ExceptT.mk,
    ExceptT.bindCont, ExceptT.lift, ExceptT.map, ExceptT.pure,
    MonadLift.monadLift, liftM, monadLift, Functor.map, Except.map,
    Bind.bind, Pure.pure, SailME.throw, PreSail.PreSailME.throw,
    bind, pure, EStateM.bind, EStateM.map, EStateM.pure, EStateM.run,
    hrx, h_aligned, split_misaligned, misaligned_order, untilFuelM, untilFuelM.go,
    LeanRV64D.Functions.not]
  simp [translateAddr, translationMode, effectivePrivilege,
    SailME.run, PreSail.PreSailME.run, ExceptT.run, ExceptT.bind, ExceptT.mk,
    ExceptT.bindCont, ExceptT.lift, ExceptT.map, ExceptT.pure,
    MonadLift.monadLift, liftM, monadLift,
    bind, pure, EStateM.bind, EStateM.map, EStateM.pure, Functor.map,
    Sail.readReg, PreSail.readReg, run_readReg_of_isInitialized s _ hs,
    Std.ExtDHashMap.get?_eq_some_get (hs _),
    getThe, MonadStateOf.get, MonadState.get, get, EStateM.get,
    modifyGet, MonadStateOf.modifyGet, MonadState.modifyGet, EStateM.modifyGet,
    privLevel_bits_backwards, privLevel_bits_forwards,
    hmprv', h_cur_privilege, hmachine, hsatp_bare,
    hfetch, is_shadow_stack_access]
  simp [mem_write_ea, is_store_conditional, write_kind_of_flags, hfetch,
    EStateM.map, EStateM.bind, EStateM.pure, EStateM.run,
    bind, Bind.bind, pure, Pure.pure, Functor.map,
    ExceptT.bindCont, ExceptT.pure, ExceptT.bind]
  have hconfig : SailState.isValidMemConfig s hs :=
    ⟨h_cur_privilege, h_mprv_disabled, h_mseccfg_disabled, h_htif, h_pma⟩
  have h := run_mem_write_value_four_bytes_of_isInitialized reg_val offset data s hs h_in_range
    hconfig
  simp only [EStateM.run] at h
  simp [zero_extend, BitVec.addInt, Sail.BitVec.zeroExtend] at h ⊢
  rw [show Sail.BitVec.extractLsb data 31 0 = data from by
    simp [Sail.BitVec.extractLsb, BitVec.extractLsb, BitVec.extractLsb']]
  conv_lhs => rw [h]
  rfl

/-- Two-byte `checked_mem_read` under kernel config (the width-2 analogue, for `LH`/`LHU`). -/
lemma run_checked_mem_read_two_bytes_of_isInitialized
    (reg_val offset : BitVec 64)
    (data₀ data₁ : BitVec 8)
    (s : SailState) (hs : SailState.isInitialized s)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 2) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true)
    (h_htif : s.regs.get Register.htif_tohost_base (hs _) = none)
    (h_pma : s.regs.get Register.pma_regions (hs _) = [SP1_PMA_Region])
    (hmem₀ : s.mem[(reg_val + offset).toNat]? = some data₀)
    (hmem₁ : s.mem[(reg_val + offset).toNat + 1]? = some data₁) :
    (checked_mem_read (MemoryAccessType.Load mem_payload.Data)
        page_based_mem_type.PBMT_PMA Privilege.Machine
        (physaddr.Physaddr (zero_extend (BitVec.addInt (reg_val + offset) 0))) 2
        false false false false).run s
      = .ok (.Ok (data₁ ++ data₀, ())) s := by
  simp [checked_mem_read, phys_access_check, pmpCheck, SailME.run, PreSail.PreSailME.run]
  simp [pmaCheck, Std.ExtDHashMap.get?_eq_some_get (hs _), h_pma]
  simp [matching_pma_region, matching_pma_region_bits_range]
  erw [h_in_range]
  simp [EStateM.Result.map, accessFaultFromAccessType,
    pma_misaligned_exception, SP1_PMA]
  simp [is_aligned_paddr, override_PMA, - EStateM.run_bind]
  erw [EStateM.run_bind, run_within_mmio_readable_mmio reg_val offset 2 s hs h_htif]
  simp [read_kind_of_flags, read_ram]
  simp [ConcurrencyInterfaceV1.sail_mem_read, PreSail.ConcurrencyInterfaceV1.sail_mem_read]
  simp only [zero_extend, BitVec.addInt, Sail.BitVec.zeroExtend]
  have hmod : (reg_val + offset).toNat = (reg_val.toNat + offset.toNat) % 18446744073709551616 :=
    BitVec.toNat_add reg_val offset
  have hmem₀' : s.mem[(reg_val.toNat + offset.toNat) % 18446744073709551616]? = some data₀ := by
    rw [← hmod]; exact hmem₀
  have hmem₁' : s.mem[(reg_val.toNat + offset.toNat) % 18446744073709551616 + 1]? = some data₁ := by
    rw [← hmod]; exact hmem₁
  simp [PreSail.readBytes, PreSail.readByte,
    hmem₀', hmem₁',
    bind, Bind.bind, EStateM.bind, EStateM.map, EStateM.pure,
    EStateM.run, pure, Pure.pure, Functor.map, getThe, MonadStateOf.get, MonadState.get,
    get, EStateM.get, MemoryOpResult_add_meta]

/-- Two-byte `mem_read` under kernel config. -/
lemma run_mem_read_two_bytes_of_isInitialized
    (reg_val offset : BitVec 64)
    (data₀ data₁ : BitVec 8)
    (s : SailState) (hs : SailState.isInitialized s)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 2) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true)
    (hconfig : SailState.isValidMemConfig s hs)
    (hmem₀ : s.mem[(reg_val + offset).toNat]? = some data₀)
    (hmem₁ : s.mem[(reg_val + offset).toNat + 1]? = some data₁) :
    (mem_read (MemoryAccessType.Load mem_payload.Data)
        page_based_mem_type.PBMT_PMA
        (physaddr.Physaddr (zero_extend (BitVec.addInt (reg_val + offset) 0))) 2
        false false false).run s
      = .ok (.Ok (data₁ ++ data₀)) s := by
  obtain ⟨h_cur_privilege, h_mprv_disabled, _, h_htif, h_pma⟩ := hconfig
  have hmprv' : Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 = 0#1 := by
    rw [show Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 =
      BitVec.ofNat 1 (BitVec.toNat (s.regs.get Register.mstatus (hs _)) >>> 17) from rfl]
    exact h_mprv_disabled
  simp [mem_read, mem_read_priv, mem_read_priv_meta, MemoryOpResult_drop_meta,
    Std.ExtDHashMap.get?_eq_some_get (hs _),
    h_cur_privilege, effectivePrivilege, _get_Mstatus_MPRV, hmprv']
  exact ⟨_, run_checked_mem_read_two_bytes_of_isInitialized reg_val offset
    data₀ data₁ s hs h_in_range h_htif h_pma
    hmem₀ hmem₁, rfl⟩

lemma run_vmem_read_of_width_2'
    (rs_addr_bv : BitVec 5)
    (reg_val : BitVec 64)
    (offset : BitVec 64)
    (data₀ data₁ : BitVec 8)
    (s : SailState)
    (hs : SailState.isInitialized s)
    (h_reg_val : s.get_reg? rs_addr_bv = some reg_val)
    (h_aligned : is_aligned_vaddr (virtaddr.Virtaddr (reg_val + offset)) 2 = true)
    (hconfig : SailState.isValidMemConfig s hs)
    (h_does_fit : reg_val.toNat + offset.toNat + 2 < 2 ^ 64)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 2) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true)
    (hmem₀ : s.mem[reg_val.toNat + offset.toNat]? = some data₀)
    (hmem₁ : s.mem[reg_val.toNat + offset.toNat + 1]? = some data₁) :
    let width := 2
    let data := data₁ ++ data₀
    (vmem_read (.Regidx rs_addr_bv) offset width (MemoryAccessType.Load mem_payload.Data)
      false false false).run s = .ok (.Ok data) s := by
  have h_mprv_disabled := hconfig.h_mprv_disabled
  have h_cur_privilege := hconfig.h_cur_privilege
  have hmachine : (Privilege.Machine == Privilege.Machine) = true := rfl
  have hsatp_bare : (SATPMode.Bare == SATPMode.Bare) = true := rfl
  have hfetch : (MemoryAccessType.Load mem_payload.Data !=
      MemoryAccessType.InstructionFetch ()) = true := rfl
  have hrx : rX_bits (regidx.Regidx rs_addr_bv) s = .ok reg_val s := by
    have h := @run_rX_bits rs_addr_bv s
    simp only [EStateM.run] at h
    rw [h, h_reg_val]
  have hmod : (reg_val + offset).toNat = reg_val.toNat + offset.toNat := by
    rw [BitVec.toNat_add, Nat.mod_eq_of_lt]; omega
  have hmem₀' : s.mem[(reg_val + offset).toNat]? = some data₀ := by rw [hmod]; exact hmem₀
  have hmem₁' : s.mem[(reg_val + offset).toNat + 1]? = some data₁ := by rw [hmod]; exact hmem₁
  have hmprv' : Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 = 0#1 := by
    rw [show Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 =
      BitVec.ofNat 1 (BitVec.toNat (s.regs.get Register.mstatus (hs _)) >>> 17) from rfl]
    exact h_mprv_disabled
  unfold vmem_read vmem_read_addr ext_data_get_addr
  simp [SailME.run, PreSail.PreSailME.run, ExceptT.run, ExceptT.bind, ExceptT.mk,
    ExceptT.bindCont, ExceptT.lift, ExceptT.map, ExceptT.pure,
    MonadLift.monadLift, liftM, monadLift, Functor.map, Except.map,
    Bind.bind, Pure.pure, SailME.throw, PreSail.PreSailME.throw,
    bind, pure, EStateM.bind, EStateM.map, EStateM.pure, EStateM.run,
    hrx, h_aligned, split_misaligned, misaligned_order, untilFuelM, untilFuelM.go,
    LeanRV64D.Functions.not]
  simp [translateAddr, translationMode, effectivePrivilege,
    SailME.run, PreSail.PreSailME.run, ExceptT.run, ExceptT.bind, ExceptT.mk,
    ExceptT.bindCont, ExceptT.lift, ExceptT.map, ExceptT.pure,
    MonadLift.monadLift, liftM, monadLift,
    bind, pure, EStateM.bind, EStateM.map, EStateM.pure, Functor.map,
    Sail.readReg, PreSail.readReg, run_readReg_of_isInitialized s _ hs,
    Std.ExtDHashMap.get?_eq_some_get (hs _),
    getThe, MonadStateOf.get, MonadState.get, get, EStateM.get,
    modifyGet, MonadStateOf.modifyGet, MonadState.modifyGet, EStateM.modifyGet,
    privLevel_bits_backwards, privLevel_bits_forwards,
    hmprv', h_cur_privilege, hmachine, hsatp_bare,
    hfetch, is_shadow_stack_access]
  have h := run_mem_read_two_bytes_of_isInitialized reg_val offset
    data₀ data₁ s hs h_in_range hconfig
    hmem₀' hmem₁'
  simp only [EStateM.run] at h
  simp [zero_extend, BitVec.addInt, Sail.BitVec.zeroExtend] at h ⊢
  conv_lhs => rw [h]
  simp [BitVec.updateSubrange, BitVec.updateSubrange', Sail.BitVec.updateSubrange,
    BitVec.setWidth_eq]
  rfl

/-- Two-byte `checked_mem_write` under kernel config (width-2 analogue, for `SH`). -/
lemma run_checked_mem_write_two_bytes_of_isInitialized
    (reg_val offset : BitVec 64) (data : BitVec 16)
    (s : SailState) (hs : SailState.isInitialized s)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 2) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true)
    (h_htif : s.regs.get Register.htif_tohost_base (hs _) = none)
    (h_pma : s.regs.get Register.pma_regions (hs _) = [SP1_PMA_Region]) :
    let paddr_nat :=
      BitVec.toNat ((zero_extend (BitVec.addInt (reg_val + offset) 0)) : BitVec 64)
    let new_mem := ((s.mem.insert paddr_nat
      (BitVec.ofNat 8 data.toNat)).insert
      (paddr_nat + 1) (BitVec.ofNat 8 (data.toNat >>> 8)))
    (checked_mem_write
        (physaddr.Physaddr (zero_extend (BitVec.addInt (reg_val + offset) 0))) 2
        data (MemoryAccessType.Store mem_payload.Data)
        page_based_mem_type.PBMT_PMA Privilege.Machine () false false false).run s
      = .ok (.Ok true) { s with mem := new_mem } := by
  simp [checked_mem_write, phys_access_check, pmpCheck, SailME.run, PreSail.PreSailME.run]
  simp [pmaCheck, Std.ExtDHashMap.get?_eq_some_get (hs _), h_pma]
  simp [matching_pma_region, matching_pma_region_bits_range]
  erw [h_in_range]
  simp [EStateM.Result.map, accessFaultFromAccessType,
    pma_misaligned_exception, SP1_PMA]
  simp [is_aligned_paddr, override_PMA, - EStateM.run_bind]
  erw [EStateM.run_bind, run_within_mmio_writable_mmio reg_val offset 2 s hs h_htif]
  simp [write_kind_of_flags, write_ram]
  simp [ConcurrencyInterfaceV1.sail_mem_write, PreSail.ConcurrencyInterfaceV1.sail_mem_write]
  simp [PreSail.writeBytes, PreSail.writeByte,
    List.ofFn, List.forM, Fin.foldr, Fin.foldr.loop,
    BitVec.extractLsb', BitVec.toNat_setWidth]

/-- Two-byte `mem_write_value` under kernel config. -/
lemma run_mem_write_value_two_bytes_of_isInitialized
    (reg_val offset : BitVec 64) (data : BitVec 16)
    (s : SailState) (hs : SailState.isInitialized s)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 2) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true)
    (hconfig : SailState.isValidMemConfig s hs) :
    let paddr_nat :=
      BitVec.toNat ((zero_extend (BitVec.addInt (reg_val + offset) 0)) : BitVec 64)
    let new_mem := ((s.mem.insert paddr_nat
      (BitVec.ofNat 8 data.toNat)).insert
      (paddr_nat + 1) (BitVec.ofNat 8 (data.toNat >>> 8)))
    (mem_write_value
        (physaddr.Physaddr (zero_extend (BitVec.addInt (reg_val + offset) 0))) 2
        data (MemoryAccessType.Store mem_payload.Data)
        page_based_mem_type.PBMT_PMA false false false).run s
      = .ok (.Ok true) { s with mem := new_mem } := by
  obtain ⟨h_cur_privilege, h_mprv_disabled, _, h_htif, h_pma⟩ := hconfig
  have hmprv' : Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 = 0#1 := by
    rw [show Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 =
      BitVec.ofNat 1 (BitVec.toNat (s.regs.get Register.mstatus (hs _)) >>> 17) from rfl]
    exact h_mprv_disabled
  simp [mem_write_value, mem_write_value_meta, mem_write_value_priv_meta,
    Std.ExtDHashMap.get?_eq_some_get (hs _),
    h_cur_privilege, effectivePrivilege, _get_Mstatus_MPRV, hmprv']
  apply run_checked_mem_write_two_bytes_of_isInitialized reg_val offset data
    s hs h_in_range h_htif h_pma

lemma run_vmem_write_of_width_2
    (rs_addr_bv : BitVec 5)
    (reg_val : BitVec 64)
    (offset : BitVec 64)
    (data : BitVec 16)
    (s : SailState)
    (hs : SailState.isInitialized s)
    (h_reg_val : s.get_reg? rs_addr_bv = some reg_val)
    (h_aligned : is_aligned_vaddr (virtaddr.Virtaddr (reg_val + offset)) 2 = true)
    (hconfig : SailState.isValidMemConfig s hs)
    (_h_does_fit : reg_val.toNat + offset.toNat + 2 < 2 ^ 64)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 2) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true) :
    (vmem_write (.Regidx rs_addr_bv) offset 2 data
      (MemoryAccessType.Store mem_payload.Data) false false false).run s = .ok (.Ok true)
        { s with mem := ((s.mem.insert
          (reg_val + offset).toNat (BitVec.ofNat 8 data.toNat)).insert
          ((reg_val + offset).toNat + 1) (BitVec.ofNat 8 (data.toNat >>> 8))) } := by
  obtain ⟨h_cur_privilege, h_mprv_disabled, h_mseccfg_disabled, h_htif, h_pma⟩ := hconfig
  have hmachine : (Privilege.Machine == Privilege.Machine) = true := rfl
  have hsatp_bare : (SATPMode.Bare == SATPMode.Bare) = true := rfl
  have hfetch : (MemoryAccessType.Store mem_payload.Data !=
      MemoryAccessType.InstructionFetch ()) = true := rfl
  have hrx : rX_bits (regidx.Regidx rs_addr_bv) s = .ok reg_val s := by
    have h := @run_rX_bits rs_addr_bv s
    simp only [EStateM.run] at h
    rw [h, h_reg_val]
  have hmprv' : Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 = 0#1 := by
    rw [show Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 =
      BitVec.ofNat 1 (BitVec.toNat (s.regs.get Register.mstatus (hs _)) >>> 17) from rfl]
    exact h_mprv_disabled
  unfold vmem_write vmem_write_addr ext_data_get_addr
  simp [SailME.run, PreSail.PreSailME.run, ExceptT.run, ExceptT.bind, ExceptT.mk,
    ExceptT.bindCont, ExceptT.lift, ExceptT.map, ExceptT.pure,
    MonadLift.monadLift, liftM, monadLift, Functor.map, Except.map,
    Bind.bind, Pure.pure, SailME.throw, PreSail.PreSailME.throw,
    bind, pure, EStateM.bind, EStateM.map, EStateM.pure, EStateM.run,
    hrx, h_aligned, split_misaligned, misaligned_order, untilFuelM, untilFuelM.go,
    LeanRV64D.Functions.not]
  simp [translateAddr, translationMode, effectivePrivilege,
    SailME.run, PreSail.PreSailME.run, ExceptT.run, ExceptT.bind, ExceptT.mk,
    ExceptT.bindCont, ExceptT.lift, ExceptT.map, ExceptT.pure,
    MonadLift.monadLift, liftM, monadLift,
    bind, pure, EStateM.bind, EStateM.map, EStateM.pure, Functor.map,
    Sail.readReg, PreSail.readReg, run_readReg_of_isInitialized s _ hs,
    Std.ExtDHashMap.get?_eq_some_get (hs _),
    getThe, MonadStateOf.get, MonadState.get, get, EStateM.get,
    modifyGet, MonadStateOf.modifyGet, MonadState.modifyGet, EStateM.modifyGet,
    privLevel_bits_backwards, privLevel_bits_forwards,
    hmprv', h_cur_privilege, hmachine, hsatp_bare,
    hfetch, is_shadow_stack_access]
  simp [mem_write_ea, is_store_conditional, write_kind_of_flags, hfetch,
    EStateM.map, EStateM.bind, EStateM.pure, EStateM.run,
    bind, Bind.bind, pure, Pure.pure, Functor.map,
    ExceptT.bindCont, ExceptT.pure, ExceptT.bind]
  have hconfig : SailState.isValidMemConfig s hs :=
    ⟨h_cur_privilege, h_mprv_disabled, h_mseccfg_disabled, h_htif, h_pma⟩
  have h := run_mem_write_value_two_bytes_of_isInitialized reg_val offset data s hs h_in_range
    hconfig
  simp only [EStateM.run] at h
  simp [zero_extend, BitVec.addInt, Sail.BitVec.zeroExtend] at h ⊢
  rw [show Sail.BitVec.extractLsb data 15 0 = data from by
    simp [Sail.BitVec.extractLsb, BitVec.extractLsb, BitVec.extractLsb']]
  conv_lhs => rw [h]
  rfl

/-- One-byte `checked_mem_read` under kernel config (the width-1 analogue, for `LB`/`LBU`). -/
lemma run_checked_mem_read_one_byte_of_isInitialized
    (reg_val offset : BitVec 64)
    (data₀ : BitVec 8)
    (s : SailState) (hs : SailState.isInitialized s)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 1) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true)
    (h_htif : s.regs.get Register.htif_tohost_base (hs _) = none)
    (h_pma : s.regs.get Register.pma_regions (hs _) = [SP1_PMA_Region])
    (hmem₀ : s.mem[(reg_val + offset).toNat]? = some data₀) :
    (checked_mem_read (MemoryAccessType.Load mem_payload.Data)
        page_based_mem_type.PBMT_PMA Privilege.Machine
        (physaddr.Physaddr (zero_extend (BitVec.addInt (reg_val + offset) 0))) 1
        false false false false).run s
      = .ok (.Ok (data₀, ())) s := by
  simp [checked_mem_read, phys_access_check, pmpCheck, SailME.run, PreSail.PreSailME.run]
  simp [pmaCheck, Std.ExtDHashMap.get?_eq_some_get (hs _), h_pma]
  simp [matching_pma_region, matching_pma_region_bits_range]
  erw [h_in_range]
  simp [EStateM.Result.map, accessFaultFromAccessType,
    pma_misaligned_exception, SP1_PMA]
  simp [is_aligned_paddr, override_PMA, - EStateM.run_bind]
  erw [EStateM.run_bind, run_within_mmio_readable_mmio reg_val offset 1 s hs h_htif]
  simp [read_kind_of_flags, read_ram]
  simp [ConcurrencyInterfaceV1.sail_mem_read, PreSail.ConcurrencyInterfaceV1.sail_mem_read]
  simp only [zero_extend, BitVec.addInt, Sail.BitVec.zeroExtend]
  have hmod : (reg_val + offset).toNat = (reg_val.toNat + offset.toNat) % 18446744073709551616 :=
    BitVec.toNat_add reg_val offset
  have hmem₀' : s.mem[(reg_val.toNat + offset.toNat) % 18446744073709551616]? = some data₀ := by
    rw [← hmod]; exact hmem₀
  simp [PreSail.readBytes, PreSail.readByte,
    hmem₀',
    bind, Bind.bind, EStateM.bind, EStateM.map, EStateM.pure,
    EStateM.run, pure, Pure.pure, Functor.map, getThe, MonadStateOf.get, MonadState.get,
    get, EStateM.get, MemoryOpResult_add_meta]

/-- One-byte `mem_read` under kernel config. -/
lemma run_mem_read_one_byte_of_isInitialized
    (reg_val offset : BitVec 64)
    (data₀ : BitVec 8)
    (s : SailState) (hs : SailState.isInitialized s)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 1) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true)
    (hconfig : SailState.isValidMemConfig s hs)
    (hmem₀ : s.mem[(reg_val + offset).toNat]? = some data₀) :
    (mem_read (MemoryAccessType.Load mem_payload.Data)
        page_based_mem_type.PBMT_PMA
        (physaddr.Physaddr (zero_extend (BitVec.addInt (reg_val + offset) 0))) 1
        false false false).run s
      = .ok (.Ok data₀) s := by
  obtain ⟨h_cur_privilege, h_mprv_disabled, _, h_htif, h_pma⟩ := hconfig
  have hmprv' : Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 = 0#1 := by
    rw [show Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 =
      BitVec.ofNat 1 (BitVec.toNat (s.regs.get Register.mstatus (hs _)) >>> 17) from rfl]
    exact h_mprv_disabled
  simp [mem_read, mem_read_priv, mem_read_priv_meta, MemoryOpResult_drop_meta,
    Std.ExtDHashMap.get?_eq_some_get (hs _),
    h_cur_privilege, effectivePrivilege, _get_Mstatus_MPRV, hmprv']
  exact ⟨_, run_checked_mem_read_one_byte_of_isInitialized reg_val offset
    data₀ s hs h_in_range h_htif h_pma hmem₀, rfl⟩

lemma run_vmem_read_of_width_1'
    (rs_addr_bv : BitVec 5)
    (reg_val : BitVec 64)
    (offset : BitVec 64)
    (data₀ : BitVec 8)
    (s : SailState)
    (hs : SailState.isInitialized s)
    (h_reg_val : s.get_reg? rs_addr_bv = some reg_val)
    (h_aligned : is_aligned_vaddr (virtaddr.Virtaddr (reg_val + offset)) 1 = true)
    (hconfig : SailState.isValidMemConfig s hs)
    (h_does_fit : reg_val.toNat + offset.toNat + 1 < 2 ^ 64)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 1) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true)
    (hmem₀ : s.mem[reg_val.toNat + offset.toNat]? = some data₀) :
    let width := 1
    let data := data₀
    (vmem_read (.Regidx rs_addr_bv) offset width (MemoryAccessType.Load mem_payload.Data)
      false false false).run s = .ok (.Ok data) s := by
  have h_mprv_disabled := hconfig.h_mprv_disabled
  have h_cur_privilege := hconfig.h_cur_privilege
  have hmachine : (Privilege.Machine == Privilege.Machine) = true := rfl
  have hsatp_bare : (SATPMode.Bare == SATPMode.Bare) = true := rfl
  have hfetch : (MemoryAccessType.Load mem_payload.Data !=
      MemoryAccessType.InstructionFetch ()) = true := rfl
  have hrx : rX_bits (regidx.Regidx rs_addr_bv) s = .ok reg_val s := by
    have h := @run_rX_bits rs_addr_bv s
    simp only [EStateM.run] at h
    rw [h, h_reg_val]
  have hmod : (reg_val + offset).toNat = reg_val.toNat + offset.toNat := by
    rw [BitVec.toNat_add, Nat.mod_eq_of_lt]; omega
  have hmem₀' : s.mem[(reg_val + offset).toNat]? = some data₀ := by rw [hmod]; exact hmem₀
  have hmprv' : Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 = 0#1 := by
    rw [show Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 =
      BitVec.ofNat 1 (BitVec.toNat (s.regs.get Register.mstatus (hs _)) >>> 17) from rfl]
    exact h_mprv_disabled
  unfold vmem_read vmem_read_addr ext_data_get_addr
  simp [SailME.run, PreSail.PreSailME.run, ExceptT.run, ExceptT.bind, ExceptT.mk,
    ExceptT.bindCont, ExceptT.lift, ExceptT.map, ExceptT.pure,
    MonadLift.monadLift, liftM, monadLift, Functor.map, Except.map,
    Bind.bind, Pure.pure, SailME.throw, PreSail.PreSailME.throw,
    bind, pure, EStateM.bind, EStateM.map, EStateM.pure, EStateM.run,
    hrx, h_aligned, split_misaligned, misaligned_order, untilFuelM, untilFuelM.go,
    LeanRV64D.Functions.not]
  simp [translateAddr, translationMode, effectivePrivilege,
    SailME.run, PreSail.PreSailME.run, ExceptT.run, ExceptT.bind, ExceptT.mk,
    ExceptT.bindCont, ExceptT.lift, ExceptT.map, ExceptT.pure,
    MonadLift.monadLift, liftM, monadLift,
    bind, pure, EStateM.bind, EStateM.map, EStateM.pure, Functor.map,
    Sail.readReg, PreSail.readReg, run_readReg_of_isInitialized s _ hs,
    Std.ExtDHashMap.get?_eq_some_get (hs _),
    getThe, MonadStateOf.get, MonadState.get, get, EStateM.get,
    modifyGet, MonadStateOf.modifyGet, MonadState.modifyGet, EStateM.modifyGet,
    privLevel_bits_backwards, privLevel_bits_forwards,
    hmprv', h_cur_privilege, hmachine, hsatp_bare,
    hfetch, is_shadow_stack_access]
  have h := run_mem_read_one_byte_of_isInitialized reg_val offset
    data₀ s hs h_in_range hconfig hmem₀'
  simp only [EStateM.run] at h
  simp [zero_extend, BitVec.addInt, Sail.BitVec.zeroExtend] at h ⊢
  conv_lhs => rw [h]
  simp [BitVec.updateSubrange, BitVec.updateSubrange', Sail.BitVec.updateSubrange,
    BitVec.setWidth_eq]
  rfl

/-- One-byte `checked_mem_write` under kernel config (width-1 analogue, for `SB`). -/
lemma run_checked_mem_write_one_byte_of_isInitialized
    (reg_val offset : BitVec 64) (data : BitVec 8)
    (s : SailState) (hs : SailState.isInitialized s)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 1) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true)
    (h_htif : s.regs.get Register.htif_tohost_base (hs _) = none)
    (h_pma : s.regs.get Register.pma_regions (hs _) = [SP1_PMA_Region]) :
    let paddr_nat :=
      BitVec.toNat ((zero_extend (BitVec.addInt (reg_val + offset) 0)) : BitVec 64)
    let new_mem := s.mem.insert paddr_nat (BitVec.ofNat 8 data.toNat)
    (checked_mem_write
        (physaddr.Physaddr (zero_extend (BitVec.addInt (reg_val + offset) 0))) 1
        data (MemoryAccessType.Store mem_payload.Data)
        page_based_mem_type.PBMT_PMA Privilege.Machine () false false false).run s
      = .ok (.Ok true) { s with mem := new_mem } := by
  simp [checked_mem_write, phys_access_check, pmpCheck, SailME.run, PreSail.PreSailME.run]
  simp [pmaCheck, Std.ExtDHashMap.get?_eq_some_get (hs _), h_pma]
  simp [matching_pma_region, matching_pma_region_bits_range]
  erw [h_in_range]
  simp [EStateM.Result.map, accessFaultFromAccessType,
    pma_misaligned_exception, SP1_PMA]
  simp [is_aligned_paddr, override_PMA, - EStateM.run_bind]
  erw [EStateM.run_bind, run_within_mmio_writable_mmio reg_val offset 1 s hs h_htif]
  simp [write_kind_of_flags, write_ram]
  simp [ConcurrencyInterfaceV1.sail_mem_write, PreSail.ConcurrencyInterfaceV1.sail_mem_write]
  simp [PreSail.writeBytes, PreSail.writeByte,
    List.ofFn, List.forM, Fin.foldr, Fin.foldr.loop,
    BitVec.extractLsb', BitVec.toNat_setWidth]

/-- One-byte `mem_write_value` under kernel config. -/
lemma run_mem_write_value_one_byte_of_isInitialized
    (reg_val offset : BitVec 64) (data : BitVec 8)
    (s : SailState) (hs : SailState.isInitialized s)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 1) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true)
    (hconfig : SailState.isValidMemConfig s hs) :
    let paddr_nat :=
      BitVec.toNat ((zero_extend (BitVec.addInt (reg_val + offset) 0)) : BitVec 64)
    let new_mem := s.mem.insert paddr_nat data
    (mem_write_value
        (physaddr.Physaddr (zero_extend (BitVec.addInt (reg_val + offset) 0))) 1
        data (MemoryAccessType.Store mem_payload.Data)
        page_based_mem_type.PBMT_PMA false false false).run s
      = .ok (.Ok true) { s with mem := new_mem } := by
  obtain ⟨h_cur_privilege, h_mprv_disabled, _, h_htif, h_pma⟩ := hconfig
  have hmprv' : Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 = 0#1 := by
    rw [show Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 =
      BitVec.ofNat 1 (BitVec.toNat (s.regs.get Register.mstatus (hs _)) >>> 17) from rfl]
    exact h_mprv_disabled
  simp [mem_write_value, mem_write_value_meta, mem_write_value_priv_meta,
    Std.ExtDHashMap.get?_eq_some_get (hs _),
    h_cur_privilege, effectivePrivilege, _get_Mstatus_MPRV, hmprv']
  have h := run_checked_mem_write_one_byte_of_isInitialized reg_val offset data
    s hs h_in_range h_htif h_pma
  rw [show (BitVec.ofNat 8 data.toNat : BitVec 8) = data from by
    apply BitVec.eq_of_toNat_eq; rw [BitVec.toNat_ofNat, Nat.mod_eq_of_lt data.isLt]] at h
  exact h

lemma run_vmem_write_of_width_1
    (rs_addr_bv : BitVec 5)
    (reg_val : BitVec 64)
    (offset : BitVec 64)
    (data : BitVec 8)
    (s : SailState)
    (hs : SailState.isInitialized s)
    (h_reg_val : s.get_reg? rs_addr_bv = some reg_val)
    (h_aligned : is_aligned_vaddr (virtaddr.Virtaddr (reg_val + offset)) 1 = true)
    (hconfig : SailState.isValidMemConfig s hs)
    (_h_does_fit : reg_val.toNat + offset.toNat + 1 < 2 ^ 64)
    (h_in_range : range_subset (zero_extend (BitVec.addInt (reg_val + offset) 0))
      (to_bits 1) (2#64 ^ 16) (2#64 ^ 48 - 2#64 ^ 16) = true) :
    (vmem_write (.Regidx rs_addr_bv) offset 1 data
      (MemoryAccessType.Store mem_payload.Data) false false false).run s = .ok (.Ok true)
        { s with mem := s.mem.insert (reg_val + offset).toNat data } := by
  obtain ⟨h_cur_privilege, h_mprv_disabled, h_mseccfg_disabled, h_htif, h_pma⟩ := hconfig
  have hmachine : (Privilege.Machine == Privilege.Machine) = true := rfl
  have hsatp_bare : (SATPMode.Bare == SATPMode.Bare) = true := rfl
  have hfetch : (MemoryAccessType.Store mem_payload.Data !=
      MemoryAccessType.InstructionFetch ()) = true := rfl
  have hrx : rX_bits (regidx.Regidx rs_addr_bv) s = .ok reg_val s := by
    have h := @run_rX_bits rs_addr_bv s
    simp only [EStateM.run] at h
    rw [h, h_reg_val]
  have hmprv' : Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 = 0#1 := by
    rw [show Sail.BitVec.extractLsb (s.regs.get Register.mstatus (hs _)) 17 17 =
      BitVec.ofNat 1 (BitVec.toNat (s.regs.get Register.mstatus (hs _)) >>> 17) from rfl]
    exact h_mprv_disabled
  unfold vmem_write vmem_write_addr ext_data_get_addr
  simp [SailME.run, PreSail.PreSailME.run, ExceptT.run, ExceptT.bind, ExceptT.mk,
    ExceptT.bindCont, ExceptT.lift, ExceptT.map, ExceptT.pure,
    MonadLift.monadLift, liftM, monadLift, Functor.map, Except.map,
    Bind.bind, Pure.pure, SailME.throw, PreSail.PreSailME.throw,
    bind, pure, EStateM.bind, EStateM.map, EStateM.pure, EStateM.run,
    hrx, h_aligned, split_misaligned, misaligned_order, untilFuelM, untilFuelM.go,
    LeanRV64D.Functions.not]
  simp [translateAddr, translationMode, effectivePrivilege,
    SailME.run, PreSail.PreSailME.run, ExceptT.run, ExceptT.bind, ExceptT.mk,
    ExceptT.bindCont, ExceptT.lift, ExceptT.map, ExceptT.pure,
    MonadLift.monadLift, liftM, monadLift,
    bind, pure, EStateM.bind, EStateM.map, EStateM.pure, Functor.map,
    Sail.readReg, PreSail.readReg, run_readReg_of_isInitialized s _ hs,
    Std.ExtDHashMap.get?_eq_some_get (hs _),
    getThe, MonadStateOf.get, MonadState.get, get, EStateM.get,
    modifyGet, MonadStateOf.modifyGet, MonadState.modifyGet, EStateM.modifyGet,
    privLevel_bits_backwards, privLevel_bits_forwards,
    hmprv', h_cur_privilege, hmachine, hsatp_bare,
    hfetch, is_shadow_stack_access]
  simp [mem_write_ea, is_store_conditional, write_kind_of_flags, hfetch,
    EStateM.map, EStateM.bind, EStateM.pure, EStateM.run,
    bind, Bind.bind, pure, Pure.pure, Functor.map,
    ExceptT.bindCont, ExceptT.pure, ExceptT.bind]
  have hconfig : SailState.isValidMemConfig s hs :=
    ⟨h_cur_privilege, h_mprv_disabled, h_mseccfg_disabled, h_htif, h_pma⟩
  have h := run_mem_write_value_one_byte_of_isInitialized reg_val offset data s hs h_in_range
    hconfig
  simp only [EStateM.run] at h
  simp [zero_extend, BitVec.addInt, Sail.BitVec.zeroExtend] at h ⊢
  rw [show Sail.BitVec.extractLsb data 7 0 = data from by
    simp [Sail.BitVec.extractLsb, BitVec.extractLsb, BitVec.extractLsb']]
  conv_lhs => rw [h]
  rfl

end SP1Clean.SailMem
