import Mathlib.Tactic
import Mathlib.Data.ZMod.Basic
import Batteries.Lean.EStateM
import LeanRV64D
import SP1Clean.Math.Misc
import SP1Clean.Model.Register
set_option linter.unusedSimpArgs false

/-! # The Sail-monad wrapper layer

The general run-lemma substrate every chip Sail bridge elaborates against — not just the Add
bridge it was first extracted for:

- `toSailM` and the `run_dite`/`run_ite`/EStateM lemmas — evaluate the generated model's monadic
  plumbing under `.run`.
- `write_reg` / `write_reg'` — project-side register writes over the `SailState` register map,
  with the self-overwrite and commutation lemmas (`write_reg'` is the `wX_bits`-shaped variant
  that drops an `x0` write; `write_reg_eq_write_reg'` names the exact agreement condition).
- The `run_readReg`/`run_writeReg` battery — evaluates the generated accessors against an
  `isInitialized` state, including the insert/lookup interaction lemmas.
- `rX_bits_eq_get_reg?` / `wX_bits_eq_write_reg'` / `run_rX_bits` / `run_wX_bits` — the bridges
  from the generated model's register accessors to the project-side map operations.
- `execute_RTYPE_pure`/`execute_RTYPE'` and `execute_RTYPEW_pure`/`execute_RTYPEW'` — pure twins
  of the generated R-type executors plus their equivalence lemmas (no `pure_w`/`bv_to_w` shift
  machinery; the shift chips carry their own reductions).
- `jump_to_of_mod4_eq_zero` — the aligned control-flow commit used by the jump/branch bridges.
- The file-scope `simp`/`local simp`/`grind` attribute blocks that make the generated helpers
  reduce during bridge proofs. -/

open LeanRV64D.Defs
open LeanRV64D.Functions
-- lean-sail v5 moved the state/monad machinery under `Sail.ConcurrencyInterfaceV1`; the root
-- `PreSail` namespace it leaves behind is empty, so an unqualified `PreSail.foo` resolves to
-- nothing without this. See `docs/agents/sail-model-provenance.md`.
open Sail.ConcurrencyInterfaceV1

set_option linter.style.setOption false

-- Helper functions generated by sail that we generally don't want in practice
attribute [simp] bit_to_bool bits_of_virtaddr bool_bit_backwards Sail.BitVec.access
  ext_control_check_pc currentlyEnabled Sail.BitVec.signExtend

attribute [local simp]
  regidxToRegister_inj
  nextPC_ne_reg_idx_toRegister
  PC_ne_reg_idx_toRegister
  encdec_reg_forwards_matches
  LeanRV64D.readReg
  PreSail.readReg
  Std.ExtDHashMap.get?_insert
  Std.ExtDHashMap.get?_insert_self
  Sail.BitVec.toNatInt

attribute [local grind =]
  nextPC_ne_reg_idx_toRegister
  PC_ne_reg_idx_toRegister
  EStateM.run_pure
  EStateM.run_throw
  EStateM.run_modify

grind_pattern Std.ExtDHashMap.get?_insert_self => (m.insert k v).get? k
grind_pattern BitVec.ofNat_eq_ofNat => (@OfNat.ofNat.{0} (BitVec n) i (@BitVec.instOfNat n i))

/-- A second insert at the same key overwrites the first: collapses the staged `nextPC ← pc+4` write
that a control-flow `jump_to`/`set_next_pc` immediately overwrites with the committed target. -/
@[simp] lemma ExtDHashMap_insert_insert_self {α : Type} {β : α → Type}
    [BEq α] [Hashable α] [LawfulBEq α] [LawfulHashable α]
    (m : Std.ExtDHashMap α β) (k : α) (a b : β k) :
    (m.insert k a).insert k b = m.insert k b := by
  apply Std.ExtDHashMap.ext_get?
  intro k'
  rw [Std.ExtDHashMap.get?_insert, Std.ExtDHashMap.get?_insert, Std.ExtDHashMap.get?_insert]
  split <;> rfl

set_option linter.style.longLine false

section sailboats

namespace Option

/-- Version of `Option.getM` using `throw` instead of `failure`. -/
def toSailM {α} (x : Option α) : SailM α :=
  Option.elim x (throw Sail.Error.Unreachable) pure

@[simp] lemma toSailM_none : toSailM (α := α) none = throw Sail.Error.Unreachable := rfl

@[simp] lemma toSailM_some (x : α) : toSailM (some x) = pure x := rfl

@[simp] lemma toSailM_map (f : α → β) (x : Option α) :
    (Option.map f x).toSailM = f <$> x.toSailM := match x with | none => rfl | some _ => rfl

end Option

namespace SailState

section get_reg?

/-- Read the value in the register corresponding to `idx`, giving an actual `BitVec 64`.
This avoids the issue of some (unused by us) registers having other length vectors. -/
@[grind] def get_reg? (s : SailState) (idx : BitVec 5) : Option (BitVec 64) :=
  if idx = 0 then some 0 else reg_idx_must_64 idx ▸ s.regs.get? (reg_idx_to_Register idx)

@[simp]
lemma get_reg?_insert_of_ne
  (h : reg ≠ reg_idx_to_Register idx) :
  SailState.get_reg? { s with regs := s.regs.insert reg v } idx =
  SailState.get_reg? s idx := by grind

@[simp]
lemma get_reg?_insert_self
  {s : SailState}
  (v : RegisterType (reg_idx_to_Register idx)) :
  let reg := reg_idx_to_Register idx
  SailState.get_reg? {s with regs := s.regs.insert reg v} idx =
  if idx = 0 then some 0 else reg_idx_must_64 idx ▸ some v := by grind

@[simp]
lemma get_reg?_insert_nextPC :
  SailState.get_reg? {s with regs := s.regs.insert Register.nextPC v} idx =
  SailState.get_reg? s idx := by aesop

@[simp]
lemma get_reg?_insert_PC :
  SailState.get_reg? {s with regs := s.regs.insert Register.PC v} idx =
  SailState.get_reg? s idx := by aesop

end get_reg?

end SailState

namespace Sail

@[simp low]
lemma run_dite (p : Prop) [Decidable p] (mx : p → SailM α) (mx' : ¬ p → SailM α) :
  (if h : p then mx h else mx' h).run = if h : p then (mx h).run else (mx' h).run :=
    apply_dite EStateM.run p mx mx'

@[simp low]
lemma run_ite (p : Prop) [Decidable p] (mx mx' : SailM α) :
  (if p then mx else mx').run = if p then mx.run else mx'.run :=
    apply_ite EStateM.run p mx mx'

section write_reg

/-- Alternative to `write_reg` that takes a `BitVec` rather than an explicit `Register`. -/
def write_reg (idx : BitVec 5) (val : BitVec 64) : SailM Unit := do
  let reg : Register := reg_idx_to_Register idx
  if idx != 0 then modify fun s =>
    { s with regs := s.regs.insert reg (reg_idx_must_64 idx ▸ val) }
  else if val ≠ 0 then throw Sail.Error.Unreachable

@[simp, grind =]
lemma run_write_reg :
    (write_reg idx val).run s =
      let reg : Register := reg_idx_to_Register idx
      if idx = 0 then if val = 0 then .ok () s else .error Sail.Error.Unreachable s
        else .ok () { s with regs := s.regs.insert reg (reg_idx_must_64 idx ▸ val) }
  := by unfold write_reg; aesop

@[simp]
lemma write_reg_write_reg_self :
    (do write_reg idx val; write_reg idx val') =
      if idx = 0 ∧ val ≠ 0 then throw .Unreachable else write_reg idx val'
:= by aesop

/-- Swap writes to two distinct registers, assuming only `0#5` written to the `0` register. -/
@[simp]
lemma write_reg_write_reg_comm
  (h : idx ≠ idx') (hval : idx = 0 → val = 0) (hval' : idx' = 0 → val' = 0) :
  (do write_reg idx val; write_reg idx' val') =
    (do write_reg idx' val'; write_reg idx val)
  := by
  -- The two `generalize`s are load-bearing for performance, not for the maths. This goal needs the
  -- permutative `@[simp] Std.ExtDHashMap.insert_insert_comm` (`Math/Misc.lean`), whose rewrite
  -- direction `simp` decides with the `Lean.Meta.acLt` term ordering — and left folded the inserted
  -- values are `reg_idx_must_64 idx ▸ val`, whose cast proof is the 31-arm `match` of
  -- `reg_idx_to_Register`. Ordering those repeatedly was the whole cost. Abstracting them first
  -- (Clean `doc/performance-problems.md`) takes this proof from >400k heartbeats to under default.
  unfold write_reg
  generalize (reg_idx_must_64 idx ▸ val : RegisterType (reg_idx_to_Register idx)) = v
  generalize (reg_idx_must_64 idx' ▸ val' : RegisterType (reg_idx_to_Register idx')) = v'
  aesop (add unsafe (by simp (disch := aesop)))

end write_reg

section write_reg'

/-- Version of `write_reg` that doesn't throw an error writing to the `0` register.
This matches more closely with the behavior of `wX_bits` -/
def write_reg' (idx : BitVec 5) (val : BitVec 64) : SailM Unit :=
  do if idx != 0 then modify fun s =>
    { s with regs := s.regs.insert (reg_idx_to_Register idx) (reg_idx_must_64 idx ▸ val) }

@[simp]
lemma run_write_reg' :
  (write_reg' idx val).run s =
    let reg : Register := reg_idx_to_Register idx
    .ok () (if idx = 0 then s
      else { s with regs := s.regs.insert reg (reg_idx_must_64 idx ▸ val) })
  := by unfold write_reg'; aesop

/-- `write_reg` and `write_reg'` align if not the `0` index of the value written is `0`. -/
@[simp]
lemma write_reg_eq_write_reg' (h : idx ≠ 0 ∨ val = 0) :
  write_reg idx val = write_reg' idx val := by unfold write_reg write_reg'; aesop

@[simp]
lemma write_reg'_write_reg'_self :
  (do write_reg' idx val; write_reg' idx val') = write_reg' idx val' := by aesop

/-- Swap writes to two distinct registers. -/
@[simp]
lemma write_reg'_write_reg'_comm (h : idx ≠ idx') :
  (do write_reg' idx val; write_reg' idx' val') =
    (do write_reg' idx' val'; write_reg' idx val)
  := by
  -- `generalize` first, for the `acLt` reason documented on `write_reg_write_reg_comm`.
  unfold write_reg'
  generalize (reg_idx_must_64 idx ▸ val : RegisterType (reg_idx_to_Register idx)) = v
  generalize (reg_idx_must_64 idx' ▸ val' : RegisterType (reg_idx_to_Register idx')) = v'
  aesop (add unsafe (by simp (disch := aesop)))

end write_reg'

section writeReg

@[simp]
lemma run_writeReg :
  (LeanRV64D.writeReg reg v).run s =
    .ok PUnit.unit { s with regs := s.regs.insert reg v} := rfl

@[simp]
lemma run_writeReg_bind (mx : Unit → SailM α) :
  (LeanRV64D.writeReg reg v >>= mx).run s =
    (mx ()).run {s with regs := s.regs.insert reg v} := by aesop

@[simp]
lemma writeReg_writeReg_self :
  (do LeanRV64D.writeReg reg v; LeanRV64D.writeReg reg v') = LeanRV64D.writeReg reg v' := by aesop

/-- Swap writes to two different registers. -/
@[simp]
lemma writeReg_writeReg_comm (h : reg ≠ reg') :
  (do LeanRV64D.writeReg reg v; LeanRV64D.writeReg reg' v') =
    (do LeanRV64D.writeReg reg' v'; LeanRV64D.writeReg reg v)
  := by aesop (add unsafe (by simp (disch := aesop)))

end writeReg

section readReg

-- dt: `run_readReg_of_isInitialized` works better with `simp`.
@[simp]
lemma run_readReg (s : SailState) (reg : Register) :
  (LeanRV64D.readReg reg).run s = match s.regs.get? reg with
  | some v => .ok v s
  | none => .error Sail.Error.Unreachable s := by aesop

lemma run_readReg_of_isInitialized (s : SailState) (reg : Register)
    (hs : SailState.isInitialized s) :
    (LeanRV64D.readReg reg).run s = .ok (s.regs.get reg (hs reg)) s := by
  rw [run_readReg]
  simp [Std.ExtDHashMap.get?_eq_some_get (hs _)]

/-- Bind version of `run_readReg_of_isInitialized`: inside an `EStateM.bind`,
the `readReg reg` step resolves to `s.regs.get reg _` under `isInitialized`.
Useful when the `readReg` is buried in a `do`-block that can't be collapsed
directly by the `.run s` form. -/
lemma run_readReg_bind_of_isInitialized {α : Type}
    (s : SailState) (reg : Register) (hs : SailState.isInitialized s)
    (k : RegisterType reg → SailM α) :
    (LeanRV64D.readReg reg >>= k).run s = (k (s.regs.get reg (hs reg))).run s := by
  simp only [bind, Bind.bind, EStateM.bind, EStateM.run]
  rw [show (LeanRV64D.readReg reg : SailM _) s = .ok (s.regs.get reg (hs reg)) s from
    run_readReg_of_isInitialized s reg hs]

/-- Direct-application variant of `run_readReg_bind_of_isInitialized`. Useful
when the `readReg reg >>= k` is syntactically applied to a state without a
visible `.run`, e.g. inside a `match … s with …` scrutinee. -/
lemma readReg_bind_apply_of_isInitialized {α : Type}
    (s : SailState) (reg : Register) (hs : SailState.isInitialized s)
    (k : RegisterType reg → SailM α) :
    (LeanRV64D.readReg reg >>= k) s = k (s.regs.get reg (hs reg)) s :=
  run_readReg_bind_of_isInitialized s reg hs k

@[simp]
lemma run_readReg_insert_of_ne (s : SailState) (h : reg ≠ reg') :
  (LeanRV64D.readReg reg').run { s with regs := s.regs.insert reg v} =
    match s.regs.get? reg' with
    | some w => .ok w { s with regs := s.regs.insert reg v }
    | none => .error .Unreachable { s with regs := s.regs.insert reg v } := by aesop

@[simp]
lemma run_readReg_insert_self (s : SailState) :
  (LeanRV64D.readReg reg).run { s with regs := s.regs.insert reg v } =
    .ok v { s with regs := s.regs.insert reg v } := by aesop

@[simp]
lemma map_const_run_readReg
  (h : (s.regs.get? reg).isSome) :
  ((LeanRV64D.readReg reg).run s).map (fun _ => x) = .ok x s
    := by
  rw [Option.isSome_iff_exists] at h
  aesop

/-- Inside `SailME.run`, reading one register (which must be present) and then writing
    another register while discarding the read value simplifies to just the writeReg's
    effect. This shows up in instruction specs where `execute_BTYPE` / `execute_JAL` read
    `Register.misa` purely to check the `C` extension bit before writing `nextPC`. -/
lemma SailME_run_readReg_map_writeReg
    {α : Type} (s : SailState) (reg_r reg_w : Register)
    (hs_r : (s.regs.get? reg_r).isSome) (v : RegisterType reg_w) (f : Unit → α) :
    EStateM.run ((PreSail.PreSailME.run do
        let _ ← liftM (LeanRV64D.readReg reg_r)
        f <$> liftM (LeanRV64D.writeReg reg_w v)) : SailM α) s =
      .ok (f ()) { s with regs := s.regs.insert reg_w v } := by
  rw [Option.isSome_iff_exists] at hs_r
  obtain ⟨v_r, hv_r⟩ := hs_r
  simp only [PreSail.PreSailME.run, LeanRV64D.readReg, LeanRV64D.writeReg, PreSail.readReg,
    PreSail.writeReg, ExceptT.run, ExceptT.mk, ExceptT.bindCont, ExceptT.bind, ExceptT.lift,
    ExceptT.map, Functor.map, Except.map, MonadLift.monadLift, liftM, monadLift, pure, bind,
    EStateM.run, EStateM.bind, EStateM.pure, EStateM.modifyGet, EStateM.map, EStateM.get,
    getThe, MonadStateOf.get, MonadState.get, get,
    MonadStateOf.modifyGet, modifyGet, MonadState.modifyGet, modify, hv_r]

end readReg

section rX_bits

-- A 32-way `fin_cases` peel of `rX_bits`/`rX`, each arm closed by a deep `simp` over the
-- generated Sail definitions.
lemma rX_bits_eq_get_reg? {s : SailState} :
  (rX_bits (regidx.Regidx idx)).run s = (s.get_reg? idx).toSailM.run s := by
  fin_cases idx <;>
    simp [Option.toSailM, SailState.get_reg?, Option.elim, reg_idx_to_Register, rX_bits, rX] <;>
    (first | rfl | (cases s.regs.get? _ <;> rfl))

@[simp high]
lemma run_rX_bits :
  (rX_bits (.Regidx idx)).run s =
  match SailState.get_reg? s idx with
  | some v => .ok v s
  | none => .error Sail.Error.Unreachable s
    := by
  rw [rX_bits_eq_get_reg?]; aesop

end rX_bits

section wX_bits

lemma wX_bits_eq_write_reg' (idx : BitVec 5) (val : BitVec 64) :
    wX_bits (.Regidx idx) val = write_reg' idx val := by
    symm
    simp [write_reg', wX_bits]
    by_cases x_is_31 : idx = 31#5
    · rw [x_is_31]
      simp
      simp [wX, LeanRV64D.writeReg, PreSail.writeReg, xreg_write_callback, xreg_full_write_callback,
        reg_name_forwards, get_config_use_abi_names, LeanRV64D.Functions.not, regval_into_reg]
    fin_cases idx
    · simp [wX, BitVec.toNatInt]
    all_goals
      simp [wX, LeanRV64D.writeReg, PreSail.writeReg, xreg_write_callback, xreg_full_write_callback,
        reg_name_forwards, get_config_use_abi_names, LeanRV64D.Functions.not, regval_into_reg,
        reg_idx_to_Register, BitVec.toNatInt]

@[simp high]
lemma run_wX_bits (reg : regidx) (data : BitVec 64) :
  (wX_bits reg data).run s = let .Regidx idx := reg
    .ok () (if idx = 0#5 then s else {s with
      regs := s.regs.insert (reg_idx_to_Register idx) (bitVecToRegidxVal idx data)}) := by
  let .Regidx idx := reg
  simp [wX_bits_eq_write_reg']
  fin_cases idx <;> simp [xreg_write_callback, reg_name_forwards, get_config_use_abi_names, LeanRV64D.Functions.not] <;> rfl

@[simp high]
lemma wX_bits_eq_writeReg :
  wX_bits (.Regidx idx) val = if idx = 0#5 then pure () else
    LeanRV64D.writeReg (reg_idx_to_Register idx) (bitVecToRegidxVal idx val) := by
  simp [wX_bits_eq_write_reg', write_reg']
  aesop

end wX_bits

section write_read_bind

/-- Reading a just written value looks like just using the written value. -/
@[simp]
lemma writeReg_readReg_bind
  (mx : RegisterType reg → SailM α) :
  (do LeanRV64D.writeReg reg v; let w ← LeanRV64D.readReg reg; mx w) =
    (do LeanRV64D.writeReg reg v; mx v) := by aesop

end write_read_bind

@[simp]
lemma writeReg_bind_map_readReg
  (f : RegisterType reg → α) :
  (do LeanRV64D.writeReg reg v; f <$> LeanRV64D.readReg reg) =
    (do LeanRV64D.writeReg reg v; return f v) := by aesop

/-- Writing a value overwrites the previous write. -/
@[simp]
lemma writeReg_wX_bits_writeReg :
  (do LeanRV64D.writeReg reg v; wX_bits typ_0 data; LeanRV64D.writeReg reg v') =
    (do wX_bits typ_0 data; LeanRV64D.writeReg reg v') := by aesop

section pc

@[simp] lemma set_next_pc_eq :
  set_next_pc pc = LeanRV64D.writeReg Register.nextPC pc := rfl

@[simp] lemma get_next_pc_eq :
  get_next_pc u = LeanRV64D.readReg Register.nextPC := rfl

@[simp] lemma tick_pc_eq :
  tick_pc u = (do LeanRV64D.writeReg Register.PC (← LeanRV64D.readReg Register.nextPC))
  := by unfold tick_pc; aesop

-- @[simp] lemma force_pc_eq :
--   force_pc pc = LeanRV64D.writeReg Register.PC pc := rfl

end pc

end Sail

end sailboats

section execution
open PreSail
open LeanRV64D.Functions

@[simp]
lemma bool_bits_forwards_to_if :
  bool_bit_forwards b = if b then 1#1 else 0#1 := by aesop

section RTYPE

/-- `execute_RTYPE` pure part -/
def execute_RTYPE_pure (op1 : BitVec 64) (op2 : BitVec 64) (op : rop) :=
  match op with
  | .ADD => op1 + op2
  | .SLT => zero_extend (m := 64) (bool_to_bit (zopz0zI_s op1 op2))
  | .SLTU => zero_extend (m := 64) (bool_to_bit (zopz0zI_u op1 op2))
  | .AND => op1 &&& op2
  | .OR => op1 ||| op2
  | .XOR => op1 ^^^ op2
  | .SLL => Sail.shift_bits_left op1 (Sail.BitVec.extractLsb op2 (LeanRV64D.Functions.log2_xlen -i 1) 0)
  | .SRL => Sail.shift_bits_right op1 (Sail.BitVec.extractLsb op2 (LeanRV64D.Functions.log2_xlen -i 1) 0)
  | .SUB => op1 - op2
  | .SRA => shift_bits_right_arith op1 (Sail.BitVec.extractLsb op2 (LeanRV64D.Functions.log2_xlen -i 1) 0)

/-- `execute_RTYPE` with isolated pure part -/
def execute_RTYPE' (rs2 : regidx) (rs1 : regidx) (rd : regidx) (op : rop) : SailM ExecutionResult := do
  let rs1_bits ← do (rX_bits rs1)
  let rs2_bits ← do (rX_bits rs2)
  (wX_bits rd (execute_RTYPE_pure rs1_bits rs2_bits op))
  (pure RETIRE_SUCCESS)

@[simp]
lemma execute_RTYPE_eq_execute_RTYPE' :
  execute_RTYPE rs2 rs1 rd op = execute_RTYPE' rs2 rs1 rd op
  := by cases op <;> simp_all [execute_RTYPE', execute_RTYPE, execute_RTYPE_pure, LeanRV64D.Functions.xlen]

end RTYPE

section RTYPEW

/-- `execute_RTYPEW` pure part: the W-instructions operate on the low 32 bits of the
operands and **sign-extend** the 32-bit result back to 64 bits (verbatim from the Sail
`execute_RTYPEW` body in `LeanRV64D/InstsEnd.lean`). -/
def execute_RTYPEW_pure (op1 : BitVec 64) (op2 : BitVec 64) (op : ropw) : BitVec 64 :=
  let rs1_val := Sail.BitVec.extractLsb op1 31 0
  let rs2_val := Sail.BitVec.extractLsb op2 31 0
  let result : (BitVec 32) :=
    match op with
    | .ADDW => (rs1_val + rs2_val)
    | .SUBW => (rs1_val - rs2_val)
    | .SLLW => (Sail.shift_bits_left rs1_val (Sail.BitVec.extractLsb rs2_val 4 0))
    | .SRLW => (Sail.shift_bits_right rs1_val (Sail.BitVec.extractLsb rs2_val 4 0))
    | .SRAW => (shift_bits_right_arith rs1_val (Sail.BitVec.extractLsb rs2_val 4 0))
  (sign_extend (m := 64) result)

/-- `execute_RTYPEW` with isolated pure part. -/
def execute_RTYPEW' (rs2 : regidx) (rs1 : regidx) (rd : regidx) (op : ropw) : SailM ExecutionResult := do
  let rs1_bits ← do (rX_bits rs1)
  let rs2_bits ← do (rX_bits rs2)
  (wX_bits rd (execute_RTYPEW_pure rs1_bits rs2_bits op))
  (pure RETIRE_SUCCESS)

@[simp]
lemma execute_RTYPEW_eq_execute_RTYPEW' :
  execute_RTYPEW rs2 rs1 rd op = execute_RTYPEW' rs2 rs1 rd op
  := by cases op <;> simp_all [execute_RTYPEW', execute_RTYPEW, execute_RTYPEW_pure]

end RTYPEW

section jump

/-- In the pinned generated Sail model, `jump_to target` runs:
  1. an extension hook `ext_control_check_pc target` (constant `none`),
  2. an `assert` that `target` bit 0 is `0`,
  3. an `if (bit_to_bool (target bit 1)) && (not (← currentlyEnabled Ext_Zca))` guard, else
  4. `set_next_pc target; pure RETIRE_SUCCESS`.
For `target % 4 = 0` both bit 0 and bit 1 are 0, so the assert passes and `bit_to_bool 0#1 = false`
short-circuits the `&&` regardless of the Zca read's value. The Zca read still executes monadically
(reading `misa`), but is state-preserving on `isInitialized s` — handled by
`SailME_run_readReg_map_writeReg`. The committed control-flow Sail bridges (JAL/JALR/BRANCH) consume this
to reduce `execute_*`'s `jump_to` to a single `nextPC` write. -/
theorem jump_to_of_mod4_eq_zero (target : BitVec 64) (s : SailState)
    (hs : SailState.isInitialized s) (h_aligned : target % 4#64 = 0) :
    EStateM.run (jump_to target) s =
      EStateM.Result.ok LeanRV64D.Functions.RETIRE_SUCCESS
        { s with regs := s.regs.insert Register.nextPC target } := by
  have h0 : target[0] = false := by bv_decide
  have h1 : target[1] = false := by bv_decide
  have hs_misa : (s.regs.get? Register.misa).isSome := by
    simp [Std.ExtDHashMap.get?_eq_some_get (hs _)]
  simp [jump_to, ext_control_check_pc, h0, h1]
  exact Sail.SailME_run_readReg_map_writeReg s Register.misa Register.nextPC hs_misa target
    (fun _ => RETIRE_SUCCESS)

end jump

end execution
