name: Lean Action CI

on:
  # Run on push to `master` or any pull requests
  push:
    branches: ["main", "ci-testing"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on:
      [
        runs-on,
        runner=64cpu-linux-x64,
        spot=false,
        disk=large,
        "run-id=${{ github.run_id }}",
      ]

    steps:
      - uses: actions/checkout@v4
      # Test that the project builds without failure
      # Note: defaults to ignore warnings and deprecations, maybe change eventually
      - uses: leanprover/lean-action@v1
        with:
          build: "true"
          test: "false"
          lint: "false"
          use-github-cache: "true"

